### ISSUE TITLE
lux-file-list: Rückgabeobjekt bei Einzelupload ist kein Array

### ISSUE THREAD

**Issue by Mankner** [IHK-GfI/lux-components#104]
**Situation:**
Wenn bei der Komponente lux-file-list mehrere Dateien hochgeladen werden, dann enthält das gebindete Objekt ein Array von Uploaddaten. Wenn allerdings nur eine Datei hochgeladen wird, dann nur ein einzelnes Objekt.

**Problem:**
Backends müssen aufwendig konfiguriert werden, wenn Daten gemischt als einzelnes Objekt übergeben werden und mal als Liste. Da sie je nach Konfiguration der Schnittstelle entweder immer ein Einzelobjekt oder immer ein Array erwarten.

**Lösung:**
Die Konfigurationsmöglichkeit der Komponente sollte so erweitert werden, dass man auch bei dem Upload einer Datei festlegen kann, dass das gebindete Objekt ein Array mit einem Uploaddatensatz ist.

**Comment by thodic77** [comment]
Über die neue Property "luxSelectedFilesAlwaysUseArray" kann jetzt das oben beschriebene Verhalten gesteuert werden. Um die Schnittstelle nicht in einer Minorversion zu brechen, wurde der Default auf "false" gesetzt und somit bleibt das Verhalten wie bisher. Mit dem nächsten Hauptrelease 12.0.0 wird der Default dann auf "true" geändert. D.h. wer das Verhalten bereits vor dem nächsten Hauptrelease aktivieren möchte, muss das Property in der entsprechenden LUX-File-List auf "true" setzen.

**Comment by thodic77** [comment]
Test

- Demoseite "File-List" öffnen.
- Das Toggle "luxSelectedFilesAlwaysUseArray" aktivieren.
- Debugconsole öffnen (z.B. F12 im Chrome)
- Genau eine Datei hochladen.
- Prüfen, dass die selektierte Datei im Array ausgeliefert wird. 

![image](https://user-images.githubusercontent.com/32597554/130448128-3cabf34c-01ba-449c-a8fa-dc489dcdfb72.png)

Test

- Das Toggle "luxSelectedFilesAlwaysUseArray" deaktivieren.
- Debugconsole öffnen (z.B. F12 im Chrome)
- Genau eine Datei hochladen.
- Prüfen, dass die selektierte Datei **_nicht_** als Array ausgeliefert wird. 

![image](https://user-images.githubusercontent.com/32597554/130448566-e63e39ed-1f16-4093-a16f-91ff4dcb81c0.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 11.5.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
