### ISSUE TITLE
Einzelne Optionen im lux-radio disablen

### ISSUE THREAD

**Issue by realSchoki** [IHK-GfI/lux-components#105]
Derzeit können einzelne Optionen in der lux-radio componente nicht disabled werden.

**Comment by thodic77** [comment]
Einzelne Optionen können jetzt deaktiviert werden. 

Test

- Die Demoseite "Radio-Button" öffnen. 
- Prüfen, ob die erste Option deaktiviert ist. 
- Das Toggle "1. Option deaktivieren" deaktivieren.
- Prüfen, ob die erste Option wieder aktiv ist. 

![image](https://user-images.githubusercontent.com/32597554/130589380-7cde78fe-9462-4385-a328-4b70197fa182.png)

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 11.5.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
