### ISSUE TITLE
lux-filter-form - Buttonfarben sollten angepasst werden können

### ISSUE THREAD

**Issue by 4ngLo** [IHK-GfI/lux-components#107]
Die Buttonfarben der Filterkomponente (inklusive der zugehörigen Dialoge) sollten angepasst werden können.

**Comment by thodic77** [comment]
Die Buttonfarben sind jetzt konfigurierbar. 

Test

- Die Demoseite "Filter" öffnen.
- Die Buttonfarben verändern.
- Prüfen, ob die korrekten Farben angezeigt werden. 

![image](https://user-images.githubusercontent.com/32597554/130613655-57370222-9e2a-4d1a-be8f-80fe0efa9f72.png)

![image](https://user-images.githubusercontent.com/32597554/130613908-c469787a-6c29-4418-889a-6e6743917e9d.png)

![image](https://user-images.githubusercontent.com/32597554/130614016-6eb0df32-0e87-4671-97ab-cde00d11a2f1.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 11.5.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
