### ISSUE TITLE
Unterschiedliche Buttongrößen in lux-card-actions

### ISSUE THREAD

**Issue by caro-kos** [IHK-GfI/lux-components#114]
**Vor** der Umstellung auf Version 11 waren die Buttons in lux-card-actions gleich groß, wenn einer ein Icon hatte und der andere Button nicht (beide mit height 45px).
![grafik](https://user-images.githubusercontent.com/62592932/131454467-1d1a214a-6d33-4711-9f12-5d42aebf8a54.png)

css-Auszug - Button mit Icon: (Version 10.8.1)
![grafik](https://user-images.githubusercontent.com/62592932/131454568-fca9aecd-f7c4-42fb-b4ea-bc1b0f344229.png)

css-Auszug - Button ohne Icon: (Version 10.8.1)
![grafik](https://user-images.githubusercontent.com/62592932/131454614-977ee64f-75e2-4d20-9073-5f5482e760ea.png)

**Nach** Update auf Verison 11.0.0
Buttons sind unterschiedlich groß.
![grafik](https://user-images.githubusercontent.com/62592932/131454925-d345afa0-2010-4681-b1bc-5b31a6c16f45.png)

css-Auszug - Button mit Icon:
![grafik](https://user-images.githubusercontent.com/62592932/131454965-cc59ee78-af68-4913-a725-e2a2f41849db.png)

css-Auszug - Button ohne Icon:
![grafik](https://user-images.githubusercontent.com/62592932/131455121-63ef198d-bf06-4e3e-8a2f-07d11bdafcc5.png)

Verwendung: 
![grafik](https://user-images.githubusercontent.com/62592932/131455629-cada593a-56a8-4197-bdf6-2099d67d544e.png)

**Comment by thodic77** [comment]
Die Buttongrößen wurden korrigiert. 

![image](https://user-images.githubusercontent.com/32597554/135210795-5ef5f2fe-1a96-4924-9c89-e471e0e180a2.png)
