### ISSUE TITLE
Datepicker soll Datum auch ohne Sonderzeichen erkennen können

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#115]
Anforderung wäre hier, dass sich die Datepicker ebenso verhalten, wie EVA es auch kann. 

Sprich:
Ich gebe einfach ohne Punkte, Striche, etc. "02022002" ein und der Datepicker würde korrekterweise daraus 02.02.2002 machen. Es muss auch wirklich nur bei dem gesetzten, vollständigen Format klappen, da gibts gar keine großen Sonderwüsnche, dass es klug "112002" als 01.01.2002 oder xx.11.2002 erkennen soll.

**Comment by thodic77** [comment]
Vollständige Datumsangaben (z.B. "02022002") ohne Angabe von Sonderzeichen (z.B. ".", "-" oder "/") werden jetzt korrekt erkannt (z.B. "02022002" => "02.02.2002").

Test
- Demoseite "Datepicker" öffnen.
- Den Wert "02022002" in das Datepickerfeld eingeben.
- Prüfen, ob der Wert korrekt zu "02.02.2002" umgewandelt wurde. 

Eingabe:
![image](https://user-images.githubusercontent.com/32597554/132461110-f1b007e6-8227-44be-b361-fe3a80206758.png)

Ergebnis:
![image](https://user-images.githubusercontent.com/32597554/132461123-00df7100-b174-450f-a92c-0f5368ea7ad9.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 11.5.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
