### ISSUE TITLE
LuxLink soll wie ein üblicher Weblink agieren

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#117]
Beim LuxLink ist aufgefallen, dass evtl. nicht 1zu1 wie ein üblicher Link (mittels a-Tag+href z.B.) agiert wird. 

Klicks mit der mittleren Maustaste öffneten z.B. keinen neuen Tab, Strg+Klick wird auch nicht immer berücksichtigt. Evtl. müsste man auch zusehen, dass Mac und Co. auch berücksichtigt werden, da kenne ich spontan die Tastenkombi für neue Tabs nicht. 
Das sollte in diesem Ticket aber auf jeden Fall angegangen werden.

Ein Kontextmenü fehlt hier an der Stelle auch, wäre aber schon Luxus und die Kirsche auf dem Eisbecher.

**Comment by thodic77** [comment]
Der LUX-Link reagiert ab jetzt  auf...
... den mittleren Mausbutton.
... die Strg-Taste und
... die Cmd-Taste.

**Comment by thodic77** [comment]
@realSchoki: Bitte testen.

**Comment by thodic77** [comment]
Die Tests waren erfolgreich (siehe Pull Request-Kommentar) und dieser Pull Request kann gemergt werden.
