### ISSUE TITLE
Badge-Notification accent-Farbe noch Theme anpassen

### ISSUE THREAD

**Issue by tlandgraf** [IHK-GfI/lux-components#121]
Die Badge-Notificationaccent-Farbe ist im Theme "green" noch nicht "das richtige grün" ;-)

![image](https://user-images.githubusercontent.com/74006133/135426490-b6ef06ed-2c5d-4774-a393-761d33f3228f.png)

**Comment by patrowe** [comment]
Die Version 11.6.0 wurde eingebunden mit dem Fix.
