### ISSUE TITLE
Datumänderung per Tasteneingabe im IE nicht möglich

### ISSUE THREAD

**Issue by ckutzner33** [IHK-GfI/lux-components#13]
Im IE 11 ist es beim DatePicker nicht möglich nur ein Teil des Datums per Tastatureingabe zu ändern. Nach der Änderung von z. B. 27.04.2020 in 27.05.2020 steht im Value vom DatePicker  "1969-12-31T23:00:00.000Z".

**Comment by thodic77** [comment]
Das Datum (als String) im IE enthielt manchmal unsichtbare Steuerzeichen, die verhinderten, dass das Datum korrekt erkannt wurde.
