### ISSUE TITLE
Character-Counter für Inputfelder mit begrenzter Zeichenzahl

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#134]
Bei einer gesetzten LuxMaxLength soll ein Zähler für die bisher eingegebenen Zeichen angezeigt werden. 
Er soll rechts unterhalb der BottomLine des Inputfeldes auf Höhe des Hints stehen und nur bei FocsuIn sichtbar sein.
Er soll sowohl für das Lux-Input vom Typ "text" und die Lux-Textaria verfügbar sein.

Kein Focus:
![Screenshot 2021-10-28 115706](https://user-images.githubusercontent.com/49644099/139239219-dcee79e8-add1-4fac-a3f3-d5e201bbbef3.png)

Input mit Focus:
![Screenshot 2021-10-28 115555](https://user-images.githubusercontent.com/49644099/139239221-af42e4f4-0be4-4e49-8e18-7c287bb16787.png)

**Comment by patrowe** [comment]
Test:

- Demoseite Input öffnen
- luxtype = text setzen, für luxMaxLength einen Wert > 0 eingeben.
![image](https://user-images.githubusercontent.com/49644099/139848253-490d2eaf-9c25-4a3b-87a7-61fffbe7616f.png)
- in das Inputfeld klicken. Der Counter soll nun angezeigt werden und bei Eingabe mitzählen

**Comment by thodic77** [comment]
Erfolgreich getestet.
