### ISSUE TITLE
lux‐table: Selektion zurücksetzen bei neuen Daten

### ISSUE THREAD

**Issue by 4ngLo** [IHK-GfI/lux-components#136]
![image](https://user-images.githubusercontent.com/32597554/140509209-78760549-2677-4367-82c5-857da547be32.png)

![image](https://user-images.githubusercontent.com/32597554/140509220-8e5eb906-0b49-4072-98f3-3ebcbd474339.png)

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

**Test**

- Die Demoseite "Table-Server" öffnen. 
- Beliebig viele Checkboxen aktivieren. 
- Den Button "Neuladen" anklicken. 
- Prüfen, ob die Selektion zurückgesetzt wurde.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.0.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
