### ISSUE TITLE
lux-tab - Das Verwenden von Custom-Icons ermöglichen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#139]
Im Rahmen dieses Vorgangs sollen die Tabs erweitert werden, so dass auch ein Custom-Icon im Header angezeigt werden kann. Das neue Custom-Icon soll zentriert oder linksbündig angezeigt werden können.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

Test
- Die Demoseite "Tabs" öffnen. 
- Auf den Tab "Erweitert" wechseln.
- Das Feld "luxIconName" leeren. 
- Prüfen, ob das orangene Icon angezeigt wird. 

![image](https://user-images.githubusercontent.com/32597554/141949502-51d49a3f-dd2f-45db-bbd3-303d303b8fc9.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.0.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
