### ISSUE TITLE
lux-chips: Nach Selektion eines Chips erscheint keine Autocomplete Liste beim erneuten Mouse-Klick

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#142]
Die Komponente lux-chips öffnet eine Autocomplete Liste mit auszuwählenden Optionen beim ersten Fokussieren (Mouse-Klick in die Komponente).
Nach Auswahl einer Option bleibt der Fokus in der Komponente erhalten, so dass sich die Autocomplete Liste nur durch Eingabe eines Zeichens oder durch Foucus Out und anschliessendes Focus In öffnet.

Es wäre von der Benutzbarkeit einfacher, wenn sich die Autocomplete Liste durch einen erneuten Mouse-Klick in die Komponente (ohne ein vorheriges Focus Out) öffnen würde.

Dieses Verhalten kann auch gerne über ein Flag ein- und ausgeschaltet werden.

Hierzu müssten in der Datei lux-chips.component.ts 1 Änderungen vorgenommen werden:
1. Anlegen eines Input Flags, default Wert ist false:
![image](https://user-images.githubusercontent.com/72753526/140944651-2258e0b9-282a-49ce-9419-2cc96e23ac31.png)
2. Anpassen der Methode autoCompleteAdd(input, value):
![image](https://user-images.githubusercontent.com/72753526/140944942-fbdb6401-3838-4a97-818b-05eeedff6afa.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.0.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
