### ISSUE TITLE
Label der vertikalen Radiobuttons brechen nicht um

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#145]
Ist-Zustand: Das Label bei vertikalen Radiobuttons wird abgeschnitten.
![image](https://user-images.githubusercontent.com/32597554/142149142-96ba2613-06bb-4e98-9805-142722bea02c.png)

Soll-Zustand: Das Label bei vertikalen Radiobuttons wird umgebrochen.
![image](https://user-images.githubusercontent.com/32597554/142149516-455be263-7611-4835-a93c-f384b7923b01.png)

**Comment by thodic77** [comment]
Test

- Die Demoseite "Radio-Buttons" öffnen.
- Auf den Tab "Allgemein" wechseln. 
- Das Toggle "luxOrientationVertical" aktivieren. 
- Den Text "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. " in das Feld "Option 1" einfügen. 
- Prüfen, ob das Label umgebrochen wird.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
**Testablauf**
- Die Demoseite "Radio-Buttons" geöffnet.
- Tab "Allgemein" gewählt.
- Das Toggle "luxOrientationVertical" aktiviert.
- Den Text "Es gibt im Moment in diese Mannschaft, oh, einige Spieler vergessen ihnen Profi was sie sind. Ich lese nicht sehr viele Zeitungen, aber ich habe gehört viele Situationen. Erstens: wir haben nicht offensiv gespielt. Es gibt keine deutsche Mannschaft spielt offensiv und die Name offensiv wie Bayern." eingefügt. -> Bei einem solchen Text ist besser zu kontrollieren ob beim Umbruch etwas verschluckt wird. ;-)
- Das Label wird umgebrochen.

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.0.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> **OK**
MacOS: Safari, Chrome, Firefox -> **OK**
