### ISSUE TITLE
Lux-Filter-Form - Filtern mit Eingabetaste starten

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#147]
Ich möchte in der Filterform mit der Eingabetaste das Filtern starten. Ich möchte aber trotzdem beispielsweise autocomplete Einträge mit den Pfeiltasten und der Entertaste auswählen können, ohne dass der Filter gestartet wird.

**Comment by thodic77** [comment]
In den LUX-Components wird "Shift + Enter" als Standardtastaturkürzel für das Absenden (z.B. Formular) verwendet. D.h. das Filtern wird dementsprechend bei "**Shift + Enter**" und **nicht** bei "Enter" alleine ausgelöst. 

Zusätzlich hat der Filtern-Button einen Tooltipp mit dem Tastaturkürzel bekommen, damit die Benutzer entsprechend informiert sind. 

![image](https://user-images.githubusercontent.com/32597554/143256181-29d88e58-3f7d-408e-bc0d-94221f41fa8b.png)

Test

- Die Demoseite "Filter" öffnen. 
- Den Fokus in ein beliebiges Eingabefeld (z.B. Input) setzen. 
- Den Wert ändern. 
- Das Tastaturkürzel "Shift + Enter" betätigen. 
- Prüfen, ob das Filtern ausgelöst wurde.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
**Testablauf**

- Die Demoseite "Filter" geöffnet.
- Den Fokus in ein beliebiges Eingabefeld (z.B. Input) gesetzt.
- Den Wert geändert.
- Das Tastaturkürzel "Shift + Enter" betätigt.
- Das Filtern wird ausgelöst.

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.0.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
