### ISSUE TITLE
LUX-Datetimepicker im LUX-Filterform ergänzen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#149]
Die LUX-Filterform so erweitern, dass auch ein LUX-Datetimepicker verwendet werden kann. Zusätzlich soll auch die Filter-Demo um ein LUX-Datetimepicker erweitert werden.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

Test

- Die Demoseite "Filter" öffnen. 
- Das Filteraccordion aufklappen. 
- Im Datetimepicker einen Wert eintragen. 
- Den Button "Filtern" anklicken. 
- Prüfen, ob das Datum und die Uhrzeit korrekt sind. 

![image](https://user-images.githubusercontent.com/32597554/143413453-d4b34c90-ee67-409e-8d02-168e3f8200b1.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by thodic77** [comment]
Der Datepicker und Datetimepicker zeigen jetzt auch ihre Fehlermeldungen an. 

![image](https://user-images.githubusercontent.com/32597554/143450693-0a76b691-39d7-40c3-9642-cb68762561e8.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte noch einmal testen.

**Comment by DSeifer** [comment]
**Test**

- Die Demoseite "Filter" geöffnet
- Das Filteraccordion aufgeklappt
- Im Datetimepicker einen korrekten Wert eingetragen.
- Den Button "Filtern" angeklickt.
- Das Datum und die Uhrzeit werden korrekt übernommen 
- Im Datetimepicker einen falschen Wert eingetragen.
- Den Button "Filtern" angeklickt.
- Es wird die Hinweismeldung "Das Datum ist ungültig" angezeigt 

**HINWEIS: Besser wäre hier der Hinweistext "Die Datum-/Uhrzeitkombination ist ungültig."**

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.0.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
