### ISSUE TITLE
Autocomplete aktualisiert nicht korrekt.

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#151]
Problem:
Die Autocomplete Liste aktualisiert sich nicht sofort wenn die Optionsdaten sich ändern, sondern erst nachdem man anfängt in das Feld zu tippen.

Vorgehen:
Lux-Autocomplete mit Optionen erstellen -> Seite aufrufen -> Klick auf Autocomplete -> Optionen werden angezeigt -> Optionen z.B. durch Buttonclick ändern -> Auf Autocomplete klicken -> Die alten Optionen werden angezeigt -> Anfangen zu tippen, nach dem ersten Buchstaben werden die neuen Optionen geladen.

**Comment by thodic77** [comment]
Dieser Issue ist eine Dublette von Issue #89 und wurde mit der Version 11.0.1 behoben.
