### ISSUE TITLE
Prefix und Suffix bei Autocomplete Komponente

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#152]
Bei der Lux-Input hat man die Möglichkeit Icons am Anfang und am Ende einzufügen z.B. mit

` <lux-input-prefix><lux-icon [luxIconName]="'fas fa-cogs'"></lux-icon></lux-input-prefix>`

Die Funktionalität ist auch bei der Autcomplete Komponente nützlich, ist dort allerdings noch nicht möglich. Sie wird benötigt, um die Autocomplete Komponente besser stylen zu können.

edit: Mit Angular Material würde das z.B. so aussehen:
https://stackblitz.com/edit/angular-fertf8-k5qsg8?file=app%2Fform-field-prefix-suffix-example.html

**Comment by thodic77** [comment]
Die Anforderungen wurden umgesetzt. Ab jetzt können auch Präfixe und Suffixe bei Autocomplete-Komponenten verwendet werden, wie bei den Input-Komponenten. 

Test

- Die Demoseite "Autocomplete" öffnen. 
- Das Toggle "" aktivieren.
- Das Toggle "" aktivieren.
- Prüfen, ob der Präfix und Suffix korrekt angezeigt wird. 

![image](https://user-images.githubusercontent.com/32597554/148027406-c180ad44-8142-4097-86c1-219f0058776a.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet wie oben beschrieben.

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
