### ISSUE TITLE
Lux-Layout lässt sich nicht in Lux-Filter verwenden

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#153]
Wird zum Erstellen eines Formulars in einem lux-filter die lux-layout Komponente benutzt, funktioniert die Filterfunktion, sowie das Anzeigen der Chips und das Zurücksetzen des Filters nicht mehr. 

Mini-Beispiel: 

`
<lux-filter-form (luxOnFilter)="onFilter($event)" [(luxFilterExpanded)]="expanded"
                       [luxFilterValues]="initFilter" [luxShowChips]="true" luxTitle="Filter"
                       luxButtonRaised="true">
          <lux-layout>
          <lux-layout-form-row>
          <lux-autocomplete 
                            [luxLabel]="ausbildungsstaetteLabel" luxName="filterAusbildungsstaette"
                            [luxOptions]="autocompleteAusbildungsstaetteOptions" luxControlBinding="autocompleteAusbildungsstaette"
                            luxFilterItem *luxLayoutRowItem>
          </lux-autocomplete>
          </lux-layout-form-row>
          </lux-layout>
</lux-filter-form>
`

**Comment by thodic77** [comment]
Der Fehler wurde behoben. Ab jetzt können auch die lux-layout-form-row-Komponenten im Filter verwendet werden. 

Test (Das Beispiel in der Demo wurde auf die Komponente "lux-layout-form-row" umgestellt.) :

- Die Demoseite "Filter" öffnen. 
- Werte in die Filterfelder eintragen. 
- Den Button "Filtern" anklicken.
- Prüfen, ob das Filtern korrekte Daten anzeigt. 
- Prüfen, ob die Chips unterhalb des Filters angezeigt werden. 
- Den Button "Zurücksetzen" im Menü anklicken.
- Prüfen, ob die Filterdaten korrekt zurückgesetzt wurden.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet wie oben beschrieben.

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
