### ISSUE TITLE
Zurück Button im "neuen Stepper" ohne Funktion

### ISSUE THREAD

**Issue by casparhauser2001** [IHK-GfI/lux-components#157]
Der zurück Button reagiert scheinbar auf die "required validation" und ist damit ohne Funktion bei nicht vollständig ausgefülltem Formular:

![image](https://user-images.githubusercontent.com/3949829/151115542-d0cc062f-aee3-44b7-ac69-4d3bc3b1ff8b.png)

**Comment by thodic77** [comment]
Die Demo wurde angepasst und der Zurück-Button wurde deaktiviert. 

Test 

- Die Demoseite "Stepper-Large" öffnen. 
- Zum Schritt 06 navigieren.
- Das Toggle "Zustimmung erforderlich" deaktivieren. 
- Prüfen, ob der Zurück-Button deaktiviert ist.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet wie oben beschrieben.

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
