### ISSUE TITLE
Feature-Request: Das multi-select in lux-tables soll pro Zeile aktiviert/deaktiviert werden können

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#158]
Für die lux-table Component kann über luxMultiSelect entschieden werden, ob die gesamte Tabelle um eine multi-select Möglichkeit erweitert wird.

Aktuell wünsche ich mir, dass das Selektieren (das Häkchensetzen) bei bestimmten Zeilen deaktiviert wird. Am liebsten über eine Funktion, welche für jeden Eintrag in der Tabelle an Hand der dahinter liegenden Daten entscheidet, ob eine Zeile selektierbar ist oder nicht. 

Grund dafür ist, das eine Aktion auf bestimmte Einträge einer Tabelle nicht möglich sein soll. Das kann zum Beispiel deshalb sein, weil der Anwender für diese Einträge keine Berechtigung für die Aktion besitzt.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

**Test**

- Die Demoseite "Tabelle" öffnen. 
- Das Toggle "luxMultiSelectDisabledProperty" aktivieren. 
- Prüfen, dass die erste und dritte Checkbox deaktiviert ist. 
- Prüfen, dass die Checkboxen auch nicht aktiviert werden können. 

![image](https://user-images.githubusercontent.com/32597554/157012984-5cf4f8d3-78a8-41ac-98a2-e017c706d156.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
