### ISSUE TITLE
LUX-Stepper-Large: Verbesserungen 1

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#161]
Im Rahmen dieses Issues sollen folgende Anforderungen umgesetzt werden. 

- Der Stepper soll weniger strikt sein und das Zurücknavigieren immer ermöglichen. 
- Schritte im Stepper sollen deaktiviert werden können. 
- Die Demo soll um einen Dialog in der Veto-Methode erweitert werden. 
- Die Demo soll um deaktivierte Schritte erweitert werden. 
- Verhinderung eines ExpressionChangedAfterItHasBeenCheckedError beim Setzen der Cursorposition (Tastatursteuerung).

**Comment by thodic77** [comment]
![image](https://user-images.githubusercontent.com/32597554/153822983-a119e80d-03f3-4584-8990-152e2b5e8da2.png)

Test

- Demoseite "Stepper-Large" öffnen. 
- Bis zum Schritt 08 navigieren. 
- Prüfen, ob die Schritte 06 und 07 deaktiviert sind und übersprungen wurden.
- Das Toggle "Zustimmung erforderlich" deaktivieren. 
- Auf den Schritt 01 klicken. 
- Prüfen, dass man nicht länger in dem Schritt 08 gefangen ist. Der Schritt 01 muss aktiv sein.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Wie oben beschrieben getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Chrome, Firefox -> OK
MacOS: Safari -> ERR (Darstellungsfehler im Meldungsfenster)
<img width="1056" alt="MacOS_Safari_#161" src="https://user-images.githubusercontent.com/75263741/153829705-a431e865-ce3b-4d22-abba-5bf263a9dced.png">

**Comment by DSeifer** [comment]
Der Darstellungsfehler ist ein Problem im lux-popup. Hierzu wird ein eigener Issue angelegt.
