### ISSUE TITLE
LUX-Lookup-Autocomplete wirft beim initialen Laden einen ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#165]
Im Rahmen dieses Issues soll der Initialisierungsfehler behoben werden. 

![image](https://user-images.githubusercontent.com/32597554/154269094-277aa27e-541a-41e0-b959-682f19ed6593.png)

**Comment by thodic77** [comment]
**Test**

- Die Demoseite "Lookup-Autocomplete" öffnen. 
- Prüfen, dass in der Debugkonsole (Chrome = F12) kein Fehler mehr zu sehen ist.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
