### ISSUE TITLE
LUX-Stepper - Es kann nicht über den Weiter-Button navigiert werden, wenn mehrere Schritte nachträglich hinzugefügt wurden

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#167]
Im Rahmen dieses Issues soll der Stepper angepasst werden, so dass der Weiter-Button korrekt funktioniert, auch wenn nachträglich mehrere Schritte hinzugefügt werden. Mit dem Fehler bleibt der Klick auf den Weiter-Button des nachträglich hinzugefügten Schritts effektlos.

**Comment by thodic77** [comment]
**Test**

- Die Demoseite "Stepper" öffnen. 
- Das Toggle "2 Schritte dynamisch hinzufügen" aktivieren. 
- Den Stepper über den Weiter-Button durchlaufen durchlaufen.
- Prüfen, ob man bis zum Ende des Steppers kommt. 

![image](https://user-images.githubusercontent.com/32597554/154274425-e3ab81ba-7e0c-42ad-9f06-0c89e1bfb6ed.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome -> OK

MacOS: Firefox -> ERR
Meldung in der Console:
[issue 167 - MacOS - Firefox.txt](https://github.com/IHK-GfI/lux-components/files/8080992/issue.167.-.MacOS.-.Firefox.txt)

**Comment by DSeifer** [comment]
Erneut getestet unter MacOS 12.2.1 mit dem Firefox-Browser  in der aktuellen Version.

MacOS: Firefox -> OK
