### ISSUE TITLE
Mehrere Fehler im LUX-Filter beheben

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#169]
1. Wenn ein Filter initial vorbelegt ist, dann zeigt die Debugconsole einen Fehler an und die Filterchips werden eventuell nicht korrekt aktualisiert. 
2. Der Laden-Button im Dialog ist im Vergleich zum Lösch-Button zu groß.
3. Wenn man im Firefox in einem Autocomplete-Feld das Filtern über die Tastatur (Shift + Enter) auslöst, fliegt ein Fehler in der Debugconsole. 

Zu 2.
![image](https://user-images.githubusercontent.com/32597554/154281906-08477ef6-fbe6-45cd-9475-55b8ca27672a.png)

**Comment by thodic77** [comment]
**Test**

- Die Demoseite "Filter" öffnen. 
- Prüfen, das initial kein Fehler in der Debugconsole (Chrome F12) zu sehen ist. 
- Prüfen, dass der Laden-Button im Dialog so groß ist wie der Lösch-Button.
- Prüfen, dass man Shift  + Enter im Autocomplete im Firefox drücken kann ohne das ein Fehler in der Debugconsole (Chrome F12) zu sehen ist.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
