### ISSUE TITLE
Events im App-Header

### ISSUE THREAD

**Issue by casparhauser2001** [IHK-GfI/lux-components#17]
Um im lux-app-header auch ohne eine lux-side-nav Komponente navigieren zu können wäre es hilfreich wenn das luxClicked Event auf den luxAppTitle/luxAppTitleShort und den luxIcon/luxImage Komponenten des Headers anwendbar ist. 

Damit könnte bspw. ein "zurück auf Home" über das Icon/Image oder den Titel abgebildet werden.

**Comment by thodic77** [comment]
Der Komponente "lux-app-header" wurde das Output-Event "luxClicked" (siehe [luxClicked](https://github.com/IHK-GfI/lux-components/wiki/lux%E2%80%90app%E2%80%90header#output)) hinzugefügt. 

![image](https://user-images.githubusercontent.com/32597554/86007740-1c991f80-ba18-11ea-89ab-8a5a7561be96.png)
