### ISSUE TITLE
LUX-Table-Spalten-Name bei Spaltenverschiebung mit anzeigen

### ISSUE THREAD

**Issue by mdlck** [IHK-GfI/lux-components#171]
Aktuell wird beim Eintragen einer Spalte in luxResponsiveBehaviour die Spalte bei einer definierten Größe in eine andere Spalte verschoben. Dabei wird ebenfalls der verschobene Spaltenname mit in die Zielspalte verschoben.
Es wäre der Übersicht einer Tabelle sicherlich zuträglich, wenn der Spaltenname der eigentlichen Spalte ebenfalls in der jeweiligen Zeile mit angezeigt wird.

![grafik](https://user-images.githubusercontent.com/76776954/154664599-7fc2859e-e22c-45f0-aaf6-bd79c576443a.png)

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

Test

- Die Demoseite "Tabelle" öffnen.
- Auf den Tab "Erweitert" wechseln. 
- Bis zu den Optionen der Spalten runterscrollen. 
- Die folgenden Werte für die Symbol-Spalte setzen:
  - Responsive Verhalten  = Spalte - Name
  - Responsive MediaQueries * = xs, sm, md, lg
- Prüfen, dass auch die Werte der Name-Spalten ihre Überschriften anzeigen.

![image](https://user-images.githubusercontent.com/32597554/158178399-98f88fc4-8860-41ec-b022-51b67b2a2b9d.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.3 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
