### ISSUE TITLE
Zeilenumbruch im Label der Formcontrols, zulassen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#173]
Die Labels der Formcontrols sind nur einzeilig und überlange Labeltexte werden abgeschnitten. Dieses soll mit einem neuen Attribut einstellbar sein, damit die Labeltexte auch mehrzeilg sein können
![Screenshot 2022-02-21 133250](https://user-images.githubusercontent.com/49644099/154955961-111123e4-ea93-4e7d-8974-7f4c5fad7e10.png)
.

**Comment by DSeifer** [comment]
Alle betroffenen Forms- und Lookup-Komponenten wurden getestet.

Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
