### ISSUE TITLE
LUX-Filter-Form - Binding-Fehler während der Initialisierung

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#175]
Im Rahmen dieses Issues soll der folgende Binding-Fehler während der Initialisierung verhindert werden:
![image](https://user-images.githubusercontent.com/32597554/155729995-4d952262-0b6f-4622-a9fd-e220805374a3.png)

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

Test

- Die Demoseite "Filter" öffnen. 
- In der Debugconsole prüfen, dass der Fehler nicht mehr auftaucht.

**Comment by thodic77** [comment]
@patrowe: Bitte testen und Pull Request prüfen.

**Comment by patrowe** [comment]
Test unter Windows10 in den Browsern: Firefox, Chrome und Edge erfolgreich durchgeführt.
Unter MacOs 12.2.1 in den Browsern: Firefox, Chrome und Safari erfolgreich durchgeführt.
