### ISSUE TITLE
Option für mehrzeilige mat-option

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#177]
In Autocomplete- oder Dropdown-Feldern gibt es aktuell nur Umwege, um mehrere Zeilen darstellen zu lassen. Ich bin nicht umher gekommen, hier CSS Manipulationen auszuführen, nur um dann immer alle mat-options zu treffen, da diese in der DOM einzelne Elemente sind, welche nicht unter den lux-autocomplete (z.B.) liegen.

Mit folgendem Beispiel klappt es, aber dann immer nur für alle Autocomplete Felder, nachdem die Component geladen wurde...
```
// Wir wollen in Autocomplete-Auswahlboxen an dieser Stelle ordentliche Umbrüche sehen
::ng-deep .mat-autocomplete-panel > .mat-option {
  white-space: pre-line !important; // Umbrüche mittels "\n" überhaupt anzeigen

  height: unset !important; // nimmt die Component sich so oder so am Ende über "line-height"

  outline-style: dotted !important; // ohne Unterscheidung zw. Einträgen dann etwas schwierig
  outline-width: thin !important;
}
```

Hier würde ich mir wünschen, dass ich direkt Attribute der "in den Lux-Components" liegenden Material Components beeinflussen könnte. Wenigstens zu den passenden Attributen um eine mehrzeilige Darstellung gezielt zu beeinflussen.

**Comment by patrowe** [comment]
Standard: Der Text einer Option ist einzeilig und wird automatisch abgeschnitten:
![image](https://user-images.githubusercontent.com/49644099/158362631-989f4161-44a0-4527-af55-0a0f4de9c3df.png)

Mit der neuen Property luxOptionMultiline werden die Texte Mehrzeilig dargestellt:
![image](https://user-images.githubusercontent.com/49644099/158362328-fd710951-8e3a-4b6e-890f-2beaed702def.png)

Bitte testen:
1. Demo für Lux-Autocomplete öffnen
2.  Unter Konfiguration > Erweitert: luxOptionMultiline auf true setzen
3. in das Autocomplete-Feld klicken und die Anzeige im Dropdown-Panel prüfen (siehe oben)

![image](https://user-images.githubusercontent.com/49644099/158363468-b2ac52a8-f629-4f29-b5f0-7682e83cd6f1.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.3 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
