### ISSUE TITLE
LUX-Chips - Placeholder, Pfeilbutton und breite Vorschlagsliste

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#178]
Im Rahmen dieses Issues sollen die folgenden Punkte umgesetzt werden: 
1. Das Eingabefeld soll einen Placeholder unterstützen.
2. Eine neue Pfeil-Action (Caret Down) soll am Ende des Eingabefeldes hinzugefügt werden.
3. Die Vorschlagsliste soll so breit sein, wie das Chip-Element und nicht nur so breit wie das Eingabefeld.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
