### ISSUE TITLE
LuxSideNav - toggle-Event rausgeben

### ISSUE THREAD

**Issue by caro-kos** [IHK-GfI/lux-components#186]
Ein Wunsch: Das "toggle"-Event (ein- und ausklappen) der lux-side-nav soll nach aussen verfügbar gemacht werden, um darauf reagieren zu können.

**Comment by thodic77** [comment]
@patrowe: Bitte testen.

**Comment by patrowe** [comment]
Test unter Windows erfolgreich durchgeführt für die Browser Edge, Firefox und Chrome
