### ISSUE TITLE
Hilfedialoge auch in LUX-Dialogen ermöglichen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#188]
Im Rahmen dieses Issues soll eine Möglichkeit geschaffen werden, innerhalb eines LUX-Dialogs einen anderen LUX-Dialog (z.B. für Hilfetexte) anzuzeigen. Dialoge in Dialogen anzuzeigen, sollte natürlich das letzte Mittel der Wahl sein. 

Zum aktuellen Zeitpunkt kann immer nur ein LUX-Dialog angezeigt werden. Öffnet man einen zweiten LUX-Dialog, wird die aktuelle Referenz überschrieben und der äußere Dialog kann nicht mehr geschlossen werden.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

**Test**

- Die Demoseite 'Dialog' öffnen.
- Das Toggle 'Output-Events loggen' aktivieren. 
- Den Button 'Öffnen [Eigene Component]' anklicken. 
- Den Info-Button anklicken. 
- Den Info-Dialog mit 'OK' schließen. 
- Das Toggle 'AGB gelesen' aktivieren. 
- Den Dialog mit 'Ok' schließen.
- Prüfen, ob der äußere Dialog auch geschlossen wurde. 
- Prüfen, ob in der Debugconsole (F12 im Chrome) das Schließen protokolliert wurde. 

![image](https://user-images.githubusercontent.com/32597554/162732638-c359df16-fea1-42d4-94a8-8e2e3124454f.png)

**Comment by thodic77** [comment]
@patrowe: Bitte testen.

**Comment by patrowe** [comment]
Test unter Windows in den Browsern MS Edge, Chrome und Firefox erfolgreich durchgeführt.
