### ISSUE TITLE
LuxErrorPage ist nicht responsive

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#191]
Die LuxErrorPage ist auf mobilen Geräten nur schwer bis gar nicht bedienbar. 

Beispiel: 
* https://lux-components-develop.gfi.ihk.de/components-overview/example/error-page öffnen
* Alle Einstellungen im Default belassen und auf Fehlerseite öffnen klicken
* Über die Entwicklertools ein iPhone XR simulieren

--> Die angezeigte Seite sollte keinen Scrollbalken benötigen, um auf einem aktuellen Smartphone angezeigt werden zu können.

**Comment by patrowe** [comment]
Die LuxErrorpage passte sich in der mobilen Ansicht nicht der Bildschirmbreite an. Nur durch horizontales Scrollen waren die Elemente der Seite erreichbar.
![image](https://user-images.githubusercontent.com/49644099/165903443-45875fe6-54bd-40e7-8c67-c53d27f0759c.png)

Der Fehler ist nun behoben. Ansicht für das iPhone XR:
![image](https://user-images.githubusercontent.com/49644099/165903506-23c4e65b-963b-4906-8923-6bd6f7e7bd65.png)

Bitte, wie oben beschrieben testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.3.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Chrome (Standardumschaltung 400 x 756) -> OK
MacOS: Safari (mit diversen Mobile-Devices und div. OS-Versionen)-> OK
