### ISSUE TITLE
lux-filter-form Filter Tastenkombination konfigurierbar machen

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#192]
Die Komponente lux-filter-form liefert die fest verbundene Tastenkombination Shift+Enter als Möglichkeit das Filtern auszuführen. Diese Tastenkombination kollidiert jedoch stark mit anderen Tastenkombination in der selben Maske.

Deshalb ist es wünschenswert, den Filter mit einer beliebigen Tastenkombination konfigurieren zu können, um das Filtern auszulösen. Alternativ soll es möglich sein, die Tastenkombination gänzlich zu deaktivieren.

**Comment by patrowe** [comment]
Bitte Testen:

Im Demo lux-filter öffnen
![image](https://user-images.githubusercontent.com/49644099/166944083-fa15d190-8f5c-4f13-9acd-c0adbbbd53a8.png)

1.	Das Filterpanel öffnen
2.	Mit dem Mauszeiger über den Filterbutton hovern -> Tooltip wird angezeigt
3.	Einen beliebigen Eintrag im Formular verändern
4.	Auf der Tastatur gleichzeitig Shift+Enter drücken
5.	Das Filterpanel soll sich schließen und ein neues Chip mit dem neuen Eintrag sollte erscheinen
![image](https://user-images.githubusercontent.com/49644099/166944300-56bf4682-e284-414f-ad7a-f3c723793149.png)
6.	Unter Konfiguration – Tastaturkürzel: luxDisableShortcut aktivieren
![image](https://user-images.githubusercontent.com/49644099/166944432-fe48f0b5-a8b0-43f4-a058-2de8b1be716e.png)
8.	Die Schritte 1-4 wiederholen. Dieses mal sollte kein Tooltip erscheinen und das Filterpanel darf sich nicht schließen und das Filtern durchführen (kein neuer Chip, bei geschlossenem Panel)

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.3.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Opera, Google Chrome  -> OK
MacOS: Safari, Google Chrome, Firefox -> OK
