### ISSUE TITLE
Textarea in LuxLayout verliert Border

### ISSUE THREAD

**Issue by ckutzner33** [IHK-GfI/lux-components#193]
Wird eine LuxTextarea in LuxLayout verwendet, dann expandiert das Textfeld zwar bei mehrzeilige Eingaben aber die Bottom-Border verschwindet.

`<lux-layout>
  <lux-layout-form-row>
    <lux-textarea *luxLayoutRowItem luxLabel="Hinweis"></lux-textarea>
  </lux-layout-form-row>
</lux-layout>`

**Comment by patrowe** [comment]
Steht die Textarea in der der untersten Zeile eines Formulars führt es dazu, dass sie bei einer Zeilenzahl von mindestens drei Zeilen ihre Bottom-Border verliert. 

Dieses kann mit folgenden Workarounds behoben werden
-	Die lux-layout-form-row bekommt ein Margin-bottom, z.B.
`<lux-layout> <lux-layout-form-row class="lux-mb-1">
              <lux-textarea *luxLayoutRowItem luxLabel="Label der Textarea">
              </lux-textarea>
            </lux-layout-form-row> <lux-layout>`
-	Die Text-Area erhält einen zusätzlichen Hinweistext.

Mit der Überarbeitung der Lux-Layout-Component im nächsten Major-Release sollte das Problem behoben sein.
