### ISSUE TITLE
Eigene Menüs im App-Header

### ISSUE THREAD

**Issue by BenLad17** [IHK-GfI/lux-components#194]
Um einen Menüeintrag in der Kopfzeile zu erstellen, existiert aktuell die LuxAppHeaderActionNavComponent. Die Komponente akzeptiert LuxAppHeaderActionNavItemComponents. Dadurch ist es möglich, dem neuen Menüeintrag Werte für `luxLabel`, `luxIconName` etc. mitzugeben.
```
<lux-app-header-action-nav>
     <lux-app-header-action-nav-item luxIconName="fas fa-bell" luxColor="accent" luxTagId="action0">
     </lux-app-header-action-nav-item>
 </lux-app-header-action-nav>
```
Es soll außerdem möglich sein, eigene Menüs analog zur LuxAppHeaderRightNavComponent (User-Menü rechts oben, siehe Screenshot) zu erstellen und in der Kopfzeile darstellen zu lassen. Beim Klick auf das Icon oder den Titel öffnet sich das Menü und der Benutzer kann eine Auswahl treffen. Auf das Klick-Event kann reagiert werden.
![image](https://user-images.githubusercontent.com/48922322/165470667-f31407c0-425b-4eec-bdd0-dfa65934a3b8.png)
Eine Möglichkeit wäre, der LuxAppHeaderActionNavItemComponent analog zur LuxAppHeaderRightNavComponent eine Liste von LuxMenuItemComponents mitzugeben.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

![image](https://user-images.githubusercontent.com/32597554/167617324-06b5c9a4-699d-4518-b19c-95a160f9b43e.png)

**Test**

In dem Header der Demo wurde ein IHK-Selektor-Dummy eingefügt, um zu zeigen, dass es ab jetzt möglich ist, eigene Menüs einzubinden. 

- Die Demoseite öffnen. 
- Prüfen, ob der IHK-Selektor zu sehen ist und funktioniert. D.h. wenn man ein Menü-Item anklickt, sollte eine Snackbarmeldung erscheinen.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.3.1 mit folgenden Browsern in der jeweils aktuellen Version (auch responsive).
Windows 10: Edge, Firefox, Opera, Google Chrome -> OK
MacOS: Safari, Google Chrome, Firefox -> OK
