### ISSUE TITLE
lux-app-footer: footer-Button "verschwindet" in Simulation iPhone XR

### ISSUE THREAD

**Issue by caro-kos** [IHK-GfI/lux-components#196]
Problem trat bei der Betrachtung der app-ok in Chrome auf. 
Simulation von verschiedenen Gerätetypen wurde getestet. 
Beim iPhone XR in Hochformat "verschwanden" Footer-Buttons.
![prob-app](https://user-images.githubusercontent.com/62592932/166199029-29a98701-9649-4783-8e18-5984b159749f.PNG)

Analyse ergab: sie rutschen anscheinend nur hinter die app-footer-links

**Nachstellbar in der Demo:**
http://lux-components.framework.apps.gfi.ihk.de/components-overview/example/app-footer

Chrome Entwicklertools und dort den Simulator
* iPhone XR in Hochformat
=> Button 1, der im 3-Punkte-Menü untergebracht wird "verschwindet"

Konfiguration für lux-app-footer-buttons anpassen
* Button 1
** label: Dokumentation
** alwaysVisible: false
* Button 2
** label: Overviewssssss (! lange Bezeichnung => man kann sehen, wie Button 1 hinter den Link "verschwindet" beim Tippen)
** alwaysVisible: true

Konfiguration für lux-app-footer-link anpassen
* beide Links 
** alwaysVisible: true
![prob-demo](https://user-images.githubusercontent.com/62592932/166198905-fe0772ca-bc3a-4352-a5aa-523a85c81994.PNG)

**Comment by patrowe** [comment]
Der Fehler wurde in der Lux-Menu-Component behoben.
Bitte wie oben beschreiben testen:

erwartetes Ergebnis: 
![image](https://user-images.githubusercontent.com/49644099/167572202-43f4e16c-08e0-4c86-b045-978cf004969d.png)

- der Menu-Button bleibt vollständig sichtbar 
- wird der Text im Button "Overview" zu groß, "springt" der Menu-Button an den rechten Rand und alle Menü-Einträge sind im Panel
![image](https://user-images.githubusercontent.com/49644099/167572317-3d45613b-a115-465e-973d-a2e52e1807ba.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.3.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Opera, Google Chrome -> OK
MacOS: Safari, Google Chrome, Firefox -> OK
