### ISSUE TITLE
LUX-LOOKUP-COMBOBOX um einen Leereintrag erweitern

### ISSUE THREAD

**Issue by simply-dennis** [IHK-GfI/lux-components#2]
Die LUX-LOOKUP-COMBOBOX, wenn ein Wert ausgewählt worden ist, kann sie nicht mehr in den Zustand 'unselektiert' zurückkehren.

**Comment by simply-dennis** [comment]
Defaultmäßig wird ein zusätzlicher leerer Eintrag dargestellt. Eventobjekt ist 'undefined'.

**Comment by thodic77** [comment]
Erfolgreich getestet.
