### ISSUE TITLE
LUX-File-Upload-Komponente kann nicht im LUX-Dialog verwendet werden

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#200]
Eine LUX-File-Upload-Komponente öffnet in den zwei folgenden Fällen einen eigenen LUX-Dialog:

- Eine Datei soll ersetzt werden.
- Eine Datei soll gelöscht werden. ´

D.h. wenn die LUX-File-Upload-Komponente in einem LUX-Dialog verwendet wird und einer der beiden obigen Fälle auftritt, dann überschreibt dieser File-Upload-Dialog die Referenz im LuxDialogService. Dadurch kann der äußere Dialog, in dem die LUX-File-Upload-Komponente liegt, nicht mehr geschlossen werden.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.4 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Opera, Google Chrome -> OK
MacOS: Safari, Google Chrome, Firefox -> OK
