### ISSUE TITLE
lux-table - Zusätzliches Outputevent "luxSelectedAsArrayChange" einführen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#207]
Mit der Umstellung auf die LUX-Components 13 wurde das bereits vorhandene Outputevent `luxSelectedChange` vom Typ `any[]` auf den Typ `Set<any>` umgestellt, da im Strict-Modus die Typen vom Getter, Setter und Outputevent identisch sein müssen. Im Rahmen dieses Issues soll das neue Outputevent "luxSelectedAsArrayChange" eingeführt werden, damit die Projekte, die bereits vorher mit einem Array gearbeitet und keine Zeit für die Umstellung haben, weiter mit einem Array arbeiten können.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.4 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Opera, Google Chrome -> OK
MacOS: Safari, Google Chrome, Firefox -> OK
