### ISSUE TITLE
LUX-Chips - Erweiterungspaket I

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#209]
Im Rahmen dieses Issues sollen die folgenden Anforderungen umgesetzt werden: 

1. Die Chips sollen die neue Property `luxStrict` erhalten. Über dieses Property soll gesteuert werden, ob nur Einträge aus den Optionen übernommen werden können oder ob jede Eingabe akzeptiert wird. 
1. Die Chips sollen ein `luxControlBinding` bekommen, damit diese auch an ein Formular gebunden werden können, so wie die anderen Formularkomponenten (z,B. Input, Checkbox,...) auch.
1. Die ausgewählten Optionen sollen nicht länger als Vorschläge im Popupmenü angezeigt werden. Aktuell werden immer alle Optionen angezeigt, unabhängig davon, ob diese bereits ausgewählt wurden.

**Comment by thodic77** [comment]
Die Anforderungen wurden umgesetzt. 

1. Neue Property `luxStrict`

- Die Demoseite "Chips" öffnen. 
- Die Property `luxStrict` aktivieren. 
- Prüfen, ob man eine Option hinzufügen kann, die nicht als Option zur Verfügung steht.

![image](https://user-images.githubusercontent.com/32597554/174809690-a9f3b9da-5dcc-4515-8f10-c7ad46f55c32.png)

2. Neue Property `luxControlBinding`

- Die Demoseite "Chips" öffnen. 
- Prüfen, ob das Beispiel "Beispiel in Reactive-Form" funktioniert. 

![image](https://user-images.githubusercontent.com/32597554/174810171-7977851d-8b62-421e-aaf3-1b9f5d9fdbfd.png)

3. Die ausgewählten Optionen sollen nicht länger als Vorschläge im Popupmenü angezeigt werden. 

- Die Demoseite "Chips" öffnen. 
- Den Chip "Neuer Chip 1" hinzufügen. 
- Noch einmal in das Textfeld klicken.
- Prüfen, dass die Option "Neuer Chip 1" nicht länger angeboten wird. 

![image](https://user-images.githubusercontent.com/32597554/174810621-be7cde9d-9a13-4c6b-a604-97751c0951df.png)

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.4 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Opera, Google Chrome -> OK
MacOS: Safari, Google Chrome, Firefox -> OK
