### ISSUE TITLE
lux-app-footer: LuxAppFooterButtonInfo um die Property "prio" erweitern

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#211]
Die Footer-Buttons sollen um die Property "prio" erweitert werden. Über diese neue Property soll die Reihenfolge der Footer-Buttons beeinflusst werden können.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt.

**Test**

- Die Demoseite "App-Footer" öffnen.
- Die Felder "prio" der Footer-Buttons verändern. 
- Prüfen, ob sich die Reihenfolge entsprechend ändert.

![image](https://user-images.githubusercontent.com/32597554/175032191-f5fc0c06-1831-4803-8b4a-7c4dfe92e170.png)

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.4 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome -> OK
MacOS: Safari, Firefox, Chrome -> OK
