### ISSUE TITLE
Theme-Anpassung für Lux-Filter-Form testen 

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#214]
1. Der Filter-Button und das Filtermenü sollen getrennt werden. Der Button bleibt unten rechts als Primary-Button stehen, das Menü soll oben rechts über dem Filterformular angezeigt werden. Für das Layout des Filter-Buttons kann zwischen luxFlat oder luxStroked(default) gewählt werden.
2. Das Filter-Formular soll optional auch in einer Card angezeigt werden können.
3. Die neuen Form-Controls für das Theme-Authentic sollen als Filteritems zur Verfügung stehen

**Comment by patrowe** [comment]
Bugfixes durchgeführt:
 - Tolltip vom Filterbutton wird wieder angezeigt
 - Merge mit Components 13.1.0 durchgeführt
 - Menü-Trigger im Accordion nach rechts verschoben
 - im Theme: Hover für Menü-Trigger ergänzt

**Comment by thodic77** [comment]
## Fehler / Verbesserungen

- [ ] Die Labels `luxExpandedLabelOpen` und `luxExpandedLabelClose` sind hard-kodiert. Bitte I18n verwenden (siehe z.B. `luxButtonFilterLabel`).

## Tests

- [X] `public_api.ts`-Eintrag vorhanden? Ja
- [X] Testfälle übernommen? Ja
- [X] Browsertests (Chrome) durchführen
- [X] Code-Review durchführen

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.4 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: 
Edge = OK 
Firefox, Opera, Google Chrome = Das Menü hängt direkt neben dem Filter-Label -> **ERR**

MacOS: 
Safari, Google Chrome, Firefox = Das Menü hängt direkt neben dem Filter-Label -> **ERR**

**Comment by patrowe** [comment]
@DSeifer 
Der Fehler ist für mich unter Windows 10 nicht nachstellbar. Siehe Screenshots:
Opera:
![Image](https://user-images.githubusercontent.com/49644099/177328017-c83c67f5-43ef-4a95-a903-1648ea1f944f.png)
Firefox:
![Image](https://user-images.githubusercontent.com/49644099/177328308-1a5f2fd0-fe9d-45fb-9b3c-5b7492bd7119.png)
Chrome:
![Image](https://user-images.githubusercontent.com/49644099/177328565-549fa519-5b88-445d-989d-c413d94f0ac6.png)

Bitte den Test wiederholen und genauer beschreiben und Screenshots ergänzen.

**Comment by patrowe** [comment]
@DSeifer Problem erkannt: die Position des Trigger-Buttons war nur im Theme-Authentic verändert worden. 
Dieses wurde nun für die Themes "blue" und "green" ergänzt. Der Fehler darf nun in allen Themes nicht mehr auftreten.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 12.4 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10:
Edge, Firefox, Opera, Google Chrome = OK
MacOS:
Safari, Google Chrome, Firefox = Das Menü hängt direkt neben dem Filter-Label -> ERR
<img width="493" alt="Safari" src="https://user-images.githubusercontent.com/75263741/181248690-37c5c210-b036-4efd-a100-8b54b2df929a.png">
<img width="557" alt="Chrome" src="https://user-images.githubusercontent.com/75263741/181248710-32981c3a-ea1c-4bfd-bf42-b403564fc616.png">
<img width="543" alt="Firefox" src="https://user-images.githubusercontent.com/75263741/181248719-60e17b52-c80f-423d-9694-80a8b824881c.png">

**Comment by DSeifer** [comment]
Weitere Testdokumentation über FRAME-177 in Jira.

**Comment by DSeifer** [comment]
Das Problem mit der Positionierung des Menüs unter MacOS ist behoben.
