### ISSUE TITLE
Zugriff auf LuxLookupTableEntry in den LuxLookup-Komponenten

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#225]
Mir ist bei Verwendung der LuxLookup-Komponenten aufgefallen, dass die aus den Schlüsseltabellen geladenen LuxLookupTableEntry's nicht zugänglich sind.
Ich stand vor dem Problem, dass ich den Key einer Selektion einer LuxLookup-Komponente in der Datenbank gespeichert habe. Beim erneuten Laden der Eingabemaske sollte die in der Datenbank gespeciherte Selektion in der LuxLookup-Komponente vorselektiert sein. Dies ließ sich allerdings nur durch Laden und Ermittlung des LuxLookupTableEntry's über LuxLookupService.getLookupTable und anschließendem Setzen des luxValue realisieren. Daher müssen für einen solchen Fall die Einträge 2 mal geladen werden:

1. Beim Initialisieren der LuxLookupo-Komponente
2. Beim ermitteln des zu selektierenden Eintrags über den LuxLookupService.getLookupTable

Es wäre einfacher wenn die LouxLookup-Komponenten Zugriff auf die bereits geladenen LuxLookupTableEntry's geben würden. Dann müsste man die Einträge nicht ein zweites mal Laden. 
Könnt ihr die LuxLookup-Komponenten erweitern und den Zugriff auf die geladenen LuxLookupTableEntry's gewähren?

**Comment by thodic77** [comment]
Aktuell ist es wie folgt möglich: 

**Kurzbeispiel:** 

TS:
```typescript
  @ViewChild(LuxLookupAutocompleteComponent) lookupAutoComplete: LuxLookupAutocompleteComponent;

  loremIpsum() {
   console.log(this.lookupAutoComplete.entries);
  }
``` 

**Langbeispiel:** 

TS:
```typescript
  @ViewChild(LuxLookupAutocompleteComponent) lookupAutoComplete: LuxLookupAutocompleteComponent;
  entries: LuxLookupTableEntry[] = null;
  viewInit = false;

  ngAfterViewInit() {
    this.viewInit = true;

    // Hier sollte die updateLookupEntries-Methode aufgerufen werden,
    // da es seien kann, dass das Laden der Lookup-Entries bereits
    // geschehen ist.
    this.updateLookupEntries();
  }

  updateLookupEntries() {
    if (this.isReady()) {
      this.entries = this.lookupAutoComplete.entries;
    }
  }

  private isReady() {
    return (
      this.viewInit &&
      Array.isArray(this.lookupAutoComplete.entries) && this.lookupAutoComplete.entries.length > 0 &&
      (this.entries !== this.lookupAutoComplete.entries || this.entries.length !== this.lookupAutoComplete.entries.length)
    );
  }
```

**Comment by thodic77** [comment]
Im Rahmen dieses Issues wurde das zusätzliche Outputevent "luxDataLoadedAsArray" eingeführt.

**Comment by thodic77** [comment]
Der Pull Request wurde genehmigt.
