### ISSUE TITLE
Neue Component / neues Feature - Kammer-/Mandantenauswahl

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#230]
[ In Abstimmung mit Thomas wollen wir als Team VzF diesen Issue umsetzen ]

Für die LUX-Components soll die im Blueprint gezeigte Möglichkeit Mandaten zu wählen erweitert werden. Die Mandantennr. ohne jegliche Erklärung würde an vielen Stellen zu mehr Verwirrung, als tatsächlicher Funktionalität führen.

In diesem Issue soll eine Component gebaut werden, welche einen Lookup-Dropdown in den App-Header bringen kann.

**Comment by patrowe** [comment]
Wegen Inaktivität geschlossen.
