### ISSUE TITLE
Lux-Select Breite in Lux Layouts

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#231]
Wenn man ein Lux-Select in einer Lux-Card hat, welche in einem Layout ist, verbreitert sich die Card automatisch, wenn zuviele Einträge für ein Lux Select ausgewählt werden. Anbei ein Beispiel, welches das Verhalten reproduziert, und eine gif, die das Verhalten live zeigt.

Template
```
<div>
  <lux-card luxTitle="Card OHNE Lux-Layout">
    <lux-card-content>
      <lux-select [luxOptions]="options" [luxSelected]="selected" [luxMultiple]="true">
        <ng-template let-option>
          {{ option.label }}
        </ng-template>
      </lux-select>
    </lux-card-content>
  </lux-card>

  <lux-layout>
    <lux-layout-card-row>
      <lux-card luxTitle="Card MIT Lux-Layout" *luxLayoutRowItem>
        <lux-card-content>
          <lux-select [luxOptions]="options" [luxSelected]="selected" [luxMultiple]="true">
            <ng-template let-option>
              {{ option.label }}
            </ng-template>
          </lux-select>
        </lux-card-content>
      </lux-card>
    </lux-layout-card-row>
  </lux-layout>
</div>
```

Typescript
```
options: any[] = [
  {label: 'Seeeeeeeeeeeeeeeeeeeeeehr lang', value: '0'},
  {label: 'suuuuuuuuuuuuuuuper lang', value: '1'},
  {label: 'kurz', value: '2'},
  {label: 'ultraaaaaaaaaaaaaaaaaaaaaaaaaaaa lang', value: '3'},
  {label: 'das längste aller Label und auch noch die meisten Wörter', value: '4'},
  {label: 'Kann irgend ein Label noch länger sein? Nein, denn dies hier ist das längste', value: '5'}
]
selected: any = [this.options[0], this.options[1], this.options[2], this.options[3], this.options[4], this.options[5]];
```

![Animation](https://user-images.githubusercontent.com/48916130/182924035-9313b976-9c93-4b8f-9ee2-b616f4af9d97.gif)

**Comment by thodic77** [comment]
Vielen Dank für die gute Fehlerbeschreibung und Entschuldigung das es so lange gedauert hat!

Vor dem Fix:
![image](https://user-images.githubusercontent.com/32597554/205924324-bc082d9a-b75b-4c59-9193-d9f456fed85a.png)


Nach dem Fix:
![image](https://user-images.githubusercontent.com/32597554/205923985-d35626f3-f7aa-4e40-bec3-68cfb1d99d60.png)


### Test 

- In der Datei "card-row-example.component.html" den Inhalt  `<p>Bitte die Karte aufklappen, um die Konfiguration anzupassen.</p>` des "Item 1" der 2. Zeile durch den folgenden Schnipsel `<lux-select [luxMultiple]="true" [luxOptions]="['Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt', 'At vero eos et accusam et justo duo dolores et ea rebum', 'Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet']"></lux-select>` ersetzen. 
- Anwendung bauen und starten.
- Die Demoseite "Card-Row" öffnen.
- Das Select öffnen und alle drei Einträge auswählen. 
- Prüfen, dass die Oberfläche korrekt wie in dem Screenshot oben aussieht. D.h. es gibt keinen horizontalen Scrollbalken und die Karte darf nicht größer sein als die von Item 2.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test auf Mac (MacOS 13.0.1) im aktuellen Safari-Browser (nach geleertem Cache):
Wie beschrieben getestet. => ERR
Das bisherige Verhalten besteht weiterhin.
![Screenshot Issue #231](https://user-images.githubusercontent.com/75263741/207034403-498bea46-c30b-46f8-bbf1-61272dc00e13.png)
![Screenshot Mac Issue #231](https://user-images.githubusercontent.com/75263741/207034416-1e51f666-37ca-431a-9b2d-7c17f5d0971e.png)

**Comment by DSeifer** [comment]
Test auf Windows (Version 10) im aktuellen Edge-Browser (nach geleertem Cache):
Wie beschrieben getestet. => ERR
Das bisherige Verhalten besteht weiterhin.
![LUX Components – Microsoft_ Edge Issue #231](https://user-images.githubusercontent.com/75263741/207036812-1e8fab4f-7653-499c-a73a-d0a2e4e967cc.png)
![Screenshot Win Issue #231](https://user-images.githubusercontent.com/75263741/207036824-1ef77804-568c-4749-87e0-a550e3071f2e.jpg)

**Comment by DSeifer** [comment]
@thodic77 Leider konnte der Issue nicht erfolgreich getestet werden.

**Comment by DSeifer** [comment]
Test auf Mac (MacOS 13.0.1) im aktuellen Safari-Browser und unter Windows 10 im aktuellen Edge-Browser (nach geleertem Cache):
Nach einer nicht mehr nachvollziehbaren Branch-Problematik, konnte der Issue heute auf beiden Systemen **positiv getestet** werden.
