### ISSUE TITLE
lux-file-preview Wiki ist nicht vollständig

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#232]
GuMo, 

die glob Pattern stimmen für Version 11.13 der Components nicht überein, mit dem, was man lokal vorfinden wird.

Der PDF Worker muss in der "großen" Variante direkt aus pdfjs-dist eingebunden werden: 
`
"glob": "pdf.worker.js",
"input": "./node_modules/pdfjs-dist/build",
"output": "./assets/pdf"
`
Dementsprechend sollte auch der pdf.worker.js als Source angegeben werden im ngDoBootstrap, logischerweise.

**Comment by thodic77** [comment]
Danke für den Hinweise. Die Dokumentation hat nur den Weg für die 13er-Version beschrieben. Die Dokumentation für die 11er-Version wurde ergänzt und entsprechend gekennzeichnet. 

Die folgende Dokumentation wurde angepasst: 
https://github.com/IHK-GfI/lux-components/wiki/lux%E2%80%90file%E2%80%90preview
