### ISSUE TITLE
lux-stepper-large: Stepper mit nur einem Schritt zeigt nicht den Finish-Button an

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#233]
Wenn man einen Stepper mit nur einem Schritt hat, wird anstatt des Finish-Buttons der Weiter-Button angezeigt. Dieser wirft einen Fehler "ERROR TypeError: Cannot read properties of undefined (reading 'luxDisabled')", wenn er betätigt wird. Im Rahmen dieses Issues soll der Stepper angepasst werden, so dass dieser auch mit nur einem Schritt korrekt funktioniert.

**Comment by thodic77** [comment]
Test

- Die Demoseite "Stepper-Large" öffnen.
- In der Datei "src/app/demo/components-overview/stepper-large-example/stepper-large-example.component.html" alle Schritte bis auf den Zusammenfassungsschritt auskommentieren.
- Prüfen, ob der Abschließen-Button angezeigt wird.
- Prüfen, dass beim Klick auf den Button kein Fehler in der Console auftaucht.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 und MacOS 12.6 im Edge- und Safari-Browser. -> OK
