### ISSUE TITLE
lux-tabs: Tabs ohne Icons werden auf mobilen Auflösungen fehlerhaft dargestellt

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#235]
![image](https://user-images.githubusercontent.com/32597554/189895129-8a4314d0-c984-4366-8f39-11d9e726acc9.png)

**Comment by thodic77** [comment]
Der Fehler wurde behoben.
![image](https://user-images.githubusercontent.com/32597554/189897127-52568f7d-64fe-4f04-a828-d4b375757d8f.png)


Test

- Die Demoseite "Tabs" öffnen.
- Auf den Tab "Erweitert" wechseln.
- Bei jedem Tab das Suffix "Lorem ipsum" (z.B. Title 1 Lorem ipsum) anhängen.
- Bei jedem Tab die folgenden Felder leeren oder deaktivieren:
  - luxIconName
  - luxImageSrc
  - luxShowNotification
  - luxCounter
- Die Auflösung auf eine mobile Ansicht reduzieren. 
- Prüfen. ob die Tabs korrekt mit Pfeilen rechts und links dargestellt werden.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 und MacOS 12.6 in Edge und Safari. -> OK
