### ISSUE TITLE
Menu-Item luxColor hat keinen Effekt

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#238]
In einem lux-menu-item kann die Farbe über das Property lux-color eingestellt werden. Diese Einstellung scheint aber keinen Effekt zu haben. 

Nachstellbar unter https://lux-components-develop.gfi.ihk.de/components-overview/example/menu

**Comment by thodic77** [comment]
Die Dokumentation wurde wie folgt angepasst: 

_luxColor: Diese Property definiert die Farbe des Buttons, wenn dieser außerhalb des Menüs angezeigt (siehe luxDisplayExtended) wird._ 

D.h. die Farbe greift nur außerhalb des Menupopups. 
Sollte das nicht das Problem gewesen sein, bitte den Issue erneut öffnen.
