### ISSUE TITLE
LUX Stepper Large Komponente Styling Issue

### ISSUE THREAD

**Issue by batchi92** [IHK-GfI/lux-components#239]
### Problem:
Wenn der Title eines Steps zu lang ist und einen Zeilenumbruch erzeugt, dann ist der grüne Haken so weit rechts wie möglich. Ohne Zeilenumbruch ist dieser am Ende des Textes positioniert. Ist der Text vor und nach dem Umbruch etwas breiter als die halbe Gesamtbreite, kommt der Effekt besonders zur Geltung (Siehe Step 3 in folgender Abbildung).

![image](https://user-images.githubusercontent.com/63929101/198593536-35952278-a839-43ab-adca-689f7fdf90ee.png)

### Lösungsvorschlag:
Der Haken könnte mittels CSS content property in dem ::after Pseudoelement an den Text angehangen werden.

**Comment by patrowe** [comment]
Hallo Andreas, vielen Dank für deinen Hinweis. Entschuldige, dass wir den Issue erst jetzt bearbeitet haben. Aber mit der neuen Version 14 wurden auch die nie Icons eingeführt. Daher haben wir die Umsetzung der Änderung erst jetzt vorgenommen.
Die Änderungen erforderten eine gleichzeitig Anpassung der Theme Dateien und werden mit dem nächsten Release ausgliefert.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
