### ISSUE TITLE
LuxListItemComponent unterstützt nicht die luxTagId directive

### ISSUE THREAD

**Issue by batchi92** [IHK-GfI/lux-components#240]
Hi, wir verwenden die LuxListItemComponent mit dem luxClicked Event und den luxSelected Attribut, wodurch die LuxListComponent zu einer auswählbaren Liste wird. LuxTagIds währen hier wie bei allen anderen interaktiven Komponenten hilfreich.

![image](https://user-images.githubusercontent.com/63929101/203317406-06d826b3-ed3b-4ed3-958c-224c0be60447.png)

Danke :)

**Comment by thodic77** [comment]
Das LUX-List-Item unterstützt die Property `luxTagId` nicht direkt, aber man kann die Direktive `luxTagIdHandler` verwenden, um eine `luxTagId` zu setzen.  

`<lux-list-item ... luxTagIdHandler [luxTagId]="'item-1'" ></lux-list-item>`

Bitte nicht vergessen, das Modul `LuxDirectiveModule` zu importieren.
