### ISSUE TITLE
Dark-Mode Feature implementieren

### ISSUE THREAD

**Issue by realSchoki** [IHK-GfI/lux-components#241]
Um ein augenfreundliches Surfen auf Seiten mit Lux Components zu ermögglichen wäre es schön, wenn ein Dark Mode via z.B. Toggle oben rechts ermöglicht wird. 

Beispielsweise: 
![image](https://user-images.githubusercontent.com/9107986/203523899-4b10ed5e-10d9-4223-9838-cfb292d978a3.png)

Bild von https://dev.to/joyshaheb/light-dark-mode-toggle-button-using-1-variable-2021-css-js-13l

**Comment by patrowe** [comment]
Wegen Inaktivität geschlossen.
