### ISSUE TITLE
lux-menu-item tooltip sollte auch im luxDisplayExtended=false Fall funktionieren

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#242]
Hallo zusammen,

Das Property luxButtonTooltip bzw. luxTooltip führt zu keinem Ergebnis, wenn das lux-menu mit luxDisplayExtended=false konfiguriert ist. 

In dem Wiki-Eintrag wird auch geschrieben, dass das nicht funktionieren soll. Ich frage mich jedoch warum? Das ein Button in einem Menü manchmal Erklärung braucht, finde ich eine sehr gute Funktionalität.

**Comment by thodic77** [comment]
> In dem Wiki-Eintrag wird auch geschrieben, dass das nicht funktionieren soll. Ich frage mich jedoch warum?

Das Menü und der Tooltipp werden in einem Overlay dargestellt. D.h. ein Overlay wird über den anderen Overlay dargestellt und je nach Tooltipplänge kann der Tooltip andere Menüeinträge verdecken, so dass diese nicht mehr direkt ausgewählt werden können. Auch wenn es mehrere Einträge gibt und jeder einen Tootipp hat, kann es sehr unruhig werden. 

![image](https://user-images.githubusercontent.com/32597554/205867595-2824aa71-4c72-4098-aa14-9762fa364a16.png)

> Das ein Button in einem Menü manchmal Erklärung braucht, finde ich eine sehr gute Funktionalität.

Es wurde die neue Property `luxMenuTooltip` eingeführt. Dadurch kann man auch einen Tooltipp setzen, wenn das Item im Menü dargestellt wird. Dadurch kann man jetzt sehr flexibel die Tooltipps setzen. 

- nur für die Buttons,
- nur im Menü
- für Buttons und Menüs
- kürzere Tooltipps für Menüs
- ...

**Comment by DSeifer** [comment]
Getestet unter Windows 10 im Edge-Browser und unter MacOS 13.0.1 im Safari.

**Testablauf Menu**
- Die Demoseite "Menu" öffnen. -> OK
- Auf den Tab "Erweitert" wechseln. -> OK
- Für die Menüitems die Properties "luxButtonTooltip" und "luxMenuTooltip" setzen. -> **_ERR, Die Option "luxMenuTooltip" ist in der Demoanwendung nicht vorhanden._**
- Prüfen, ob die Tooltipps bei den Buttons angezeigt werden. -> OK, Im Beispiel mit LUX-Icons werden Tooltipps angezeigt.
- Auf den Tab "Allgemein" wechseln. -> OK
- Das Toggle "luxDisplayExtended" deaktivieren. -> OK
- Prüfen, ob die Tooltipps im Menü angezeigt werden. -> **ERR, Alle Icons bis auf das Burger-Menu verschwinden**

**Testablauf App-Footer**
- Die Demoseite "App-Footer" öffnen. -> OK
- Da es hier keinen Tab "Erweitert" gibt, wurde dieser Schritt ignoriert.
- Die Properties "luxButtonTooltip" und "luxMenuTooltip" existieren hier ebenfalls nicht. Die Property "Tooltip" wurde gesetzt. -> OK
- Prüfen, ob die Tooltipps bei den Buttons angezeigt werden. -> OK
- Auch den Tab "Allgemein" gibt es hier nicht.
- Ebenfalls ist das Toggle "luxDisplayExtended" nicht vorhanden.
- Auf den lux-app-footer-links ist anscheinend kein Tooltipp vorgesehen.

@thodic77: Der Test konnte leider nicht in jedem Punkt positiv abgeschlossen werden.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 im Edge-Browser und unter MacOS 13.0.1 im Safari.

**Testablauf Menu**

- Die Demoseite "Menu" öffnen. -> OK
- Auf den Tab "Erweitert" wechseln. -> OK
- Für die Menüitems die Properties "luxButtonTooltip" und "luxMenuTooltip" setzen. -> OK
- Prüfen, ob die Tooltipps bei den Buttons angezeigt werden. -> OK
- Auf den Tab "Allgemein" wechseln. -> OK
- Das Toggle "luxDisplayExtended" deaktivieren. -> OK
- Prüfen, ob die Tooltipps im Menü angezeigt werden. -> OK

**Testablauf App-Footer**

- Die Demoseite "App-Footer" öffnen. -> OK
- Da es hier keinen Tab "Erweitert" gibt, wurde dieser Schritt ignoriert.
- Die Properties "luxButtonTooltip" und "luxMenuTooltip" heißen hier "Tooltip (wenn Button" und Tooltip (im Menu)". Die Properties wurden gesetzt. -> OK
- Prüfen, ob die Tooltipps bei den Buttons angezeigt werden. -> OK
- Eine Darstellung des "Tooltip (wenn Menu)" war nicht möglich.
- Auch den Tab "Allgemein" gibt es hier nicht.
- Ebenfalls ist das Toggle "luxDisplayExtended" nicht vorhanden.
- Auf den lux-app-footer-links ist anscheinend kein Tooltip vorgesehen.
