### ISSUE TITLE
Option um Zurücksetzen des Filters in den Lux-Tables

### ISSUE THREAD

**Issue by TheLethalGoose** [IHK-GfI/lux-components#245]
Es wäre schön wenn Nutzer die Möglichkeit hätten, die von ihnen definierten Filter schnell zurückzusetzen.
Vielleicht mit einem kleinen 'x', rechts im/neben dem Input-Field.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. Das Filterfeld hat jetzt einen Button am Ende. 

Test

- Die Demoseite "Table" öffnen.
- Den Toggle "luxShowFilter" aktivieren.
- Im Filter einen beliebigen Wert eingeben.
- Prüfen, ob die Tabelle korrekt gefiltert hat. 
- Den X-Button im Filterfeld betätigen. 
- Prüfen, ob die ungefilterte Tabelle angezeigt wird.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.1 mit den jeweils aktuellen Browserversionen:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
