### ISSUE TITLE
Doppelte Einträge in lux.lookup-combobox

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#246]
Be Verwendung der "lux-lookup-combobox"-Komponente wird der letzte Eintrag immer gedoppelt.
Beispiel:
```
<lux-lookup-combobox luxLabel="Geschlecht" luxRenderProp="kurzText"
	[luxParameters]="parameters" luxTableNo="1031" luxLookupId="geschlechtLookup">
	
new LuxLookupParameters( {
	knr: '101,
	raw: false;
	fields: [ LuxFieldValues.kurz, LuxFieldValues.lang1, LuxFieldValues.lang2],
	keys: []
});
```

![doppelter_eintrag png](https://user-images.githubusercontent.com/72753526/208878721-ac562559-3e81-4bdc-a862-dfd5ed681657.png)

Kann dies gefixt werden oder gibt es einen Workaround um doppelte Einträge zu vermeiden?

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

**Test**

- Die Demoseite "Lookup-Combobox" öffnen.
- Auf den Tab "Erweitert" wechseln.
- Die Property "luxEntryBlockSize" auf "500" setzen.
- Die Combobox öffnen.
- Prüfen, dass der letzte Eintrag nicht doppelt vorkommt.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.2 mit den jeweils aktuellen Browserversionen getestet:

MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
