### ISSUE TITLE
Probleme mit LUX-Upload-Components und Dateigrößen

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#247]
U.A. in der lux-file-list sind in Version 11.14.0 noch einige Auffälligkeiten, welche wahrscheinlich mit in die neusten Versionen übernommen wurden.

- Problem 1: Die MB-Limits werden nicht korrekt berechnet. Hier wird die 10er Potenz und nicht die 2er Potenz betrachtet, sodass 20.300.000 Bytes 20.3 Megabyte sein sollen. Korrekt wäre aber hier MebiByte zu verwenden, sodass 20.300.000 Bytes ca. 19.36 MiB wären.
- Problem 2: Die Dateien, welche mittels Form-Binding in einer Liste landen, werden nicht entfernt, sollte die gesetzte Grenze bzgl. Dateigröße überschritten werden. Sprich ich lade eine 20.300.000 Byte große Datei in die File-list, bei gesetzten 20 MB maximaler Größe - so sehe ich den Validationerror, kann ihn aber niemals beheben.

Angehangene Dateien wurden unter Win11 per fsutil erstellt und sind nur Dummy-files!
[sample_20300000Byte.pdf](https://github.com/IHK-GfI/lux-components/files/10343540/sample_20300000Byte.pdf)
[sample_20MiB.pdf](https://github.com/IHK-GfI/lux-components/files/10343541/sample_20MiB.pdf)

**Comment by thodic77** [comment]
Die Probleme wurden behoben. 

**Test**

- Die Beispieldateien (siehe weiter oben) runterladen oder eigene erstellen.
- Die Demoseite "File-Input" öffnen. 
- Versuchen (z.B. via Drag&Drop) eine Datei hochzuladen.
- Prüfen, ob eine Fehlermeldung erscheint.
- Die Fehlermeldung über den X-Button ausblenden.
- Prüfen, ob die Fehlermeldung korrekt ausgeblendet wurde und die Komponente nicht mehr im Fehlerzustand (rot) ist.
- Das Limit auf 20MB (siehe luxMaxSizeMB) hochsetzen.
- Erneut versuchen die Datei hochzuladen.
- Prüfen, dass das keine Fehlermeldung erscheint.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 und MacOS 13.1 mit den jeweils aktuellen Browserversionen:

Ein grundsätzlich aufgefallenes merkwürdiges Verhalten in der Demo ist:
Nach dem Upload-Versuch der 20MB-Datei und dem Wegklicken der Fehlermeldung, lässt sich die gleiche Datei nicht erneut hochladen. Nach dem Hochsetzen von luxMaxSizeMB auf 20MB und der erneuten Dateiauswahl reagiert die Demoanwendung einfach gar nicht. Eine Datei anderen Namens lässt sich dann jedoch hochladen. -> ERR?

### Windows
**Theme - authentic** 
Edge: OK, Firefox: OK, Chrome: OK
**Theme - blue**
Edge: OK, Firefox: OK, Chrome: OK
**Theme - green** 
Edge: OK, Firefox: OK, Chrome: OK

### MacOS
**Theme - authentic** 
Safari: OK, Firefox: OK, Chrome: OK
**Theme - blue** 
Safari: OK, Firefox: OK, Chrome: OK
**Theme - green** 
Safari: OK, Firefox: OK, Chrome: OK

**Comment by DSeifer** [comment]
Das Problem mit dem fehlerhaften File-Handling beim Upload wurde in Issue #253 ausgelagert.
