### ISSUE TITLE
Lux-App-Header-AC: User-Menu wird immer angezeigt.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#248]
Das User-Menu bzw. der Trigger-Button werden im App-Header-Ac immer angezeigt, auch wenn kein User-Menu als Child-Element vorhanden ist.

**Comment by patrowe** [comment]
Der Fehler wurde gefixt. Wenn kein lux-app-header-ac-user-menu vorhanden ist, wird nicht mehr ein Trigger(bzw. leeres Panel) für das User-Menü angezeigt.

**Comment by thodic77** [comment]
Der Issue wurde erfolgreich getestet. 
Der zugehörige Pull Request kann gemergt werden.
