### ISSUE TITLE
Fehlerhaftes Handling beim Upload von zuvor abgewiesenen Dateien

### ISSUE THREAD

**Issue by DSeifer** [IHK-GfI/lux-components#253]
Im Rahmen des Issue #247 fiel auf, dass nach dem Versuch eine zu große Datei hochzuladen und dem Wegklicken der roten Fehlermeldung ein erneuter Upload einer gleichnamigen Datei nicht funktioniert. Die App reagiert einfach nicht. Dies betrifft folgende Komponenten:

- Lux-File-Input-Ac
- Lux-File-Upload

Bitte prüfen, wieso der Uploadversuch nicht erneut durchgeführt wird und das Problem beseitigen.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

Anmerkung: 
Der Fehler trat nur auf, wenn man den Upload-Button verwendet hat, aber nicht bei Drag&Drop.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.2 mit den jeweils aktuellen Browserversionen getestet:

MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
