### ISSUE TITLE
Icon-Pfad der neuen LUX-Icons in die Konfiguration aufnehmen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#254]
Im Rahmen dieses Issues soll die Konfiguration um die Property "iconBasePath" erweitert werden. Über diese Property soll der Icon-Pfad der neuen LUX-Icon individuell angepasst werden können.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

**Test (ohne Konfigurationsänderung)**

- Die Home-Seite (Kachelübersicht) öffnen.
- Prüfen, ob die Kacheln Komponenten, Iconsuche, Formulare, Baseline und Konfiguration Icons haben. 
- In der Debug-Console (Chrome F12) dürfen keine Fehler stehen, dass Icons nicht geladen wurden.

**Test (mit Konfigurationsänderung)**

- In der Datei "angular.json" im Abschnitt "projects.lux-components.architekt.build.configurations.development" den "baseHref": "/test/" eintragen:
```json
  "development": {
     ...
     "baseHref": "/test/" <--- Zeile einfügen
   }
```
- In der Datei "app.module.ts" die Konfiguration anpassen:
  ```ts
  const myConfiguration: LuxComponentsConfigParameters = {
    generateLuxTagIds: environment.generateLuxTagIds,
    iconBasePath: '/test/', <--- Zeile einfügen
    ...
  }
  ```
- Den Ordner ".angular" löschen.
- Server neustarten.
- Prüfen, ob die Kacheln (lokal http://localhost:4200/test) Komponenten, Iconsuche, Formulare, Baseline und Konfiguration Icons haben. 
- In der Debug-Console (Chrome F12) dürfen keine Fehler stehen, dass Icons nicht geladen wurden.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.2 mit den jeweils aktuellen Browserversionen getestet:

MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
