### ISSUE TITLE
Erste Iteration über das neue Theme Authentic 1.1

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#257]
Das neue Theme Authentic erfordete eine umfangreiche Überarbeitung der Components. 
Vergleiche https://github.com/IHK-GfI/lux-components-theme/issues/26

Für die Tests müssen jeweils der Zweig feature/Theme-Authentic 1.1 bei den Lux-Components und beim Lux-Components-Theme ausgewählt werden.

**Comment by patrowe** [comment]
@DSeifer Bitte Testen.

Vgl. dazu https://github.com/IHK-GfI/lux-components-theme/issues/26

**Comment by DSeifer** [comment]
Wie bereits am 20.01.2023 via Teams geschrieben, findest Du meine allgemeinen Testergebnisse in Confluence unter: https://confluence.gfi.ihk.de/x/JalTPg
Bitte meine Ergebnisse/Fragen dort kommentieren und dann ggf. den Issue zu mir zurückgeben. Ansonsten weiß ich nicht was ich hier noch testen muss.

**Comment by DSeifer** [comment]
Dieser Issue wurde gemeinsam mit #26 getestet und wird geschlossen.
