### ISSUE TITLE
Neue Features für lux‐autocomplete

### ISSUE THREAD

**Issue by BenLad17** [IHK-GfI/lux-components#26]
Wäre es beim lux‐autocomplete möglich analog zum lux-select eine luxPickValue-Funktion zu übergeben? Eventuell nur wenn luxStrict = true gesetzt ist.

Außerdem wäre es interessant die Daten für das lux‐autocomplete asynchron aus dem Backend zu laden und auch das Filtern ins Backend auszulagern, ähnlich wie bei der lux-table.

**Comment by thodic77** [comment]
> Wäre es beim lux‐autocomplete möglich analog zum lux-select eine luxPickValue-Funktion zu übergeben? 
> Eventuell nur wenn luxStrict = true gesetzt ist.

Das Lux-Autocomplete hat  eine luxPickValue-Funktion erhalten.  Erfordert luxStrict = true. 

> Außerdem wäre es interessant die Daten für das lux‐autocomplete asynchron aus dem Backend zu laden und auch das Filtern ins Backend auszulagern, ähnlich wie bei der lux-table.

Diese Anforderung wird nicht im Rahmen dieses Vorgangs umgesetzt. Der Filter oberhalb der Tabelle filtert im Client. Beim Filtern im Backend muss man sehr vorsichtig sein, damit nicht jeder Tastendruck einen Request ans Backend auslöst.
