### ISSUE TITLE
LuxFilePreviewService: Darstellung über Preview "durcheinander"

### ISSUE THREAD

**Issue by taubec** [IHK-GfI/lux-components#260]
Die Darstellung bei der open-Funktion des LuxFilePreviewService ist durcheinander gekommen. Zwar wird das Dokument angezeigt, jedoch sind die Schaltflächen zum Herunterladen und Schließen herunter gerutscht und nicht mehr oben rechts. Weiterhin wird zusätzlich ein großes Dokument-Icon angezeigt. Hier ein Screenshot aus der Demo: 
![LuxComponentsPreview](https://user-images.githubusercontent.com/81471669/215099586-c0a79c1b-4c53-4e35-bcf3-33d4bc34613f.png)

Die Schaltflächen sollten wieder nach oben rechts wandern und das Dokument-Icon könnte für meinen Geschmack weg. Genutzt wurde hier Chrome.

Die gleiche Problematik ergab sich beim lokalen Ausführen der Demo unter Safari. Die PDF-Preview teilt das gleiche Schicksal.

**Comment by taubec** [comment]
Der Grund ist das zu große Dokument-Icon, welches das Layout zerschiesst. In einer mobilen Ansicht verschwindet das komplett und die Anzeige ist wieder "schön".

Ich hab in der Datei lux-file-preview-toolbar.component.html das Attribut luxIconSize="1x" ergänzt und konnte das Problem damit beseitigen. Allerdings vermute ich, dass dies eher irgendwo an zentraler Stelle geschehen sollte, da die Angabe für das alte Icon auch nicht nötig war.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
