### ISSUE TITLE
Sortiermöglichkeit in lux-lookup-combobox

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#263]
Es gibt Schlüsseltabellen mit sehr vielen Einträgen, z.B. die Ländertabelle 1002 enthält 253 Einträge. Aktuell werden die anscheinend nach key sortiert aus der Schlüsseltabelle abgefragt und auch in dieser Reihenfolge in der Komponente dargestellt. Dies entspricht leider nicht der alphabetischen Sortierung der in der Komponente dargestellten Einträge, was die Verwendung großer Schlüsseltabellen nahezu unmöglich macht.

Daher wäre eine Funktionalität hilfreich, mit der man entweder bei der Abfrage oder bei der Darstellung angeben, nach welcher Spalte/Parameter die Einträge der Schlüsseltabelle sortiert sind.

**Comment by thodic77** [comment]
Es wurde die neue Property "`luxCompareFn`" eingeführt. D.h. es kann eine Compare-Funktion übergeben werden, die verwendet wird, um die Schlüsseltabelleneinträge zu sortieren. Für die Standardfälle wurden die folgenden Compare-Funktionen erstellt: 

- luxLookupCompareKeyFn
- luxLookupCompareKurzTextFn
- luxLookupCompareLangText1Fn
- luxLookupCompareLangText2Fn

### Test

- Die Demoseite "Lookup-Combobox" öffnen.
- Die Optionen der Combobox öffnen.
- Prüfen, dass die Schlüsseltabelleneinträge unsortiert angezeigt werden.
- Auf den Tab "Erweitert" wechseln.
- Das Toggle "luxCompareFn" aktivieren.
- Erneut die Optionen der Combobox öffnen.
- Prüfen, dass die Schlüsseltabelleneinträge sortiert angezeigt werden.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
