### ISSUE TITLE
Lux-Dialog Config und Breite von Komponenten im Dialog funktionieren nicht

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#264]
Lux-Dialog hat mit der aktuellen Version mehrere Fehler:

- die config Eigenschaft "disableClose" ist wirkungslos, der "x" Button wird immer angezeigt und ist auch funktionsfähig
- Wenn man die Breite und Höhe über die Config auf z.B. 80% stellt und der Dialog eine Lux-Card beinhaltet, nimmt diese Card nicht mehr die gesamte Breite ein. Dies scheint auch bei anderen Komponenten der Fall zu sein (z.B. Lux-File-Upload, zu sehen im Blueprint)

Das Verhalten kann man im Blueprint nachvollziehen

**Comment by taubec** [comment]
### disableClose wirkungslos (lokal, develop, Edge Browser):

![lux-dialog-disableClose](https://user-images.githubusercontent.com/81471669/216542283-88ae5cfc-c5d4-44cc-9558-87c86c21b648.png)

**Comment by schoflo** [comment]
Beispiel von dem 80% Dialog Desktop:
![image](https://user-images.githubusercontent.com/48916130/216904234-b6e2686b-3d5d-4bc2-99ea-9135e378f6a4.png)

Beispiel 80% Dialog mobil:
![image](https://user-images.githubusercontent.com/48916130/216904565-b344adce-0467-4b7a-85fb-04593d018f71.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
