### ISSUE TITLE
Fehler bei Aufruf von Custom Tabs

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#268]
Wenn man einen Custom Tab einbaut und aufruft, erscheint beim Aufruf die Fehlermeldung "contentTemplate should be initialized".
Das wurde auch mit dem Minimalbeispiel aus dem Wiki getestet. Dort tritt der Fehler ebenfalls auf.

![image](https://user-images.githubusercontent.com/48916130/216969163-3f6dc5e1-0d38-468b-b95d-9be023df9da7.png)

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

### Test

- Die Demoseite "Tabs" öffnen. 
- Auf den Tab "Beispiel 3" (Custom Tab) wechseln.
- Prüfen, dass die obige Fehlermeldung nicht mehr in der Debug-Console (Chrome F12) auftaucht.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
