### ISSUE TITLE
Neues FavIcon und AppIcon für den Header-Ac hinzufügen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#269]
Für das Demo soll ein eigenes Favicon gemäß des Designvorschlags hinzugefügt werden.
Dieses Icon wird auch als Appicon im Header-Ac benutzt.
Weiterhin soll der Header-Ac ein default-Icon anzeigen, falls kein AppIcon angegeben wird.

**Comment by patrowe** [comment]
Das AppIcon für die Demo wurde im Header ausgetauscht und das bisherige Brandlogo durch eine SVG-Datei ersetzt.
Im App-Header-AC wurden jeweils ein Default-Icon für das Brandlogo und das AppLogo hinterlegt. 
Die Stylings wurden im Theme angepasst, Vergleiche dafür 
https://github.com/IHK-GfI/lux-components-theme/issues/32

Für den TEST:

Den Zweig https://github.com/IHK-GfI/lux-components-theme/tree/feature/Issue_32_icon_buttons_in_ac_header
im Theme auschecken und lokal das Theme bauen. Anschließend lokal mit den Components verlinken.

Die Demo starten und auf das Theme Authentic wechseln.

Das neue Favicon soll im Browsertab erscheinen. 
![image](https://user-images.githubusercontent.com/49644099/217199612-be1e37e1-088e-4370-9a89-36a5fcf91fd5.png)

Im Header sollten das Brandlogo (oben links) nun das neue AppIcon (oben Mitte) im Header angezeigt werden.
![image](https://user-images.githubusercontent.com/49644099/217196698-61c65745-c2e7-419a-ae8e-f5a43bf43b21.png)

Jetzt in der Datei app.component.html  die Zeilen 140,141 löschen und die Datei speichern.
![Screenshot 2023-02-07 095821](https://user-images.githubusercontent.com/49644099/217198665-9b4912af-d22c-43ad-a8f9-b482e1d661d7.png)

Im Header sollten die Default-Logos (siehe Bild) angezeigt werden.
![image](https://user-images.githubusercontent.com/49644099/217198437-e8763be6-c954-44f3-9af9-a0c4541c1196.png)

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.

Überall ergibt sich das selbe Bild:
![before](https://user-images.githubusercontent.com/75263741/217792998-72797039-c1b1-4c7d-9ad8-c4364d982c63.png)
![after](https://user-images.githubusercontent.com/75263741/217793041-69b73d12-1425-47dd-9ca6-8f81407a53b8.png)

Das Icon vor dem Editieren der html-Datei hat die falsche Schriftart und der Text läuft bis zum Rand des Icons.

**Comment by patrowe** [comment]
@DSeifer Das Favicon für die App wurde ausgetauscht. Bitte erneut testen.
Das neue Default-Icon wird mit dem nächsten Release der lux-components-icons-and-font verfügbar sein.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
