### ISSUE TITLE
lux-checkbox und lange Texte

### ISSUE THREAD

**Issue by casparhauser2001** [IHK-GfI/lux-components#27]
mit der Componente lux-checkbox ist es momentan nur über eigene CSS (.mat-checkbox-layout { white-space: normal !important; ...) Elemente und manuelle Bereiche für die ErrorMessage möglich eine Checkbox mit langen Texten korrekt darzustellen. 
(dies ist eine allgemeine Problematik der mat-checkbox)
Kann ggf. dieses Problem in der Lux-Componente behoben werden?
 
![lux-checkbox_required_message](https://user-images.githubusercontent.com/3949829/88388065-10ed0e80-cdb4-11ea-9acd-60a30d53a272.jpg)
![lux-checkbox_long_text](https://user-images.githubusercontent.com/3949829/88388068-1185a500-cdb4-11ea-9799-5ba80002dc93.jpg)

**Comment by thodic77** [comment]
Aufgrund von Urlaub kam es zur Verzögerungen. 

Das Problem wird mit der LUX-Componentsversion 1.9.4 behoben.

**Comment by thodic77** [comment]
![image](https://user-images.githubusercontent.com/32597554/90638533-bb2e4980-e22d-11ea-99e0-80d0736fd3e8.png)

![image](https://user-images.githubusercontent.com/32597554/90638636-def18f80-e22d-11ea-9150-12b730a63761.png)
