### ISSUE TITLE
Auswahlbox bei lux-select-ac im Theme authentic ungünstig positioniert

### ISSUE THREAD

**Issue by ckutzner33** [IHK-GfI/lux-components#271]
In einer mobilen Ansicht wird die Auswahlbox bei Select ungünstig positioniert, wenn die Items zu lang sind. Die Items werden am Anfang abgeschnitten und können nicht erkannt werden.

![vp-select-neu](https://user-images.githubusercontent.com/66011448/217178649-da9cdf40-59bb-4157-915c-9b11f3099275.PNG)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by patrowe** [comment]
Für den Test den folgenden Zweig für das Theme-Authentic auschecken https://github.com/IHK-GfI/lux-components/pull/273 und das Theme lokal bauen und verlinken.

- Das Demo-Programm starten und das Theme-Authentic auswählen. 
- Die Komponente **lux-select-ac** öffnen.
- In der Entwickler-Konsole auf Responsive-Mode gehen und Samsung Galaxy S8+ (o.ä.) auswählen.
- das Panels der unterschiedlichen select-Felder auf der Seite Prüfen
- gewünschtes Ergebnis: die Panels werden in der Breite vollständig angezeigt

Den Test für die **lux-lookup-combobox-ac** widerholen.

Dafür bei der Konfiguration für die Combobox bei der Option luxRenderProp den Wert "langText1" einfügen.
![image](https://user-images.githubusercontent.com/49644099/217488084-5f164f7d-d39a-41d7-9823-1f6e654e4f85.png)
Danach den Test wie oben wiederholen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2.

Soweit OK. Bei den jeweiligen Multiselect-Beispielen fällt browser- und OS-unabhängig auf, dass die Auswahlliste etwas breiter gargestellt wird als bei single-select. Hier geht die Listenbreite über das Panel hinaus. Besteht die Möglichkeit hier die gleiche Breite hinzubekommen wie bei single-select?

Nach Rücksprache mit @thodic77 wird der Issue geschlossen, da das noch offene Designproblem separat gelöst werden soll.
