### ISSUE TITLE
LUX-Lookup-Combobox - Das Array des Output-Events "luxDataLoadedAsArray" wird nachträglich verändert

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#274]
Die LUX-Lookup-Combobox zeigt die Optionen blockweise an. D.h. es wird der erste Block (siehe "luxEntryBlockSize") von Optionen angezeigt. Die nächsten Blöcke werden nachgeladen, wenn die Benutzer mit der Maus oder Tastatur nach unten gehen. Intern werden dafür 2 Arrays verwendet. Im ersten Array sind alle Optionen enthalten und im zweiten die bereits sichtbaren Optionen. Beim Nachladen wird dann das erste Array um die eingestellte Anzahl reduziert und das zweite Array entsprechend gefüllt. Am Ende ist das erste Array leer und das zweite enthält alle Optionen. D.h. alle Optionen sind sichtbar. 

Der Fehler besteht darin, dass eine Referenz auf das erste Array durch das Output-Event "luxDataLoadedAsArray" verschickt wird, welches durch das Nachladen manipuliert wird, bis es am Ende leer ist. Im Rahmen dieses Issues muss die Komponente so umgebaut werden, dass das Array alle Einträge enthält, stabil bleibt und keine Manipulationen daran ausgeführt werden.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

### Test

- In der Methode "_updateDisplayedEntries_" der Datei "_lux-lookup-combobox-ac.component.ts_" die folgende Zeile am Ende einfügen, damit Logausgaben in der Debug-Console (F12 Chrome) geschrieben werden. 
  ```typescript
  console.log(`\nEinträge gesamt:     ${this.entries.length} \nEinträge sichtbar:   ${this.displayedEntries.length} \nEinträge ausstehend: ${this.invisibleEntries.length}`);
   ```
- Die Demoseite "Lookup-Combobox-Authentic" öffnen. 
- Die Optionen der Lookup-Combobox öffnen und bis zum Ende scrollen.
- Prüfen, ob in der Debug-Console folgendes steht: 
  ```bash
  Einträge gesamt: 254 (Vor dem Fix stand hier eine 0)
  Einträge sichtbar: 254
  Einträge ausstehend: 0
  ```
- Den Test analog für die Lookup-Combobox (bitte die folgende Datei "_lux-lookup-combobox.component.ts_" wie oben modifizieren) durchführen.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
