### ISSUE TITLE
Webfonts aus dem Theme einbinden

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#277]
Die Fonts für das neue Theme Authentic werden in dem Projekt [lux-components-icons-and-fonts](https://github.com/IHK-GfI/lux-components-icons-and-fonts) bereitgestellt und müssen über das Theme eingebunden werden.

**Comment by patrowe** [comment]
Die Umstellung auf Webfonts wurde durchgeführt.

**Comment by patrowe** [comment]
Bitte Testen!

**Vorbedingung:** 
- den Zweig über den Pullrequest auschecken, https://github.com/IHK-GfI/lux-components/pull/279
- _npm install_ in der Komandozeile ausführen
- evtl. lokal im System die Schriften Blogger Sans und Source Sans Pro deinstallieren
-  mit _npm run start_ das Demo starten

**Test:**
- In der Demo in den Bereich Formulare wecheseln und dort den Reiter "Webfonts" wählen
- Die dort abgebildeten Schriften, sollen wie folgt aussehen

![image](https://user-images.githubusercontent.com/49644099/220097319-e3c46477-23bd-440b-ac28-0b79d392d015.png)
![image](https://user-images.githubusercontent.com/49644099/220097578-f7898a1c-d5b8-49da-8bed-74281e91802e.png)

**Comment by patrowe** [comment]
@thodic77 Bitte Testen!

**Comment by thodic77** [comment]
Erfolgreich getestet.
