### ISSUE TITLE
lux-autocomplete - Performance mit großen Datenmengen verbessern

### ISSUE THREAD

**Issue by JBeckerSN** [IHK-GfI/lux-components#278]
Die Autocomplete-Komponente soll mit grossen Datenmengen (z.B. 14.000 Datensätze) zurechtkommen. Derzeit wird viel Zeit in der UI verbraucht.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

### Test

- Die Demoseite "Autocomplete" öffnen.
- In das Autocomplete-Feld klicken, damit sich das Optionsoverlay öffnet.
- Nach unten scrollen, bei ca. 85% des Scrollbalken sollte nachgeladen werden.
- Prüfen, ob der nächste Optionsblock (siehe Property _luxOptionBlockSize_) nachgeladen wurde.

Diesen Test für die folgenden Komponenten wiederholen: 

- Autocomplete-Ac
- Chips
- Chips-ac

**Comment by thodic77** [comment]
@patrowe: Bitte testen.

**Comment by patrowe** [comment]
Getestet unter Windows 10 Enterprise:
Mozilla Firefox  -> OK
Microsoft Edge -> OK
Google Chrome -> OK
