### ISSUE TITLE
lux‐datepicker: luxMaxDate greift bei 5- oder 6-stelligen Jahreszahlen nicht und luxValueChange empfängt event

### ISSUE THREAD

**Issue by StephanTh** [IHK-GfI/lux-components#28]
Voraussetzung:
- luxMaxDate gesetzt, z.B. 06.08.2021
- Verarbeitung des Values über luxValueChange

luxMaxDate greift bei Datumsangaben im Format dd.MM.yyyy wie gewohnt und luxValueChange wird nicht getriggert, wenn die Datumseingabe nach dem in luxMaxDate festgelegtem Datum liegt.

Erfolgt jedoch eine 5- oder 6-stellige Jahreszahleingabe (dd.MM.yyyyy oder dd.MM.yyyyyy) erscheint im Frontend für kurze Zeit der Hinweis (kaum sichtbar), dass das Maximaldatum (luxMaxDate) überschritten wurde und fälschlicherweise wird dann trotzdem luxValueChange getriggert als sei es ein zulässiges Datum.

**Comment by thodic77** [comment]
Aufgrund von Urlaub kam es zur Verzögerungen.

**Comment by thodic77** [comment]
Der Fehler wurde behoben.
