### ISSUE TITLE
Aria-Labels in Lux-App-Header-AC ergänzen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#281]
Die Aria-Labels für die neue Header-Komponente sollen ergänzt und zu denen in der bisherigen Komponente angepasst werden.

**Comment by patrowe** [comment]
Die Änderungen wurden durchgeführt.
Bitte Testen!

**Comment by thodic77** [comment]
Erfolgreich mit NVDA getestet.
