### ISSUE TITLE
lux-link-plain hover-effekt für blue/green-Theme und custom-style-class

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#284]
Der Hovereffekt ist im Blue- und im Green-Theme nur schwer zu erkennen und muss angepasst werden.

![image](https://user-images.githubusercontent.com/49644099/221880382-c346f35b-0a02-43e6-94ac-3ae2bd552723.png)

Weiterhin soll eine Custom-class als Property ergänzt werden. Damit sollen idividuelle Stylings für spezielle Anwendungsfälle ermöglicht werden. Z.B. Nutzen des Link-Plains in einer Breadcrumpkomponente.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt, zusätzlich wurde die Ausrichtung von Icon und Text an der Baseline durchgeführt.

**Comment by patrowe** [comment]
**Test für Lux-Link-Plain**

**Vorbereitung:**
1.	Den passenden Zweig für die lux-components und lux-components-theme jeweils auschecken.
2.	Das Theme lokal bauen und mit den Components lokal verlinken.
3.	Das Demo-Programm starten und die Seite für lux-link-plain öffnen.

**Test:**
1.	_Hover:_ der Hover-Effekt soll bei allen Beispiel-Links gleich sein, insbesondere beim Beispiel „Link-Plain mit einer Custom-Class“ zu prüfen. (Siehe Abbildung oben: default/unten: hover)
![image](https://user-images.githubusercontent.com/49644099/226596153-9a2fc993-1b14-4488-8ff9-fa309c4feaea.png)
![image](https://user-images.githubusercontent.com/49644099/226596429-26a21676-7bc3-42e2-806b-d8f42316df73.png)

2.	_Disabled:_ Unter Konfiguration luxDisabled auf true setzen. Die Beispiel-Links auf der Seite (Ausnahmen: Beispiele in der Liste und Breadcrump-Komponente) werden ausgegraut und sind auch nicht mehr durch Keyboard-Access (Tab) erreichbar.
![image](https://user-images.githubusercontent.com/49644099/226596646-884dc810-e527-4f3f-b2b3-ebb676f0e46e.png)

3.	_luxIconShowRight_: unter Konfiguration den Schieber vor luxIconShowRight auf "false" setzen.
Die Icons in den oberen beiden Links verschieben sich nach links, dabei darf sich der Link in der Zeile nicht nach oben oder unten verschieben.
![Screenshot-left](https://user-images.githubusercontent.com/49644099/226597884-e0074d64-5d5b-4284-887b-fbc5d91735c4.png)
![Screenshot-right](https://user-images.githubusercontent.com/49644099/226597916-4626bf62-6a5d-4bb0-8f04-03f5f61709e2.png)

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
