### ISSUE TITLE
lux-app-header-ac: Die neuen Properties "luxHideAppLogo" und "luxHideBrandLogo" einführen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#285]
Im Rahmen dieses Issues sollen die neuen Properties "luxHideAppLogo" und "luxHideBrandLogo" eingeführt werden. Über diese Properties kann gesteuert werden, ob das App- und Brand-Logo angezeigt werden.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt.

**Comment by thodic77** [comment]
### Test

- Eine beliebige Demoseite (Authentic-Theme) öffnen.
- In der Datei `app.component.html` in dem `lux-app-header-ac`-Tag die Attribute "luxHideAppLogo" und "luxHideBrandLogo" ergänzen:
  ```html
  <lux-app-header-ac
    [luxHideBrandLogo]="true"
    [luxHideAppLogo]="true"
  ```
- Prüfen, ob das App- und Brandlogo ausgeblendet wurden.

**Comment by thodic77** [comment]
@patrowe: Bitte testen.

**Comment by patrowe** [comment]
Test wurde erfolgreich durchgeführt.
Geprüft wurde in den Browsern Google Chrome, Firefox und Edge unter Windows 10.
