### ISSUE TITLE
Hover-Effekt der LUX-Cards ohne luxCardActions im Theme-Authentic anpassen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#287]
Cards ohne luxCardAction sind klickbar und haben einen Hover-Effekt. 
Der Standard-Wert passt nicht und muss angepasst werden.

![image](https://user-images.githubusercontent.com/49644099/223413704-df1c89c9-0b90-4fe6-8b47-a8fdd6b89f8e.png)

**Comment by patrowe** [comment]
Die Änderungen wurden umgesetzt.

Für den Test:

- Den Zweig im lux-components-theme auschecken, lokal die Themes bauen und mit den lux-components verlinken.
- Das Demo für die Card öffnen
- Unter Konfiguration -> Erweitert den eintrag "luxCardActions anzeigen" deaktivieren
![image](https://user-images.githubusercontent.com/49644099/223425878-84649e91-b8e1-43ee-bf26-be5f95b63b75.png)

Mit der Maus über die Demo-Card hovern, es soll folgender Effekt erscheinen.
![image](https://user-images.githubusercontent.com/49644099/223426133-fa4c4bd9-a620-4ef3-91ef-7d90681194ae.png)

**Comment by patrowe** [comment]
@thodic77 bitte Testen.

**Comment by thodic77** [comment]
Test erfolgreich durchgeführt.
