### ISSUE TITLE
Immer dialogClosed-Event auslösen, wenn Dialog geschlossen wird

### ISSUE THREAD

**Issue by BenLad17** [IHK-GfI/lux-components#293]
Wenn ein Dialog mit `disableClose = false` geöffnet wurde und durch einen Klick außerhalb des Dialogs geschlossen wird, dann wird dadurch kein Event ausgelöst. Es soll auch in diesem Fall möglich sein, über den geschlossenen Dialog durch ein Event informiert zu werden. Es soll eine verlässliche Methode geben, um in jedem Fall informiert zu werden, wenn der Dialog geschlossen wurde.

Lösungsidee:
Das Event `backdropClick` auswerten und `dialogClosed` auslösen, falls `disableClose = false` ist.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt.

### Test

- Die Demo-Seite "Dialog" öffnen. 
- Das Toggle "Output-Events loggen" aktivieren.
- Das Toggle "dialogClosed" deaktivieren. 
- Den Button "ÖFFNEN [PRESET]" drücken.
- Außerhalb des Dialogs in den grauen Bereich klicken.
- Prüfen, ob in der Debug-Console (F12 Chrome) "dialogClosed" steht. 
- Den Test mit dem Button "ÖFFNEN [EIGENE KOMPONENTE]" wiederholen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK

Beim "Öffnen (eigene components)" erhalte ich in allen Umgebungen folgende Meldung:
![image](https://user-images.githubusercontent.com/75263741/228220726-6597ee04-1858-4ab6-a3d1-74f44b1c0ac9.png)
