### ISSUE TITLE
Neue Komponente lux-checkbox-container

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#297]
In manchen Anwendungen gibt es Formulare mit einer Reihe von Checkboxen. Diese sollen dichter angeordnet werden können, ähnlich zu einer Radiogroup.
Der Container soll automatisch das Padding zwischen den Checkboxen verringern, die Boxen in einer Spalte oder Zeile anzeigen. Optional kann dem Container ein übergeordneter Titel gegeben werden.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
Test

1. Die jeweiligen Zeige für die Components und das Theme auschecken.
2. Das Theme lokal bauen und mit den Components lokal verknüpfen.
3. Das Demo starten, auf Theme-Authentic wechseln und die Seite für den Checkbox-Container-Ac öffnen.
4. Im Feld luxLabel den Eintrag löschen, das Label in der Testkomponente soll ausgeblendet werden und der gesamte Container "rutscht" nach oben. Mit einem neuen Eintrag erscheint das Label wieder und der Container geht an die ursprüngliche Position zurück.
![image](https://user-images.githubusercontent.com/49644099/229488166-6ae17eca-1ad8-4f62-ba86-08cc0915b490.png)
5. Bei der Property luxVertical den Schieber nach links bewegen. Die Checkboxen im Container sollen in einer Reihe (bei kleinem Browserfenster auch in mehreren) angezeigt werden.
![image](https://user-images.githubusercontent.com/49644099/229488652-263bcb39-aeb8-47a5-a7c1-815685d73c5e.png)

**Comment by patrowe** [comment]
@DSeifer Bitte Testen!

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
