### ISSUE TITLE
Lux-Icons sind am Rand angeschnitten

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#298]
Einige Lux-Icons liegen nicht komplett im Viewport und sind am Rand angeschnitten.
Z.B. lux-bulk, lux-interface-text-formatting-list-bullets

![image](https://user-images.githubusercontent.com/49644099/228820380-da55ad2a-e94b-4701-b749-d1d2d4c45d19.png)
![image](https://user-images.githubusercontent.com/49644099/228820295-f2969459-46d1-4b15-9efe-13b896ec5b05.png)

Diese Icons müssen überarbeitet werden.

**Comment by thodic77** [comment]
Erfolgreich getestet.
