### ISSUE TITLE
lux-stepper-large - Gleiche Ids für die Nav-Item-Labels

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#299]
### Fehler

Aktuell werden gleiche Ids für die Nav-Item-Labels generiert. 

![Bug](https://user-images.githubusercontent.com/32597554/229051477-b06a78f7-b9a8-4495-b034-dd7ffb24fbf8.png)

### Akzeptanzkriterien

- Es werden unterschiedliche Ids für die Nav-Item-Labels genieriert

**Comment by thodic77** [comment]
### Test

- Die Demoseite "Stepper-Large" öffnen. 
- Vier Schritte weiter gehen. 
- Im Browser-Quellcode nach "lux-stepper-large-nav-item-label-link" suchen. (F12 Chrome)
- Prüfen, ob sich die Ids unterscheiden. 

![Fixed](https://user-images.githubusercontent.com/32597554/229055251-d40d3603-c6f3-4174-a747-7c48ae3fc661.png)

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

 @DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> Ich bin leider nicht an den Seitenquellcode gekommen. Da müsste ich ggf. nochmal mit @patrowe schauen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2.1 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK

ABER:
@patrowe  hat beim Test festgestellt, dass die ID im responsive design nicht korrekt gesetzt wird.

**Comment by DSeifer** [comment]
Rückmeldung von @thodic77: In der mobilen Fassung ist die ID nicht nötig, da es dort "echte" Links sind, die direkt annavigiert werden können. Daher ist der Test nur für die Desktop-Variante nötig.
