### ISSUE TITLE
LUX-Components auf Angular 15 aktualisieren

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#302]
Im Rahmen dieses Issues sollen die LUX-Components von Angular v14 auf v15 aktualisiert werden.

**Comment by thodic77** [comment]
Angular wurde auf 15 angehoben und die LUX-Components (inklusive Demo) wurden angepasst. 

@DSeifer: Bitte testen, dass alles noch funktioniert wie die 14er-Version.

**Comment by DSeifer** [comment]
Es sind bisher nur zwei Kleinigkeiten aufgefallen.

[Testbericht LUX-Components V15.pdf](https://github.com/IHK-GfI/lux-components/files/11296511/Testbericht.LUX-Components.V15.pdf)

**Comment by thodic77** [comment]
> Es sind bisher nur zwei Kleinigkeiten aufgefallen.
> 
> [Testbericht LUX-Components V15.pdf](https://github.com/IHK-GfI/lux-components/files/11296511/Testbericht.LUX-Components.V15.pdf)

Die Fehler wurden korrigiert.
@DSeifer: Bitte nachtesten.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 (a) mit den jeweils aktuellen Browserversionen getestet:
- Das mit dem Button beim Datetimepicker ist sowohl unter Windows als auch unter MacOS in allen getesteten Browsern **OK**
- Im Theme-Green wird das Kalender-Icon bei beiden Komponenten unter beiden OS und in allen Browsern noch immer fehlerhaft angezeigt **ERR** -> @patrowe

**Comment by patrowe** [comment]
Die Icons wurden auch im Green-Theme angepasst.
@DSeifer Bitte nachtesten.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 (a) mit den jeweils aktuellen Browserversionen getestet:

Das zuletzt Im Theme-Green aufgetauchte UI-Problem ist behoben. 

Nichtsdestotrotz denke ich, dass ich da nochmal komplett durchgehen sollte. Daher die Frage worauf das Hauptaugenmerk zu legen ist. M.E. sollte es durch die Umstellung eigentlich keine funktionalen Änderungen, bzw. Probleme geben. Heißt, ich würde mir nochmal alle Komponenten unter UI-Gesichtspunkten in beiden Themes ansehen. OK?

**Comment by DSeifer** [comment]
Testdokument:
[Test Issue #302 (authentic-green).docx](https://github.com/IHK-GfI/lux-components/files/11464588/Test.Issue.302.authentic-green.docx)

**Comment by thodic77** [comment]
> Testdokument: [Test Issue #302 (authentic-green).docx](https://github.com/IHK-GfI/lux-components/files/11464588/Test.Issue.302.authentic-green.docx)

Die Fehler wurden behoben. 
@DSeifer: Bitte nachtesten.

**Comment by DSeifer** [comment]
Das Leeren des Browser-Cache löst das Problem der nicht vertikalen Zentrierung im Theme green. Da das Umschalten des Theme im echten Leben nicht vorkommt, wird der Issue geschlossen.
