### ISSUE TITLE
lux-table - Feststehender Header hat einen transparenten Hintergrund

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#303]
Wenn innerhalb einer Tabelle mit feststehendem Header gescrollt wird, dann sieht der Header fehlerhaft aus. 

Screenshot: 
![image](https://user-images.githubusercontent.com/32597554/229998391-05e93a6c-7d27-43ed-b252-b2078e3f5f24.png)

### Akzeptanzkriterien

- Der Header grenzt sich beim Scrollen wieder eindeutig vom Inhalt ab.

**Comment by patrowe** [comment]
Der Fehler wurde behoben.

**Comment by patrowe** [comment]
**Test:**

1. Das Demoprogramm starten und die Seite für die Table öffnen.
2. Unter Erweitert "Höhe festlegen" auswählen und den Wert auf 300 setzen.
<img width="524" alt="Bildschirmfoto 2023-04-20 um 13 53 03" src="https://user-images.githubusercontent.com/49644099/233360627-d4bef135-4341-4de5-8465-fe7227dd2173.png">
3. Mit der Maus über das Tabellen-Beispiel hovern und nach oben und unten scrollen.

**Erwartetes Ergebnis:**

Die Tabellen-Zeilen  scrollen unter den Tabellen-Header und der Hintergrund des Headers ist weiß.
<img width="572" alt="Bildschirmfoto 2023-04-20 um 13 53 19" src="https://user-images.githubusercontent.com/49644099/233360619-7263b280-af6d-4f75-8923-3fb4933ce3d2.png">

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
