### ISSUE TITLE
Layout-Form-Row: Buttons sollen mit AC-Komponenten zentriert werden

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#304]
Werden Buttons in der Lux-Layout-Form-Row zusammen mit den AC-Formularelementen kombiniert, werden diese nicht mehr zentriert. 
Dieses soll gefixt werden.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/49644099/230316363-362b769c-e276-4830-82b9-c25211031871.png)

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.

**Für den Test:** 
1. Demoprogramm starten und die Seite für die Form-Row-Komponente öffnen.
2. Bis zur Karte "Formular mit Buttons in der Form-Row" scrollen. Die Buttons in der Row sollen mit dem Input-Container zentriert sein. (In allen vier Input-Versionen Standard, ohne Top- und Bottom-Label, ohne Top-Label und ohne Bottom-Label.)
<img width="928" alt="Bildschirmfoto 2023-04-20 um 09 36 11" src="https://user-images.githubusercontent.com/49644099/233297728-0eb03610-e5c1-48f9-b47e-acdf5e37984f.png">

<img width="934" alt="Bildschirmfoto 2023-04-20 um 09 36 28" src="https://user-images.githubusercontent.com/49644099/233297368-70c7b313-4f93-4b0f-ab05-92b193652998.png">

3. In der Entwickler-Konsole auf Responsive-Dartstellung umschalten. In der mobilen Darstellung wird die Anzeige 1-spaltig, die Buttons bleiben in einer Zeile neben dem Input.
<img width="580" alt="Bildschirmfoto 2023-04-20 um 09 41 21" src="https://user-images.githubusercontent.com/49644099/233298015-3e7085a6-c05d-410d-a411-717a083bbdcb.png">

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
