### ISSUE TITLE
Badge-Notififaction für "lux-app-header-ac-nav-menu-item"

### ISSUE THREAD

**Issue by JBeckerSN** [IHK-GfI/lux-components#305]
Die Möglichkeit, eine Badge-Notification an ein Header-Menu-Item zu hängen, wäre eine schöne Erweiterung. 
So könnte man z.B. mit einem Menü-Eintrag "Aufgaben" direkt signalisieren, dass Aufgaben zur Erledigung anstehen.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.

**Comment by patrowe** [comment]
**Test der neuen Properties:**

**Vorbedingungen:**
Die entsprechenden Zweige für die Lux-Components und das Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo-Programm starten.

**Test für Lux-Button:**
1. Die Testseite für lux-button öffnen

2. Bei "luxButtonBadge" einen Text eingeben
![Screenshot 2023-06-13 101137](https://github.com/IHK-GfI/lux-components/assets/49644099/322286be-8015-4f9c-bd85-e1925179d28e)
Zu erwartendes Ergebnis:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/79435d00-d3b2-4bb7-8b22-246a64f1ca32)

3. Den Text schrittweise erweitern und prüfen, ob der Text bis zu vier Zeichen vollständig angezeigt wird. Z.B. +9, +99, +999
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/dcba0593-d2cf-4c23-ab8d-bb5908220eae)

4. Den Text +9999 (fünf Zeichen) eingeben. Zu erwartendes Ergebnis:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/d4b13d49-7bc6-4fc5-954d-ee6de3cc9e50)

5. Die Property luxIconShowRight auswählen und einen BadgeText eingeben. Zu erwartendes Ergebnis:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/84c1e17f-ac81-4cb1-acbd-2abecae0b757)

6. Die Property luxDisabled auf "true" setzen und einen Badgetext eingeben. Zu erwartendes Ergebnis: Die Badge wird ausgeblendet.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/d8d1cfa2-2206-4624-b20f-cdbc9c1d7949)

7. Die BadgeColors testen. Dazu das Dropdown für luxButtonBadgeColor öffnen und die Optionen einzeln durch prüfen. Zu erwartendes Ergebnis: "primary" -> dunkelblaue Badge, "accent" -> grüne Badge, "warn" -> rote Badge.

**Test für das Lux-Menu:**
1. Die Testseite für lux-menu öffnen und unter Konfiguration > Erweitert das Panel für "Menu-Item #0" öffnen. 
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/3fa4e6d5-5320-43be-bfab-efded89e205d)

2. Unten im Panel bei der Property luxButtonBadge die Schritte 2-4 für den Button (s.o.) wieder holen. Zu erwartendes Ergebnis:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/61d67d13-c9af-4575-86a4-0ce908ba2bcc)

3. Testen der Badge im Panel: Unter Konfiguration > Allgemein den Schalter für "luxDisplayExtended" auf false setzen:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/6980e625-f112-4823-8d67-fc06ffde6645)
Und wie unter zwei beschrieben vorgehen.  Das Menu-Panel öffnen und Ergebnis prüfen:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/a7e4a953-04e6-4ded-ba4c-505d981d2889)
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/9bbae088-afeb-44f5-8204-18cd4a9db287)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.1288) und MacOS 13.4 mit den jeweils aktuellen Browserversionen getestet:

### Windows: Edge, Firefox, Chrome
- Eingabe von 4 Ziffern = OK
- Eingabe von "+" zzgl. 3 Ziffern = OK
- Eingabe von "WWWW" führt zur Anzeige: "W..." = **ERR?**
- Eingabe von "+9999" führt zu "+9..." = OK
- luxIconShowRight gesetzt = OK
- luxDisabled gesetzt. Ist luxButtonBadge leer, ist der Button größer und geräumiger als wenn luxButtonBadge einen Inhalt hat. = **ERR?**
- Bei lux-Menu wird bei MenuItem #3 (extralanges Beispiellabel) bereits ein Badge in "rot" angezeigt. Woher kommt die Farbe? = **ERR?**
- Test des Badge im Panel: Aus "+999" beim extralangen Beispiellabel wird "-..." = **ERR**

### MacOS: Safari, Chrome, Firefox
- Eingabe von 4 Ziffern = OK
- Eingabe von "+" zzgl. 3 Ziffern = OK
- Eingabe von "WWWW" führt zur Anzeige: "W..." = **ERR?**
- Eingabe von "+9999" führt zu "+9..." = OK
- luxIconShowRight gesetzt = OK
- luxDisabled gesetzt. Ist luxButtonBadge leer, ist der Button größer und geräumiger als wenn luxButtonBadge einen Inhalt hat. = **ERR?**
- Bei lux-Menu wird bei MenuItem #3 (extralanges Beispiellabel) bereits ein Badge in "rot" angezeigt. Woher kommt die Farbe? = **ERR?**
- Test des Badge im Panel: Aus "+999" beim extralangen Beispiellabel wird "-..." = **ERR**

**Comment by patrowe** [comment]
_Nachträglicher Fix:_ im Menu-Panel dürfen die Batches nicht angezeigt werden, wenn ein Menu-Item disabled ist. Gleichzeitig solleln das Label und das Icon des deaktivierten Menu-Items in Grau angezeigt werden.

@DSeifer, bitte nachtesten:


1. Die Seite für Lux-menu öffnen.
2. Unter Konfiguration: Lux-Menu-Extendet auf "false" setzten
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/4df7d8da-e497-4f24-ae53-d3b87533717a)
3. Unter "Erweitert" für "MenuItem #0" den Wert "luxDisabled" auf "true" setzen und für die Buttonbadge einen Eintrag machen
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/8427ed9a-054a-4684-8515-24df5669cddf)
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/ebac881d-f24c-4321-ba4b-12975a95a3fd)
4. Das Menu-Panel im obersten Beispiel öffnen. 


**Zu Erwartendes Ergebnis:**

- Der erste Eintrag im Panel ist ausgegraut und nicht klickkbar. 
- Es wird bei dem ersten Eintrag im Panel keine Badge hinter dem Label angezeigt.

![image](https://github.com/IHK-GfI/lux-components/assets/49644099/20c47fa6-9c06-4100-b07b-641a1f4c817f)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3086) und MacOS 13.4.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
