### ISSUE TITLE
Unerwünschte Consolenausgabe von lux-app-header-nav-menu entfernen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#306]
Ist das Nav-Menu eingeklappt, liefert das öffnen über den Trigger-Button unerwünschte Consolen-Ausgaben.
Diese sollen entfernt werden.

![image](https://user-images.githubusercontent.com/32597554/233557718-7c5841fa-c5bd-494b-afe0-6c47ece94b30.png)

**Comment by thodic77** [comment]
Die Konsolenausgaben wurden entfernt.

### Test

- Eine beliebige Seite in der Demo öffnen.
- Das Browserfenster so verkleinern, dass das die Navigationspunkte ins Menü verschoben werden.
- Das Menü öffnen und wieder schließen. 
- In der Debug-Console (F12 Chrome) prüfen, dass keine Ausgabe mit "navmenu..." vorhanden ist.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
