### ISSUE TITLE
No flat button style in lux-link

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#307]
Aktuell gibt es keine Möglichkeit lux-link Buttons im Flat Style zu erzeugen.
Das Property luxFlat wird in lux-link aktuell nicht ausgewertet.
Wäre es möglich dies zu korrigieren, damit auch lux-link's im Flat Style möglich sind?

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

### Test

- Die Demoseite "Link" öffnen.
- Das Toggle "luxFlat" aktivieren.
- Prüfen, ob der Link flach und ohne Schatten dargestellt wird.
- Das Toggle "luxRaised" aktivieren.
- Prüfen, ob der Link erhöht und mit Schatten dargestellt wird.

@DSeifer: Bitte testen.
