### ISSUE TITLE
LUX-Http-Error - Zeigt keine Fehler mehr an

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#309]
Aktuell zeigt der LUX-Http-Error keine Fehler mehr an. 

### Test

- Die Demoseite "HTTP-Error" öffnen.
- Einen der Buttons "Als Map", "Als String-Array" oder "Als Objekte" anklicken.
- Prüfen, ob die entsprechenden Fehlermeldungen angezeigt werden. 

![image](https://user-images.githubusercontent.com/32597554/231741132-7ddb16d0-7e58-460f-ac83-03c4d5364ed6.png)

### Akzeptanzkriterien

- Die HTTP-Fehler werden wieder angezeigt. 

![image](https://user-images.githubusercontent.com/32597554/231740801-214b6080-644d-4eb2-a634-99d5994720d4.png)

**Comment by thodic77** [comment]
Das Problem liegt an den neuen SVG-Icons. Der LUX-Http-Error zeigt die Fehler an, bis der nächste Request ohne Fehlerstatuscode 400 durchgeführt wurde. Die Fehlermeldungen haben SVG-Icons (z.B. Bug siehe Screenshot). Die SVG-Icons werden auch via Requests geladen. Diese gehen ohne Fehlerstatuscode 400 durch und sorgen dafür, dass die vorherigen Fehler wieder ausgeblendet werden. Die Assets-Requests wurden jetzt ausgenommen, so dass die Fehlermeldungen wieder korrekt angezeigt werden, bis der nächste echte Request durchgegangen ist.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.2.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
