### ISSUE TITLE
Lange Labels im Menu-Panel werden abgeschnitten.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#312]
Lange Labels werden im Menu-Panel  abgeschnitten. 
<img width="327" alt="Bildschirmfoto 2023-04-20 um 10 04 28" src="https://user-images.githubusercontent.com/49644099/233302045-575dc2ac-6955-4dba-baf4-1e05915ca987.png">

Dieses soll geändert werden. Die Labels sollen automatisch gekürzt und mit "..." diese Kürzung angezeigt werden.

**Comment by patrowe** [comment]
**Test**

_Vorbedingung:_

1. Die entsprechende Zweige für die Lux-Components und das Lux-Components-Theme auschecken.
2. Das Theme lokal bauen und mit den Components lokal verlinken.
3. Das Demo starten und die Seite für das Lux-Menu öffnen.

_Durchführung:_

1. Die Property "luxDisplayExtended" auf false setzen
<img width="526" alt="Bildschirmfoto 2023-04-24 um 11 19 03" src="https://user-images.githubusercontent.com/49644099/233955310-01d3970a-d51c-4797-a8bb-7921c00879fc.png">

2. Mit dem Icon das Menu-Panel öffnen

_Zu erwartendes Ergebnis:_
<img width="323" alt="Bildschirmfoto 2023-04-24 um 11 20 20" src="https://user-images.githubusercontent.com/49644099/233955353-062d417f-a0ef-4218-9f55-774f92af786f.png">

Das Label des unteren Eintrags wird gekürzt und "..." am Ende angehängt.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
