### ISSUE TITLE
Blue-Theme und alle dazugehörenden Komponenten entfernen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#316]
Im Rahmen dieses Issues soll das Blue-Theme und alle dazugehörenden Komponenten entfernt werden.

### Akzeptanzkriterien

- Das Blue-Theme wurde entfernt.
- Die dazugehörigen Komponenten wurden entfernt.
- Die dazugehörigen Demoseiten wurden entfernt.

**Comment by thodic77** [comment]
Die Anforderungen wurden umgesetzt.

@patrowe: Bitte testen und Code-Review durchführen.

**Comment by patrowe** [comment]
Weitere nicht mehr benötigte Regeln und Theme-Variablen wurden aus lux-components-theme entfernt.
@thodic77 Bitte erneut die Formcontrols in beiden Themes testen.

**Comment by thodic77** [comment]
Bei den Tests wurden folgende Punkte entdeckt: 

- Das Datepicker-/Datetimepicker-Icon wird nicht disabled dargestellt.
- Höhenunterschied bei den Suffixen beim Input (green-Theme)
- Baseline - Fehler anzeigen, dann wird der Rahmen links abgeschnitten (green-Theme)

**Comment by patrowe** [comment]
Folgende Fehler wurden gefixt:

- Das Datepicker-/Datetimepicker-Icon wird nicht disabled dargestellt. -> Änderungen im Lux-Components-Theme durchgeführt
- Baseline - Fehler anzeigen, dann wird der Rahmen links abgeschnitten (green-Theme) -> Änderungen in den Lux-Components durchgeführt

Der Fehler "Höhenunterschied bei den Suffixen beim Input (green-Theme)" konnte nicht nachgestellt werden.

**Comment by thodic77** [comment]
Die beiden oberen Fehler wurden erfolgreich nachgetestet. 

> Der Fehler "Höhenunterschied bei den Suffixen beim Input (green-Theme)" konnte nicht nachgestellt werden.

Dieser Fehler wurde im Zuge der Umstellung von den Matieral- und FA-Icons auf die LUX-Icons behoben (Issue #322).
