### ISSUE TITLE
lux-file-list Dateien mit demselben Dateinamen werden ungefragt ersetzt

### ISSUE THREAD

**Issue by StephanTh** [IHK-GfI/lux-components#318]
Wenn innerhalb von lux-file-list bereits eine Datei mit zum Beispiel den Dateinamen "Test1.pdf" existiert und eine weitere Datei mit demselben Dateinamen "Test1.pdf" hochgeladen wird, so wird die erste Datei ungefragt überschrieben/ersetzt.

Als Entwickler möchte ich, dass optional die Möglichkeit existiert, eine oder mehrere Dateien mit demselben Dateinamen zuzulassen ohne das ein ungefragtes Überschreiben stattfindet

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 (a) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
