### ISSUE TITLE
lux-file-list Einzelne Action wird im Contextmenü angezeigt

### ISSUE THREAD

**Issue by StephanTh** [IHK-GfI/lux-components#320]
<img width="890" alt="lux-file-list" src="https://user-images.githubusercontent.com/28092121/236180108-3a53c2f9-dce1-4b35-acf5-2e710a10ea69.PNG">

Die lux-file-list enthält nur eine Action (ViewAction), die anderen Actions sind deaktiviert, und trotzdem wird die Aktion hinter einem Menü versteckt und sorgt somit für einen unnötigen Klick, um zu der Aktion zu gelangen.

`<lux-file-list luxLabel="Zugehörige Papierantragsdateien"
               [luxSelected]="papierantragsdateien" [luxContentsAsBlob]="true"
               [luxMaxSizeMB]="10" [luxMultiple]="true"
               [luxDownloadActionConfig]="disabledConfig" [luxUploadActionConfig]="disabledConfig"
               [luxViewActionConfig]="viewActionConfig" [luxDeleteActionConfig]="disabledConfig" [luxDisabled]="isPapierantrageInformationenLoading" #luxFileListComponent>
</lux-file-list>
`

`
disabledConfig: ILuxFileListActionConfig = {
    disabled      : true,
    disabledHeader: true,
    hidden        : true,
    hiddenHeader  : true,
    iconName      : '',
    iconNameHeader: '',
    label         : '',
    labelHeader   : ''
  };

  // Die Konfiguration für die Action, die den Callback aufruft und in einem neuen Fenster öffnet
  viewActionConfig: ILuxFileActionConfig = {
    disabled: false,
    hidden  : false,
    iconName: 'lux-interface-edit-view',
    label   : 'Anzeigen',
    onClick : $event => {
      const file = {
        name   : $event.name,
        type   : $event.type,
        content: $event.content
      }

      this.filePreviewService.open({
        previewData: {
          fileComponent: this.luxFileInputComponent,
          fileObject   : file
        }
      });
    }
  };
`

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

### Test

- Die Demoseite "lux-file-list" öffnen.
- Das Browserfenster vergrößern und verkleinern.
- Prüfen, ob die korrekte Anzahl von Menüitems zu sehen sind.
- Den Test für die "lux-file-input"-Komponente wiederholen. 
- Bitte auch mit allen Themes testen, da die Menüitembreite vom Theme abhängt.

![Error](https://github.com/IHK-GfI/lux-components/assets/32597554/861c0b03-0493-43fb-8206-5ee4b215b034)

![Ok](https://github.com/IHK-GfI/lux-components/assets/32597554/0238cb45-3e26-4d37-a738-261143aeb1cb)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 (a) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
