### ISSUE TITLE
Material- und FA-Icons entfernen und durch LUX-Icons ersetzen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#322]
Mit der v15 werden nur noch die lux-icons unterstützt. Daher sollendie Abhängigkeiten von Fontawesome und den Material-Icons entfernt.

**Aktzeptanzkriterien:**
- die Abhängikeiten in der Komponente lux-icon sind entfernt
- bei dem Einsetzen eines ungültigen Iconnames soll eine Fehleranzeige auf der Console erscheinen
- die Components und die Demo dürfen keine ungültigen Icons enthalten.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2965) und MacOS 13.4 mit den jeweils aktuellen Browserversionen und den Themes Green und Authentic getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> OK
