### ISSUE TITLE
Die Property luxIconsize soll flexibler werden

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#323]
Die Iconsize kann bisher nur die Werte 1x, 2x, ...5x annehmen. Dieses erschwert eine flexible Gestaltung der Icons.
Mit den neuen Icons und der Version 15 soll diese Propety überarbeitet werden. 

Akzeptanzkreterium:
- die Property luxIconsize soll px- und em-Werte annehmen

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt und Iconsize bei folgenden Komponenten entsprechend überarbeitet:
lux-button, lux-menu (menu-item, menu-trigger), lux-tile-ac, lux-input-ac-prefix/-suffix, lux-file-input, lux-file-list, lux-file-upoad, lux-app-header, lux-app-footer, lux-tab.

**Comment by patrowe** [comment]
**Test:**

**Vorbedingungen:**
- Jeweils den Branch "Issue_323-luxIconSize_more_flexible" für die LUX-Components und das LUX-Components-Theme herunterladen
- Das Theme lokal bauen und mit den Components lokal verlinken
- Das Demo-Programm starten.
- Die folgenden Tests (bis auf die Header) jeweils für das Theme Authentic und das Theme Green durchführen 

**Test 1: lux-icon**
- Die Demoseite für die Komponente öffnen
- Die einzelnen Werte für die Property "luxIconSize" durchtesten und die Anzeige der Icons vergleichen.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/38df907d-693c-45a2-bef2-ca0864116ad2)
![Screenshot 2023-07-06 095606](https://github.com/IHK-GfI/lux-components/assets/49644099/215ff97c-64ba-4cad-9f91-2879aac51e1a)

**Test 2: lux-button**
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die Icons und der Labeltext vertikal zentriert angezeigt werden
![Screenshot 2023-07-06 091008](https://github.com/IHK-GfI/lux-components/assets/49644099/dd9f6d44-4e01-4cbf-babf-c96aecdf25a1)

**Test 3: lux-menu**
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die Icons und Labels im Menu zusammen mit dem Trigger-Button vertikal zentriert ausgerichtet sind.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/627700dd-1df2-41db-83af-d091130d9c2c)
- Die Property luxMenuExtended auf false setzen und des Dropdown-Panel über den Trigger-Button öffnen. Prüfen, dass die Icons und die Labels ausgerichtet angezeigt werden.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/da81f61e-48c0-4879-aab4-bdb5b8b9538d)

**Test 4: lux-tile-ac**
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die Icons in der Kachel oben rechts in der Ecke ausgerichtet sind.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/29467126-a6d6-43b2-a78f-275b6db24f6c)

**Test 5: lux-input-ac-suffix/prefix**
- Im Demo die Kategorie "Formulare" öffnen, im ersten Reiter "Authentic" das Formular-Feld "Spende" zeigt sowohl im Prefix als auch im Suffix ein Icon an. Prüfen, dass die Icons vertikal zentriert im Textfeld ausgerichtet sind.
- Zur Überprüfung das Textfeld komplett mit Ziffern füllen und die Ausrichtung der Eingabe und der Icons kontrollieren
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/fadf7aea-5e45-4c3f-add3-dbb190d91f0d)

**Test 6: lux-file-input**:
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die Icon(-buttons) im Input vertikal zentriert sind
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/7caa1f61-2664-4886-bd56-d22b23a8146a)

**Test 7: lux-file-list**:
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die Icons in der Titelzeile und bei den jeweiligen Listen-Elementen, zentriert ausgerichtet sind
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/3ffb32ae-5fa7-44c9-9b1d-d80bea30ca97)

**Test 8: lux-file-upload**:
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die Icons korrekt angezeigt werden
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/7f67bc9d-d985-451a-bcab-069f960cb063)

**Test 9: lux-app-footer**:
- Eine beliebige Demoseite öffnen
- Den Footer der Anwendung betrachten und prüfen, dass die Buttons und Link im Footer vertikal zentriert ausgerichtet sind
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/2f78d5f7-befc-4a1b-9396-a27c811b1c5e)

**Test 10: lux-tabs**:
- Die Demoseite für die Tabs öffnen
- Das Dropdown bei LuxIconSize öffnen und die einzelnen Werte durchgehen, dabei die Anzeige der Icons in den Tabs überprüfen.
![Screenshot 2023-07-06 094639](https://github.com/IHK-GfI/lux-components/assets/49644099/ea475c14-b3d5-4c2a-980b-059af2e6e013)

**Test 11: lux-app-header-ac**
- Nur für das Theme Authentic
- Eine beliebige Seite in der Demo öffnen
- Prüfen, dass die Buttons im Header vertical zentriert ausgerichte sind.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/248f2f85-96c1-47d2-b8d2-5a4ce794a81b)

**Test 12: lux-app-header**
- Nur für das Theme Green
- Eine beliebige Seite in der Demo öffnen
-  Prüfen, dass die Buttons im Header vertical zentriert ausgerichte sind.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/8736eb5b-7388-48d5-8071-e18a2d314185)

**Test 13: lux-card**
- Die Demoseite für die Komponente öffnen
- Prüfen, dass die beiden Icons im Header der Card mit dem Titel ausgerichtet sind.
![Screenshot 2023-07-06 100529](https://github.com/IHK-GfI/lux-components/assets/49644099/8996ad2b-0b98-4461-82d3-ba52b85f9093)

**Comment by patrowe** [comment]
@DSeifer Bitte Testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3086) und MacOS 13.4.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS: Safari -> OK
Windows: Edge -> OK
