### ISSUE TITLE
Festlegung des Fokus auf einen Button im Standarddialog

### ISSUE THREAD

**Issue by DSeifer** [IHK-GfI/lux-components#325]
**Komponente: lux-dialog**

Zwecks der Verbesserung der Tastaturbedienbarkeit des Standarddialogs, soll dieser um die Möglichkeit erweitert werden, einem Button konfigurativ den Fokus zu geben.

**Comment by thodic77** [comment]
In der Dialogkonfiguration wurde die Property "defaultButton" (undefinded, 'confirm' oder 'decline') eingeführt. 

### Test

- Die Demoseite "Dialog" öffnen.
- Das Toggle "Output-Events aktivieren" einschalten.

Wert "unset"

- Den Radiobutton "defaultButton" auf "unset" setzen.
- Den Dialog über den Button "Öffnen Preset" öffnen.
- Die Debug-Console (F12 Chrome) öffnen.
- Die Enter-Taste drücken.
- Prüfen, dass der Dialog geöffnet bleibt, da keine Standardaction gesetzt wurde.
- Prüfen, dass keine Ausgabe in der Debug-Console erscheint.
- Den Dialog über einen beliebigen Button schließen.

Wert "confirm"

- Den Radiobutton "defaultButton" auf "confirm" setzen.
- Den Dialog über den Button "Öffnen Preset" öffnen.
- Die Debug-Console (F12 Chrome) öffnen.
- Die Enter-Taste drücken.
- Prüfen, dass der Dialog geschlossen wurde.
- Prüfen, dass die Ausgabe "dialogConfirmed " in der Debug-Console erscheint.

Wert "decline"

- Den Radiobutton "defaultButton" auf "decline" setzen.
- Den Dialog über den Button "Öffnen Preset" öffnen.
- Die Debug-Console (F12 Chrome) öffnen.
- Die Enter-Taste drücken.
- Prüfen, dass der Dialog geschlossen wurde.
- Prüfen, dass die Ausgabe "dialogDeclined" in der Debug-Console erscheint.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 (a) mit den jeweils aktuellen Browserversionen getestet:

Windows: Edge, Firefox, Chrome -> OK
MacOS: Safari, Firefox, Chrome -> OK
