### ISSUE TITLE
lux-dialog: ESC-Taste löst kein dialogClosed-Event aus

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#328]
Wenn ein Dialog (`disableClose=false`) über die ESC-Taste geschlossen wird, wird kein `dialogClosed`-Event ausgelöst.

### Akzeptanzkritieren

- Wenn ein Dialog (`disableClose=false`) über die ESC-Taste geschlossen wird, wird ein `dialogClosed`-Event ausgelöst.

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

### Test

- Die Demoseite "Dialog" öffnen.
- Die Debug-Console (F12 Chrome) öffnen.
- Das Toggle "Output-Events aktivieren" einschalten.
- Das Toggle "disableClose" ausschalten.
- Den Dialog über den Button "Öffnen [Preset]" öffnen.
- Den Dialog über die ESC-Taste schließen.
- Prüfen, ob der Dialog geschlossen wurde.
- Prüfen, ob in der Debug-Console der Wert "dialogClosed" geloggt wurde.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.3.1 (a) mit den jeweils aktuellen Browserversionen getestet:

Windows: Edge, Firefox, Chrome -> OK
MacOS: Safari, Firefox, Chrome -> OK
