### ISSUE TITLE
Material-Icons im Stepper austauschen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#331]
Der Stepper nutzt im Standard Material-Icons. Diese stehen nach dem Entfernen der Mat-Icons nicht mehr zur Verfügung und müssen gegen die Neuen Lux-Icons ersetzt werden.

![image](https://github.com/IHK-GfI/lux-components/assets/49644099/73e52528-4ffb-41e8-8e5f-8da1429ed324)

Akzeptanzkriterium:
Für den Standard werden passende lux-icons gesetzt.
Die Wahl von Custom-Icons bleibt weiterhin möglich.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
Bitte Testen!

**Test-Vorbereitung:**
-Den Branch ausschecken und das Demo für die Components starten.
-Die Seite für den Lux-Stepper öffnen

**Test-Durchführung:**
**A: Default-Icons**
 - die Steps in der Demo-Anwenung durchführen und den Wechsel der Icons im "Step-Header" vergleichen
 Zu erwartendes Ergebnis:
Startzustand:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/c356bb3e-449f-4984-a63d-519102439f76)
Endzustand:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/05835d56-bc1f-4342-86be-f77ff0778aea)

**B: Custom-Icons**
- die Property "luxCustomIcons" auswählen.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/bf42b3ca-7c7b-44d1-89aa-8f7d096008dd)

- die Steps in der Demo-Anwendung durchführen und den Wechsel der Icons im "Step-Header" vergleichen
Zu erwartendes Ergebnis:
Startzustand:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/5d70ddd8-fca7-4c06-8c84-9ddc6d174fdd)
Endzustand
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/64ee73a2-840f-4c63-a787-77564e7f6e56)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3324) und MacOS 13.4.1 (c) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari -> OK
Windows: Edge -> OK
