### ISSUE TITLE
Schriften werden im Theme-Authentic nicht korrekt angezeigt

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#334]
Bei einer Bildschirm-Skalierung von 100% werden die Schriften unter Windows nicht korrekt angezeigt.
Z.B. sind einige Buchstaben bei bei font-weight: 600 nicht deutlich gerendert.
![Screenshot 2023-06-19 152124](https://github.com/IHK-GfI/lux-components/assets/49644099/e6ced8ec-98a1-4d1d-9e16-035e1721163c)

Zudem wird das Label bei einem Input-Element bei den Unterlängen abgeschnitten (nur Firefox)
![Screenshot 2023-06-19 152332](https://github.com/IHK-GfI/lux-components/assets/49644099/cd1bcdda-b451-466c-9103-910d7a6dbbb1)

Dieses soll gefixt werden!

**Akzeptanzkriterium:**

Die Schriften Blogger Sans und Source Sans pro sind in den jeweiligen Schriftschnitten deutlich gezeichnet.
Die Labels der Formular-Elemente werden in allen Browsern vollständig angezeigt.

**Comment by patrowe** [comment]
Die beschriebenen Probleme wurden behoben.

Bitte Testen.

**Test:**

_Vorbedingungen:_

- Den  verlinkten Branch für das Projekt lux-components-icons-and-fonts auschecken.
- Für die Components den Zweig develop auschecken und die lux-components-icons-and-fonts lokal verlinken.
- Das Demo Programm starten.
- In den Systemsteinstellungen die Skalierung für die Anzeige auf 100% stellen.

_Test:_
- Die Kachel "Formulare" wählen und den Reiter "WebFonts" öffnen
- Prüfen, dass alle Schriftschnitte in der Übersicht korrekt angezeigt werden. Insbesondere die Punzen (innenliegende Weißräume) in den Buchstaben sind deutlich zu erkennen.
_Zu erwartendes Ergebnis:_
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/768e7f6c-4c62-4f07-9a6a-e2c0ade79db7)

- Die Anzeige in der Navbar testen. Das Label für die aktuell ausgewählte Seite im Demo wird korrekt angezeigt.
_Zu erwartendes Ergebnis:_
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/c0f0fb99-a132-4ef3-9cf0-f0164a5e57fa)

- Für das Label in den Formularelementen die Komponente lux-input-ac öffnen
- Für das Label den Text "Label gpqy" einsetzten. Prüfen, dass die Unterlängen der Buchstaben im Label vollständig angezeigt werden.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/fffc4637-b981-499e-8f89-e0e91644df7a)
_Zu erwartendes Ergebnis:_
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/f7e46a77-13e1-4c75-8a73-ecbd1c41d915)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3086) und MacOS 13.4.1 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome -> ERR
In der VM unter Windows 21H2 (19044.3086):

![Screenshot 2023-06-29 132833](https://github.com/IHK-GfI/lux-components/assets/75263741/8746c1c6-edeb-4653-884c-23f03fc78e4b)

Auf dem NB unter Windows 22H2 (19045.3086):
![image](https://github.com/IHK-GfI/lux-components/assets/75263741/82cbe88f-ec39-4dfa-ab91-4013e110752c)
