### ISSUE TITLE
lux-master-detail-ac startet in der Mobilen Ansicht initial im Detail sollte jedoch im Master starten

### ISSUE THREAD

**Issue by ToWeGfI** [IHK-GfI/lux-components#338]
Wenn ein IPhone User die Komponente aufruft, dann wird initial die Detailseite geladen. Es sollte allerdings zu erst die Masterliste angezeigt werden. 
Das Verhalten konnte auf echten Geräten reproduziert werden. Man kann dies aber auch simulieren in dem man im Browser die Auflösung vom Iphone13 einstellt z.B. im Firefox.

**Comment by patrowe** [comment]
Beide oben benannten Fehler für die Mobile Version des Master-Detail-AC müssen behoben werden.

Akzeptanzkriterium:
- Beim Initialen Laden des Master-Detail-Ac in der mobilen Ansicht wirde die Master-Liste angezeigt.
- Nach dem Wechsel zwischen Master-Liste und Detail darf sich der Status eines aufklappbaren Filters nicht verändert haben.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.

@DSeifer: Bitte Testen!

**Comment by patrowe** [comment]
**Test:**

**Vorbedingung:**

1. Die verlinkten Zweige für die Lux-Components und das Lux-Components-Theme lokal auschecken.
2. Das Theme lokal bauen und mit den Components verlinken.
3. Die Demo-Anwendung starten und die Seite für den lux-Master-Detail-AC öffnen.
4. In den Entwickler-Einstellungen auf "Mobile Ansicht" wechseln und das "Iphone 12" o.ä. Gerät auswählen.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/3acf7b50-f133-44d5-bdcf-32b8c3159471)
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/ed847e5a-495b-47bd-9f81-909cc1672f9f)

**Test A: Initiales Laden ohne selektiertes Element**

1. In VSCode die Datei "master-detail-authentic-example.component.html" öffnen
2. In Zeile 12 für den Wert "selecetedDetail" auf "null" setzen und die Änderung speichern.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/1dc62949-3569-4541-87e8-db88f3d54fa8)
3. Im Browser "F5" drücken.

**Erwartetes Ergebnis:**
Die "Master-Liste" wird angezeigt.

**Test B: "Zurück zu Liste"-Button ist bei leerem Detail nicht klickbar**

1. Code-Änderung von Test A zurücknehmen.
2. Im Browser in Footer der Master-View den Menü-Punkt "Liste leeren" wählen.
3. In der leeren Detail-View den Button "Zurück zur Liste" klicken.

**Erwartetes Ergebnis:**
Der Button ist klickbar und die Master-View wird angezeigt.

**Test C: Ausgeklapter Filter ist nach Öffnen und Schließen der Master-View noch geöffnet. Der Optionen-Button reagiert auf ersten Klick.**

1. Im Browser in der Master-Liste den Filter erweitern
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/504b7b72-29bc-4fc9-b428-bf02669aef73)
2. Auf ein Listen-Element klicken, um in den Detail zu wechseln.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/2ab948db-8518-4b48-acba-357cccb1be5e)
3. Zurück zur Liste wechseln.
4. Den Button "Weniger Optionen" klicken.

**Erwartetes Ergebnis**
Der Filter klappt sich beim ersten Klick auf den Button ein.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3208) und MacOS 13.4.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS: Safari -> OK
Windows: Edge -> OK
