### ISSUE TITLE
Beispieldateien zu den Lizenzhinweisen und readme anpassen

### ISSUE THREAD

**Issue by DSeifer** [IHK-GfI/lux-components#340]
Die Beispieldateien zu den Lizenzhinweisen für Icons und Fonts sollten dahingehend angepasst werden, dass sie allgemeingültig sind. Z.B. sollte am Anfang nicht "In dieser Demo ..." sondern "In dieser Anwendung ..." stehen.
Auch die Verlinkungen und Lizenztexte müssten nochmal überprüft werden. (siehe e-Mail von Stephan Flake).

Bitte auch die Die readme-files dahingehend überarbeiten, dass klar wird, dass die Lizenztexte ggf. produktspezifisch anzupassen sind.

**Comment by DSeifer** [comment]
### Beispiel aus OZG

### Lizenzhinweise
**Lizenzhinweis - Icons**
In diesen Webseiten wurden Streamline-Icons über das Github-Projekt https://github.com/IHK-GfI/lux-components-icons-and-fonts der IHK-GfI mbH eingebunden. Die verwendeten Streamline-Icons laufen unter der Lizenz [Creative Commons 4.0](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0). Der Urheber ist [streamlinehq.com](https://www.streamlinehq.com/). Bezugsquelle: [Core Line - Free (streamlinehq.com)](https://www.streamlinehq.com/icons/streamline-mini-line). Die Lizensierungsinformationen sind verfügbar unter https://www.streamlinehq.com/license-free. Die Icons aus dem o.g. Iconset wurden durch die IHK-GfI mbH nicht verändert. Im o.g. Github-Projekt wurden jedoch eigene Icons im selben Stil erstellt und der Sammlung unter gleicher Lizenz hinzugefügt.

**Lizenzhinweis - Fonts**
Diese Webseiten verwenden die Schriftarten "Source Sans Pro" designed by Paul D. Hunt (lizensiert unter SIL Open Font License V1.1) sowie "BloggerSans" created by Sergiy Tkachenko (Lizenz: https://www.fontsquirrel.com/license/blogger-sans, lizensiert unter [Creative Commons 4.0](https://creativecommons.org/licenses/by/4.0/)).

**Comment by patrowe** [comment]
Die Texte wurden überarbeitet und ergänzt.

@DSeifer Bitte testen!

**Comment by thodic77** [comment]
@DSeifer: Ich habe den Test übernommen.
