### ISSUE TITLE
lux-autocomplete - Multiselect ermöglichen

### ISSUE THREAD

**Issue by Stathi1404** [IHK-GfI/lux-components#344]
Im lux-select gibt es die Funktion des Multiselect, aber hier kann man nicht schön "suchen".
Im lux-autocomplete kann man schön "suchen", aber man kann nicht mehrere Treffer auswählen.

Die Erweiterung des lux-autocomplete um ein Multiselect wäre sicherlich sinnvoll.

**Comment by thodic77** [comment]
Es tut mir leid, aber das LUX-Autocomplete ist an ein Textfeld gebunden und unterstützt keine Mehrfachselektion. 
Siehe https://v14.material.angular.io/components/autocomplete/overview
