### ISSUE TITLE
lux-table - Fehlermeldung bei fehlenden ng-template verbessern

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#345]
Aktuell sieht die Fehlermeldung wie folgt aus: 

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/24f50243-7d6a-46f9-ba6a-ce5995bcd260)

### Akzeptanzkriterien

- Die Fehlermeldung enthält einen aussagekräftigen Hinweis auf das fehlende ng-template-Tag.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/8a59b451-0b9a-42ef-9df4-74e2da3aed7a)

### Test

- In der Datei "src/app/demo/components-overview/table-example/table-example.component.html" ein `<ng-template>`-Tag aus einem `<lux-table-column-header>`-Tag löschen und speichern.
  
  ![image](https://github.com/IHK-GfI/lux-components/assets/32597554/9006e409-f437-4a7d-bacc-0d56d7c8df13)

- Die Demoseite "Table" öffnen. 
- Die Debugconsole (F12 in Chrome) öffnen.
- Prüfen, ob die aussagekräftigere Fehlermeldung geloggt wurde.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3208) und MacOS 13.4.1 (c) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari -> OK
Windows: Edge -> OK
