### ISSUE TITLE
Selected-Nav-Item in lux-app-header-ac ist verschoben

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#349]
Das Label des Selected-item in der Nav-Bar des App-Headers ist nach oben verschoben.
Dieses soll gefixt werden.
![Screenshot nav-bar](https://github.com/IHK-GfI/lux-components/assets/49644099/971293bd-3e10-42e4-9d99-9aa07d03b188)

Aktzeptanzkriterium:
Die Labels aller Nav-Items sind auf einer Höhe.

**Comment by patrowe** [comment]
Das Problem wurde gefixt.
![Screenshot nav-bar2](https://github.com/IHK-GfI/lux-components/assets/49644099/0093269d-8931-4f42-bc10-a60d3cd6ed9b)

Bitte Testen!

**Comment by patrowe** [comment]
**Test:**

Vorbedingung:
- Den Branch für das lux-components-theme auschecken.
- Das Theme lokal bauen und lokal mit den Components verlinken
- Das Demo öffnen.

Test:
- Ein Element aus der Nav-Liste auswählen und prüfen, dass die Elemente auf einer Linie ausgerichtet sind. (Bild siehe oben.)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3324) und MacOS 13.4.1 (c) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari -> OK
Windows: Edge -> OK
