### ISSUE TITLE
lux-master-detail-ac: keyboard-access für die Master-Liste überarbeiten

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#350]
Aktuell wird bei Navigation mit dem Keyboard (Tab) zunächst die gesamte Liste im Master-Detail fokussiert. Danach kann man mit den Pfeiltasten durch die Liste navigieren, mit einem weiteren Tab kommt man aus der Liste heraus.

Dieses soll geändert werden. Wird Liste per Tab erreicht, soll das "aktive/ausgewählte" Element fokussiert werden. Danach soll die Navigation durch die Liste wie bisher mit den Pfeiltasten erfolgen. Mit einem weiteren Tab wird die Liste verlassen.
Ist kein Element ausgewählt, soll das oberste Element fokussiert werden.

Akzeptanzkriterium:
Mit dem Tab-Key wird das ausgwählte bzw. das oberste Element fokussiert. Mit einem weiteren Tab wird die Liste verlassen. Die bisherige Navigation mit Pfeiltasten durch die Liste bleibt erhalten. Die Screenreader-Funktionalität muss erhalten bleiben bzw. angepasst werden.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
Bitte testen!

**Comment by patrowe** [comment]
**Test**

**Vorbedingungen:**
- die angehängten Branches für das Theme und die Components jeweils auschecken
- das Theme lokal bauen und lokal mit den Components verlinken
- das Demoprogramm für die Components starten

**Test A: Fokus-Reihenfolge, bei Selektiertem List-Item (default in der Demo)**
1. Den Focus im Filter "platzieren" dafür den Button "Mehr Optionen" 2mal klicken (Dadurch schließt sich der Filter wieder)
2. Mit der Tabulator-Taste durch die Seite navigieren (mindestens 3 Schritte)
![Screenshot 2023-08-16 153945](https://github.com/IHK-GfI/lux-components/assets/49644099/ea42a9cd-2fcf-464f-a1a1-97b4e3f99c95)
3. Dabei sollen die Elemente in folgender Reihenfolge fokusiert werden (wichtig in der Masterliste wird Eintrag 2 fokusiert)
![Screenshot 2023-08-16 155205](https://github.com/IHK-GfI/lux-components/assets/49644099/25646c04-1a98-4f8f-99f2-9f77d5bc8f1b)

**Test B: Fokus-Reihenfolge ohne selektiertes List-Item**
1. Das Menü im Master-Footer öffnen und zuerst "Liste leeren" wählen, danach wieder "Liste füllen", dadurch wird das selektierte Position zurückgesezt.
2. Die Schritte 1 und 2 von Test A wiederholen.
3. Die Elemente werden wie oben fokusiert, nur in der Masterliste wird Eintrag 1 fokusiert.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3324) und MacOS 13.4.1 (c) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Firefox, Chrome, Safari -> OK
> Im Safari muss in den Einstellungen unter Erweitert die Option "Über Tabulatur jedes Objekt auf einer Webseite hervorheben" aktiviert sein, damit die programmierte Tabulatorreihenfolge genutzt wird!

Windows: Edge, Firefox, Chrome -> OK
