### ISSUE TITLE
lux-Table: innerhalb der Standard-Table-Cell wird die Schrift Roboto verwendet.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#354]
Die Standard-Tabellen Zellen werden von Material noch mit der Schrift Roboto überschrieben.
Hier soll die lux-table angepasst werden, dass in allen Zellen die Theme-Schrift "Source Sans Pro" angezeigt wird.

Akzeptanzkriterium:
Innerhalb einer lux-table wird ausschließlich nur noch die Schriftart "Source Sans Pro" verwendet.

**Comment by patrowe** [comment]
**Test**

**Vorbedingungen:**
1. Die Branches jeweils für das Theme und die Components auschecken.
2. Das Theme lokal bauen und lokal mit den Components verlinken
3. Das Demo starten.

**Test-Durchführung:**
1. Die Seite für die Lux-Table öffnen.
2. Das Beispiel nach unten scrollen und in der Test-Tabelle die Einträge vergleichen. Dazu über die Entwickler-Tools die font-family überprüfen.

**Gewünschtest Ergebnis:**
Innerhalb der Tabelle wird in jeder Zelle  die Schrift "Source Sans Pro" verwendet. 
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/74a21e4b-bb96-452e-b65d-224d1e5a44b4)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3324) und MacOS 13.4.1 (c) mit den jeweils aktuellen Browserversionen getestet:
MacOS: Firefox, Chrome, Safari -> OK
Windows: Edge, Firefox, Chrome -> OK
