### ISSUE TITLE
lux-list: Sporadisch auftretende Fehler beheben

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#356]
Der Issue #350: lux-master-detail-ac führt zu sporadischen Fehlern in den Tests der LUX-List.

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/159cca99-e1e3-4f7e-852b-d44f35aabe5c)

Akzeptanzkriterien

- Auch mehrfach hintereinander und parallel durchgeführte Tests laufen fehlerfrei durch.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

### Test

- In der Datei _karma.conf.js_ alle möglichen Browser (z.B. _['Chrome', 'Firefox', 'Edge']_) eintragen.
- Dann die Tests mit `npm run test` starten. 
- Prüfen, dass alle Tests erfolgreich durchlaufen.
- Den Vorgang mehrere Male wiederholen.

**Comment by thodic77** [comment]
@patrowe: Bitte testen.

**Comment by patrowe** [comment]
Test wurde mehrfach durchgeführt unter
Win 10 Enterprise für die Browser Edge, Firefox und Chrome -> OK
macOS Ventura 15.0 für die Browser Safari, Edge, Firefox unc Chrome -> OK
