### ISSUE TITLE
Barrierefreiheit: lux-tile - ARIA-Attribute ergänzen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#358]
Die Komponente lux-tile ist eine interaktive Schaltfläche. Daher muss sie als solche gekennzeichnet werden, damit sie von den Screen-Readern als solche erkannt wird.

**Akzeptanzkriterium**
Die Komponente hat foglende Attribute erhalten:
aria-role = "link"
aria-label soll mit dem Wert von "luxLabel" belegt werden
aria-description soll mit dem Wert von "luxSubtitel" belegt werden.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3324) und MacOS 13.5.2 mit den jeweils aktuellen Browserversionen nachgetestet:
**MacOS:** 
Safari -> Sprachausgabe: "Link - Komponenten - Inhalt"
Firefox -> Sprachausgabe: "Link - Komponenten - Haut - Alle Komponenten auf einem Blick"
Chrome -> Sprachausgabe: "Link - Komponenten - Mein"

**Windows:** 
Edge -> Sprachausgabe: "Mein Landmark Komponenten Link Alle Komponenten auf einem Blick"
Chrome -> Sprachausgabe: "Komponenten Link Alle Komponenten auf einem Blick"
Firefox -> Sprachausgabe: "Mein Landmark Komponenten Link Alle Komponenten auf einem Blick"

Aufgrund der sehr unterschiedlichen Ausgabe kann ich den Issue leider nicht schließen.
