### ISSUE TITLE
Barrierefreiheit: lux-textbox soll Property luxHeading erhalten

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#360]
Die Komponente lux-textbox nutz für die Darstellung eines Titels eine h3. Dieses soll wie bei der lux-Card veränderbar sein. Damit eine Webseite Barrierfrei ist, muss sie eine durchgehende "Headingstruktur" haben. Deshalb soll die Property luxHeading eingeführt. Das Styling soll sich dabei nicht ändern.

Akzeptanzkriterium:
Die Komponente lux-textbox hat die Property luxHeading erhalten. Der Default-Wert und das Verhalten, wird wie bei der lux-card umgesetzt. Das bisherige Styling wird nicht verändert.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3324) und MacOS 13.5.2 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Firefox -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
Firefox -> OK
