### ISSUE TITLE
Barrierefreiheit: Text soll auf 200% vergrößerbar sein

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#362]
Laut WCAG-Kriterium "1.4.4 Resize text Level AA" soll Text ohne Assistenztechnologie (z.B. Bildschirmlupe) auf 200% vergrößert werden können.

Technisch lässt sich das umsetzen, indem Schriftgrößen statt mit px mit rem angegeben werden.

Es ist zu prüfen, bei welchen Komponenten dieser Schritt weitere Anpassungen erfordert, z.B. der Button muss evlt mit der Schrift "mitwachsen" oder es der vergrößerte Text bricht nicht um und wird am Rand abgeschnitten.

**Comment by patrowe** [comment]
Im ersten Schritt sollen die Schriftgrößen für Headlines h1,..., h6, p, div, small sollen in rem definiert werden. Die Werte wurden mit hilfe des Type-Scaling-Systems "Major-Second" bestimmt.

Ebenso soll der Wert für  die Variable $form-control-sizein rem definiert werden.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
@DSeifer bitte Testen.

**Comment by patrowe** [comment]
Test

1. Testvorbedingungen:
- die Angehängten Zweige für die Lux-components und das Lux-Components-theme herunterladen
- das Theme lokal bauen und lokal mit den Components verlinken
- die Demo-Anwendung starten
- unter Windows Einstellungen>Erleichterte Bedienung>Bildschirm die Einstellungen für die Textgröße auf 200% setzen udn auf Anwenden klicken
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/d5df535d-6e9b-497a-9b89-cae1dabc2e0f)

2. Testdurchführung:
Die einzelnen Seiten der Demoanwendungen auf abgeschnittene Texte oder Fehlerhafte Anzeigen überprüfen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4046) und MacOS 14.3.1 mit den jeweils aktuellen Browserversionen und in beiden Themes getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
