### ISSUE TITLE
Barrierefreiheit: lux-dialog hat keine Heading

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#370]
Die lux-dialog-Komponente besitzt keine Heading. Da der bisherige Seiteninhalt durch das Öffnen eines Dialogs ausgeblendet wird, muss die Dialog-Komponente eine eigene Heading enthalten.
Analog zu den Empfehlungen der Angular-Material-components soll Titel in einer h2 dargestellt werden.
vgl. https://accessibleweb.com/question-answer/how-should-i-handle-headings-in-a-modal/
und https://material.angular.io/components/dialog/examples

Akzeptanzkriterium
Der Titel des Dialogs wird in einer h2 dargestellt.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt. Bitte Testen.

Für den Test die Erweiterung in Chrome hinzufügen
https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi?utm_source=ext_sidebar&hl=de

**Comment by patrowe** [comment]
### Test

_Vorbedingungen:_
Den angehängten Pullrequest auschecken und die Demo starten.
Die Erweiterung headingsMap in den Entwicklertools starten.

_Test:_
Auf die Test-Seite für Dialoge wechseln, nach unten scrollen und den Button "Öffnen(Preset)" klicken.

_Zu erwartendes Ergebnis:_
Bei geöffnetem Dialog zeigt headingsMap folgende Struktur an.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/f27918d7-94e7-456a-aa3a-9e5923a8dc6b)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3448) und MacOS 14.0 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari -> OK
Windows: Edge -> OK
