### ISSUE TITLE
Autocomplete in lux-textarea-ac funktioniert nicht

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#375]
Die Property luxAutocomplete zeigt keine Auswirkungen bei der lux-textarea-ac.
Diese Funktion soll gefixt werden.

Aktzeptanzkriterium:
Die lux-textarea-ac bietet die Autocomplete-Furnktion durch den Browser an.
Über die Property luxAutocomplete kann diese Funktion ein und ausgeschaltet werden.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt, bitte Testen.

**Comment by patrowe** [comment]
### Test

Vorbedingung:
- den angehängten Zweig auschecken
- die Demo starten

Test:
- die Seite für die Textarea öffnen
- im Feld "luxAutocomplete" den Wert "name" auswählen
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/dc07965d-3966-468a-b65b-92b722c50a1b)
- in die Textarea mit dem Cursor klicken

Zu erwartendes Ergebnis:
- ein Dropdown mit Vorschlägen erscheint, eine gewählte Auswahl fügt sich in die Textarea ein.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/bad9193b-7e74-4509-a785-043848ca026d)

Falls nicht, kann es sein dass im Browsercache keine Daten für das "Autofill/Autocomplete" hinterlegt sind.
Hier kann man über die Einstellungen für den Browser Muster-Daten für Autofill/Autocomplete hinterlegen.

Nach dem Test den Wert für luxAutocomplete auf "off" setzen. Jetzt sollte diese Funktion in der Textarea nicht mehr funktionieren.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3448) und MacOS 14.0 mit den jeweils aktuellen Browserversionen getestet:
MacOS: Safari -> OK
Windows: Edge -> OK
