### ISSUE TITLE
LuxTable Doppelklick

### ISSUE THREAD

**Issue by SNneuf** [IHK-GfI/lux-components#377]
Um LuxTable auf mehr Seiten verwenden zu können, brauchen wir ein Feature, womit über einen Doppelklick auf einen Eintrag in der Table, sich eine Seite öffnet. 
Etwas konkreter: wir haben eine Seite auf der nach Anträge gesucht werden kann. Diese werden in einer Tabelle aufgelistet. Der entsprechende Antrag (URL) soll sich über einen Doppelklick auf den Eintrag in der Tabelle öffnen.

**Comment by thodic77** [comment]
Es ist nicht geplant einen Doppelklick in der Tabelle umzusetzen. 

Die Tabelle verfügt über das Output-Event `luxSelectedChange`. Aktuell wird die geklickte Zeile nicht hervorgehoben und ist daher nicht so gut geeignet. Besser wäre die Alternative über eine zusätzliche Aktion-Spalte. 

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/d3671682-05ec-4747-a9b9-56d77a52daf2)

oder 

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/f7fecfc3-d0ad-472b-bdcd-4636dbba1b21)

Sollte das nicht passen, gerne bei mir melden.

**Comment by thodic77** [comment]
Da in einem Projekt die Kunden bereits an den Doppelklick gewöhnt sind, wurde die Funktionalität doch in die LUX-Components aufgenommen. Es wurde das Property "luxDoubleClicked" eingeführt.

**Comment by thodic77** [comment]
### Test

- Die Demoseite "Tabelle" öffnen. 
- Das Toggle "luxMultiSelect" deaktivieren.
- Das Toggle "luxDoubleClicked" aktivieren.
- Die Debugconole  (F12 im Chrome) öffnen.
- Einen Doppelklick auf einer beliebigen Tabellenzeile ausführen.
- Prüfen, ob in der Console eine Logausgabe zu sehen ist.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3570) und MacOS 14.0 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Firefox -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
Firefox -> OK
