### ISSUE TITLE
Erweiterung LuxFormComponentBase: Neue bzw. angepasste Funktion zur Anzeige von Erklärungstext, wenn das Feld den Fokus hat

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#38]
Hallo,

in der LuxFormComponentBase gibt es die Property 

> luxHint

Aktuell wird der bei luxHint angegebene Text immer unterhalb der Komponente dargestellt.
Dies kann bei vielen Komponenten mit einem Text in luxHint innerhalb einer Komponente sehr überfrachtet wirken.

Wir würden uns daher als Verbesserung wünschen, dass es eine Möglichkeit gibt, dass der luxHint Text nur bei fokussierter Komponente dargestellt wird.

Es müsste ein neues Attribut in luxFormComponentBase mit Namen luxShowHintAtFocus=true|false umgesetzt werden:

1. Bei luxShowHintAtFocus=true: Nur bei Fokussierung der Komponente wird der unter luxHint gesetzte Text als luxHint dargestellt. Bei Verlieren des Fokus wird der luxHint nicht mehr dargestellt und der Text verschwindet.
2. Bei luxShowHintAtFocus=false: Der unter luxHint gesetzte Text wird immer dargestellt, unabhängig davon, ob die Komponente fokussiert ist oder nicht. Ist kein Text in luxHint angegeben, wird kein Text dargestellt.

Standardmäßig würde luxShowHintAtFocus=false gesetzt sein, damit die Komponenten sich bei nicht gesetztem luxShowHintAtFocus genauso wie aktuell verhalten.

Vielen Dank und viele Grüße
Sascha Bülow

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt.
