### ISSUE TITLE
LuxTable: Reihen einfärben

### ISSUE THREAD

**Issue by SNneuf** [IHK-GfI/lux-components#380]
Um Informationen zu einem Eintrag in der Table schnell sichtbar zu machen, würden wir die Reihe in der Tabelle gerne farbig gestalten und die Farbe in einer Legende erklären.

**Comment by thodic77** [comment]
Man kann die Reihen bereits individuell einfärben. Ein Beispiel ist hier: 
https://github.com/IHK-GfI/lux-components/wiki/lux%E2%80%90table#6-custom-css

**Comment by thodic77** [comment]
Die Legende muss selbst erstellt werden und sollte auf den individuellen Style abgestimmt werden.
