### ISSUE TITLE
LuxTable: Platzhalter für leere Zellen

### ISSUE THREAD

**Issue by SNneuf** [IHK-GfI/lux-components#381]
Wir hätten gerne die Möglichkeit einen Platzhalter zu definieren, der dann leere Zellen ersetzt.

**Comment by thodic77** [comment]
Die Anforderung müsste noch detaillierter Beschrieben werden. 

Aktuell werden die Zellinhalte durch den Fachentwickler bestimmt und sind nicht Teil der LUX-Components.  D.h. es gibt aktuell keine Einschränkungen. Was sollten die LUX-Components genau bieten?
