### ISSUE TITLE
LuxFilterForm: Verwendung von LuxRadio ermöglichen

### ISSUE THREAD

**Issue by caro-kos** [IHK-GfI/lux-components#382]
Einige Componenten können schon innerhalb einer LuxFilterForm verwendet werden. 
Wir bräuchten die Möglichkeit auch eine **LuxRadio**AcComponent im Filter einzusetzen.
Momentan führt die Verwendung zum "Die Formularkomponente ist unbekannt!"

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

### Test

- Die Demoseite "Filter" öffnen.
- Das Filterpanel öffnen.
- Den Radio-Button "B" auswählen.
- Den Filtern-Button anklicken.
- Prüfen, ob der Wert in der Debugconsole (F12 im Chrome) erscheint.
- Auf den Tab "Erweitert" wechseln.
- Die Toggle "luxFilterDisabled" und "luxFilterHidden" für die Radio-Komponente testen.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19044.3570) und MacOS 14.0 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Firefox -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
Firefox -> OK
