### ISSUE TITLE
LuxLookupCombobox: Ungültige Werte werden als gültig angezeigt

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#383]
In der Komponente "lux-lookup-combobox" ist die Option luxBehandlungUngueltige im Fall von 'ausblenden' ohne funktion, weil alle Werte als gültig behandelt werden. Auch wenn das gültig-bis Datum eines Schlüssels bereits erreicht wurde.

Nachstellbar in ENTW, Knr. 101 mit der Schlüsseltabelle 500037: 

_html_
...
<lux-lookup-combobox luxLabel="Abmeldungsgrund"
                             luxControlBinding="endeGrund"
                             [luxParameters]="getLookupParameters()"
                             luxTableNo="500037"
                             [luxRenderProp]="kurzText"
                             [luxBehandlungUngueltige]="behandlungUngueltige"
                             luxLookupId="abmeldungs-grund"></lux-lookup-combobox>
...

_ts_
...
 getLookupParameters() {
    return new LuxLookupParameters({
      knr   : this.knr,
      raw   : false,
      fields: [ LuxFieldValues.kurz ],
      keys  : []
    });
  }
...
public behandlungUngueltige: LuxBehandlungsOptionenUngueltige = LuxBehandlungsOptionenUngueltige.ausblenden;

Genutzt wird die Version 13.3.0 der lux-components.

**Comment by thodic77** [comment]
Bitte das Feld `LuxFieldValues.gueltig_bis` noch in die `fields` aufnehmen. Anhand dieses Feldes wird die Gültigkeit bestimmt, dann sollte alles wie gewohnt funktionieren.
