### ISSUE TITLE
lux-card: Die Property "luxTitleLineBreak" wirkt sich initial nicht aus

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#384]
Die Property `luxTitleLineBreak=false` wirkt sich initial nicht aus, sondern erst nach dem erneuten setzen. 

### Akzeptanzkriterien

- Die Property `luxTitleLineBreak=false` wirkt sich initial aus.

**Comment by thodic77** [comment]
###  Test

- In der Datei _card-example.component.ts_ die Property _titleLineBreak_ auf den Wert _true_ setzen.
- Prüfen, dass der Titel nicht umgebrochen wird.

Falsch:
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/5883b0fd-69f8-4787-a3d1-de139eb270d2)

Korrekt:
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/38844db7-ff3f-4b78-b8e3-50adaac17047)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3570) und MacOS 14.0 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> **ERR** (Zuckt nur und bleibt bei "ohne Umbruch")
Firefox -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
Firefox -> OK

**Comment by DSeifer** [comment]
Unter MacOS 14.0 mit Safari nachgetestet: OK

**Comment by TheLethalGoose** [comment]
In Version 15.4.0 der LuxComponents tritt der Fehler immer noch auf. Änderungen an **luxTitleLineBreak** haben keine Auswirkungen. Der Card Title ist immer abgeschnitten.

**Comment by DSeifer** [comment]
Ich habe das wie beschrieben nachgetestet und kann den beschriebenen Fehler nicht reproduzieren. Bitte reproducer oder Videobeispiel zur Verfügung stellen.

**Comment by TheLethalGoose** [comment]
Habe den Fehler bei mir gefunden, danke für die schnelle Rückmeldung!

**Comment by DSeifer** [comment]
Könntest Du mich bitte einmal direkt kontaktieren, damit ich einen Realnamen zuordnen kann? ;-)
