### ISSUE TITLE
Flex-Layout in dem Modul lux-layout austauschen.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#388]
Bei den Komponenten im Modul lux-layout müssen die Einträge von Flex-Layout durch eigenes CSS ausgetauscht werden.

Dazu gehören die Komponenten:
lux-app-footer, lux-app-header, lux-app-header-ac
lux-card, lux-tile, lux-tile-ac
lux-list
lux-stepper
lux-tabs

sowie evtl vorhandener Teilkomponenten.

Akzeptanzkriterium:
Die oben genannten Komponenten verwenden keine Befehle von Flex-Layout.
Sofern noch nicht vorhanden, erhält jede Komponente eine eigene Klasse im lux-componentens-theme.

**Comment by patrowe** [comment]
### Test für lux-list

**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten und die Seite für lux-list öffnen.

**Test-Durchführung:**

**1. Hover:** Der Hover-Effekt für ein nicht selektiertes Listenelement soll wie folgt aussehen:
Authentic:
<img width="545" alt="Bildschirmfoto 2023-11-22 um 09 02 15" src="https://github.com/IHK-GfI/lux-components/assets/49644099/1d625645-34ad-42a5-a2ec-b92a1e4a4852">
Green:
<img width="540" alt="Bildschirmfoto 2023-11-22 um 09 05 09" src="https://github.com/IHK-GfI/lux-components/assets/49644099/b3c713c6-6bb1-49e5-b50e-2141811d880b">

**2. Selected:** Ein Listenelement ist durch Mausklick auf das Element oder durch "Enter" bei einem fokussierten Element Selektiert. Ein Selektiertes Element soll wie folgt aussehen
Authentic:
<img width="543" alt="Bildschirmfoto 2023-11-22 um 09 09 28" src="https://github.com/IHK-GfI/lux-components/assets/49644099/5bb08a6b-ae12-4cb9-bec5-304ba4c68d3f">
Green:
<img width="539" alt="Bildschirmfoto 2023-11-22 um 09 08 51" src="https://github.com/IHK-GfI/lux-components/assets/49644099/a2c22cae-304a-45ed-ab7c-e22ddb827aba">
**3. Focus:** Mit den Pfeiltasten kann durch eine Liste mit der Tastatur navigiert werden.
Authetic:
<img width="543" alt="Bildschirmfoto 2023-11-22 um 09 13 44" src="https://github.com/IHK-GfI/lux-components/assets/49644099/22cc412a-e566-4bfb-a488-1f8ab724da0f">
Green: (1px gepunktete Linie)
<img width="538" alt="Bildschirmfoto 2023-11-22 um 09 14 38" src="https://github.com/IHK-GfI/lux-components/assets/49644099/508ec898-a720-4098-b1d6-2fb811acdb41">
**4. Empty-List-Item**: Unter Konfiguration den Button "Leeren" klicken, um die Listen-Elemente zu löschen. 
Das "Empty-List-Item" soll angezeigt werden. (In beiden Themes gleich)
<img width="180" alt="Bildschirmfoto 2023-11-22 um 09 19 40" src="https://github.com/IHK-GfI/lux-components/assets/49644099/1cf7adbc-69f0-4042-b87a-4945454a788f">

**Comment by patrowe** [comment]
### Test für Lux-Card:
**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten und die Seite für lux-card öffnen.
Sofern nicht anders beschrieben, sind die Tests für beide Themes durchzuführen. Die Unterschiede bestehen nur in der Schriftart/größe und Buttonform, die gewünschten Funktionen sind jeweils gleich. 

**Test-Durchführung:**
_1. luxTitleLineBreak_: Im default können der Titel und der Subtitel mehrzeilig sein. Dafür die Breite des Browserfensters verändern bis der Zeilenumbruch eintritt. Danach die Property luxTitleLineBreak auf "false" setzen, jetzt werden Titel und Subtitel einzeilig, der überschüßige Text wird abgeschnitten und "..." erscheint am Zeilenende.
Mit Zeilenumbruch:
<img width="435" alt="Bildschirmfoto 2023-11-22 um 10 21 36" src="https://github.com/IHK-GfI/lux-components/assets/49644099/eb03ffce-a599-439f-ae97-2f0e069e639a">
Ohne Zeilenumbruch
<img width="423" alt="Bildschirmfoto 2023-11-22 um 10 22 11" src="https://github.com/IHK-GfI/lux-components/assets/49644099/6dfecbb4-5fd5-4058-acea-3bb0db493081">
_2. luxIcon / luxCardInfo anzeigen:_ Im Card-Header können ein Icon (links neben dem Titel) und eine CardInfo (rechts neben dem Titel) individuell angezeigt werden. Wird eines der genannten Elemente ausgeblendet sollen der Titel und der Subtitel den entsprechenden Platz einnehmen. Über die Schalter unter Erweitert können diese beiden Elemente individuell ein/ausgeblendet werden.
ohne luxIcon: Titel/Subtitel werden linksbündig am Kartenrand ausgerichtet.
<img width="427" alt="Bildschirmfoto 2023-11-22 um 10 31 38" src="https://github.com/IHK-GfI/lux-components/assets/49644099/1f0152f1-f9e0-447d-8f0c-775a609e796e">
ohne luxCardInfo: Titel/Subtitel nehmen den Platz bis zum rechten Rand der Card ein.
<img width="428" alt="Bildschirmfoto 2023-11-22 um 10 34 08" src="https://github.com/IHK-GfI/lux-components/assets/49644099/70bc3384-4220-48ab-a6c9-25b1e8d40427">
_3. luxCardActions anzeigen_:
Über diese Property kann die Card mit eigenen Actions versehen werden. Sie wird klickbar und erhält einen Hover-Effekt.
Unter Erweitert die Property luxCardActions aktivieren und auf die Card klicken. Ergebnis: Die Buttons am unteren Rand der Card werden ausgeblendet und eine "Snackbar" mit dem Text "Card clicked" erscheint.
Mouse-Hover: wie bei der lux-tile-ac.
_4. luxCardContentExpanded aktivieren:_
Den Schalter bei luxCardContentExpanded aktiveren auf true setzten.
Ergebnis: Der Button "Mehr Inhalt anzeigen" wird eingeblendet. Durch Betätigung dieses Buttons wird weiterer Inhalt unterhalb des Buttons angezeigt. Erneutes Klicken blendet diesen Inhalt wieder aus.

**Comment by patrowe** [comment]
### Test für Lux-Tile-Ac:
**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten und die Seite für lux-tile-ac öffnen. Die Tests sind für beide Themes durchzuführen. Die Unterschiede bestehen ausschließlich in der Schriftart.
Defaultansicht im Theme Authentic:
<img width="273" alt="Bildschirmfoto 2023-11-22 um 11 20 01" src="https://github.com/IHK-GfI/lux-components/assets/49644099/192aeef7-e6d6-481c-8ccb-7afffb970b1c">

**Test-Durchführung:**
_1. luxIcon anzeigen:_ Im Default wird ein Icon in der Kachel angezeigt. Wird der Schalter vor "luxIcon anzeigen" auf false gesetzt, wird das Icon durch eine Grafik ersetzt. Dabei darf sich Titelzeile nicht verschieben und der Subtitel bricht um.
Erwünschtes Ergebnis:
<img width="270" alt="Bildschirmfoto 2023-11-22 um 11 20 35" src="https://github.com/IHK-GfI/lux-components/assets/49644099/28263a3f-fbe1-458a-9ebc-2c7b187cb4b6">
_2. Hover:_ Mit der Maus über die Kachel Hovern. 
Erwünschtes Ergebnis:
<img width="271" alt="Bildschirmfoto 2023-11-22 um 11 20 14" src="https://github.com/IHK-GfI/lux-components/assets/49644099/a70b69f6-9e69-462f-a08d-ca78cb0b0446">
_3. luxShowNotification:_ Den Schalter auf True setzten
Erwünschtes Ergebnis:
<img width="286" alt="Bildschirmfoto 2023-11-22 um 11 28 54" src="https://github.com/IHK-GfI/lux-components/assets/49644099/426bb9ad-d58b-4a35-aad4-69e0b197d706">

Danach die NotifactionSize auf small und auf large setzten. Erwünschtes Ergebnis: Der Kreis behält seine Position und verändert nur die Größe.

**Comment by patrowe** [comment]
### Test für Lux-Tile
**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten und die Seite für lux-tile öffnen. Diese Komponente wird nur noch für das Green-Theme unterstützt und muss daher nur noch dafür getestet werden.
Defaultansicht:
<img width="254" alt="Bildschirmfoto 2023-11-22 um 12 38 31" src="https://github.com/IHK-GfI/lux-components/assets/49644099/4e675ec4-84e7-4d2b-b8b1-a624a1065e4b">

**Testdurchführung:**
_1. Hover:_ Mit der Maus über die Kachel hovern. Erwünschtes Ergebnis
<img width="271" alt="Bildschirmfoto 2023-11-22 um 12 38 01" src="https://github.com/IHK-GfI/lux-components/assets/49644099/044c4ae8-39b6-4a28-b746-8bece497a8d1">
_2. luxIcon anzeigen:_ Den Schalter für luxIcon anzeigen auf false setzen.
Erwünschtes Ergebnis:
<img width="250" alt="Bildschirmfoto 2023-11-22 um 12 40 07" src="https://github.com/IHK-GfI/lux-components/assets/49644099/062a02d6-9bf4-4a18-87fc-decaf53357c9">
_3. luxShowNotification:_ Den Schalter für luxShowNotification auf true setzen. Erwünschtes Ergebnis:
<img width="273" alt="Bildschirmfoto 2023-11-22 um 12 41 17" src="https://github.com/IHK-GfI/lux-components/assets/49644099/a09962f7-533d-4783-b013-0b09e4186539">
_4. luxCounter:_ Die Zahl 10 in das Textfeld "luxCounter" eintragen (wichtig luxShowNotification muss auf False stehen). Erwünschtes Ergebnis: 
<img width="261" alt="Bildschirmfoto 2023-11-22 um 12 41 02" src="https://github.com/IHK-GfI/lux-components/assets/49644099/8622ad82-dc7b-4ebd-9cd0-848f70cf8402">

**Comment by patrowe** [comment]
### Test für lux-app-header-ac

**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten.

**Testdurchführung**:
Der Header wird nur im Authentic-Theme angezeigt.
Gewünschte Ansicht in der Desktop-Größe:
<img width="1289" alt="Bildschirmfoto 2023-11-22 um 13 02 54" src="https://github.com/IHK-GfI/lux-components/assets/49644099/52cb4bde-8bad-44d7-a7f0-992ad0f095d4">
Gewünschte Ansicht für Mobile Version:
<img width="673" alt="Bildschirmfoto 2023-11-22 um 13 03 15" src="https://github.com/IHK-GfI/lux-components/assets/49644099/6ac75380-f66a-4f67-bef4-68d6724d119f">

**Comment by patrowe** [comment]
### Test für lux-app-header
**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten.

**Testdurchführung:**
Der Header wird nur im Green-Theme angezeigt.
Gewünschte Ansicht in der Desktop-Größe:
<img width="1155" alt="Bildschirmfoto 2023-11-22 um 13 06 02" src="https://github.com/IHK-GfI/lux-components/assets/49644099/bed75e53-b3ef-4d01-a805-5436541a2a10">
Mobile Version:
<img width="667" alt="Bildschirmfoto 2023-11-22 um 13 05 44" src="https://github.com/IHK-GfI/lux-components/assets/49644099/fceae9e8-44bb-4865-a189-3e82e972599f">

**Comment by DSeifer** [comment]
Die Dokumentation der Test´s bis hierher findet sich in Confluence: https://confluence.gfi.ihk.de/x/Hu6DPw

**Comment by patrowe** [comment]
### Test für Lux-Tabs

**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten und die Seite für die lux-tabs öffnen.

**Durchführung:**
Default der Demo-Komponente für Authentic:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/13768f66-7a1e-4707-8e3f-a9465dc0db35)
Default der Demo Komponente für Green:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/d8a5fe5e-2b6a-4e2a-8df6-fba0cac7b857)

- disabled: Unter Erweiterungen die Einstellungen für "Tab 1" öffnen und die Property "disabled" auswählen. 
zu erwartendes Ergebnis: In beiden Themes wird das Icon und das Label im Tab ausgegraut.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/e157c84f-ed67-4650-89fc-c7f7137fe37a)

- Mobile Ansicht: in den Entwicklertools auf "Mobile Ansicht" wechseln.
Zu erwartendes Ergebnis: In beiden Themes wird das Label im Tab wird ausgeblendet:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/1d2822f3-333c-4103-9b64-8815f98f4ef4)

**Comment by patrowe** [comment]
###Test für Lux-Stepper

**Vorbedingung:**
Die Zweige für die Lux-Components und Lux-Components-Theme auschecken.
Das Theme lokal bauen und mit den Components lokal verlinken.
Das Demo Starten und die Seite für die lux-stepper öffnen.

Default-Ansicht des lux-stepper (horizontal) für das Theme Authentic:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/577a5318-6acd-49b1-8fb6-a46597031ee2)
(vertikal)
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/70fd1d5c-1713-4219-bea9-bd81d0e55f94)

Default-Ansicht des lux-stepper (horizontal) für das Theme Green:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/a29666d2-ad00-4c03-92fb-0ad6516653f5)
(vertikal)
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/340af7e2-4930-4059-90be-64217a5d2efd)

**Test-Durchführung:**
- Die erforderlichen Angaben im Stepp 1 mit Probedaten ausfüllen und dann auf "weiter" klicken
  Zu erwartendes Ergebnis: die Ziffer 1 im Stepp-Header wird in ein Icon (Hier ein Stift) umgewandelt.  
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/e74d9502-0b92-482e-9178-49f940fc3808)

-  Unter Konfiguration>Allgemein die Property luxUseCustomeIcons auf true setzen.
Zu erwartendes Ergebnis: Anstatt der Ziffern im Header werden Icons angezeigt.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/00dccf18-5a9b-4e65-a68b-e4477cc6cc83)

**Comment by DSeifer** [comment]
Die Dokumentation der Test´s bis hierher findet sich in Confluence: https://confluence.gfi.ihk.de/x/Hu6DPw
Aktuell sind bis auf das Tastatur-Ansprungverhalten bei lux-List alle Tests OK.

**Comment by DSeifer** [comment]
Das Tab-Ansprungverhalten unter MacOS wurde wie beschrieben positiv nachgetestet.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3803) und MacOS 14.2.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK
