### ISSUE TITLE
Readonly mit Kopiermöglichkeit

### ISSUE THREAD

**Issue by ckutzner33** [IHK-GfI/lux-components#389]
Es ist nicht möglich als Benutzer aus eine Textbox einen Text zu kopieren, wenn dieser readonly ist. Diese Verhalten ist für UIs ungewöhnlich, da eigentlich bei readonly der Text nicht editiert aber weiterhin kopiert werden kann. Möchte man auch das Kopieren eines Textes verhindern, würde man das Flag disabled verwenden.

Ansonsten benötigen wir eine alternative Option, die es uns ermöglicht den Text nicht änderbar aber kopierbar zu machen.

**Comment by thodic77** [comment]
Es ist jetzt möglich, den Text aus den Formcontrols zu kopieren.

### Test

- Die Demo "Autocomplete" öffnen.
- Beliebige Werte eintragen.
- Das Toggle "luxReadonly" aktivieren.
- Den Text markieren. 
- Den Text mit Ctrl + C kopieren.
- Den Text in einen beliebigen Texteditor einfügen.
- Prüfen, ob der Text korrekt kopiert wurde.

Den Test für die folgenden Komponenten wiederholt: 

- Datepicker
- Datetimepicker
- File-Input
- Input
- Select
- Textarea

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3693) und MacOS 14.1.1 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Firefox -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
Firefox -> OK
