### ISSUE TITLE
lux-file-upload Dateiauswahl in iOS / Safari auf Iphone unmöglich

### ISSUE THREAD

**Issue by marcoebbinghausGFI** [IHK-GfI/lux-components#390]
Wir haben von einem Kunden das Feedback erhalten, dass es via Safari-Browser auf dem iPhone keine Möglichkeit gibt, eine Datei auszuwählen, wenn man auf den Upload-Link eines lux-file-uploads klickt. Stattdessen aktiviert sich direkt die Handykamera und man kann dann eben nur ein Foto machen. Das konnten wir reproduzieren.

Auf Android Smartphones (Chrome) öffnet sich korrekterweise ein Menü mit den Auswahlmöglichkeiten Kamera, Kamera Video und Medien.

**Comment by thodic77** [comment]
Wenn das Property _luxCapture_ nicht angegeben wird bzw. leer ist, wird trotzdem das Attribut _capture="environment"_ gerendert.

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/db8ae182-ac21-426d-bd76-c54b5444b60d)

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/be197bf7-4c65-477d-808a-76d7b00867ee)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3693) und MacOS 14.1.1 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Firefox -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
Firefox -> OK
