### ISSUE TITLE
lux-menu: Austausch von flex-layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#394]
Aus der Komponente lux-menu müssen die Befehle von Flex-Layout entfernt werden.
Für den Austausch stehen die neuen lux-layout-Klassen aus dem Lux-Components-Theme bereit.

Aktzeptanzkriterium:
Alle Befehle von angular/flex-layout wurden aus der Komponente entfernt.

**Comment by patrowe** [comment]
### Test für lux-menu

**Testvorbereitung**
- Die angehängten Zweige für die lux-components und das lux-components-theme auschecken.
- Das Theme lokal bauen und mit den lux-components lokal verlinken.
- Das Demoprogramm starten und die Seite für das lux-menu öffnen.

### Testdurchführung
**A Für Desktop-Variante: Das Browserfenster maximieren.**
Default-Ansicht der Testkomponente (alle Elemente sind sichtbar, kein Trigger-Button):
<img width="717" alt="Bildschirmfoto 2023-12-13 um 10 56 38" src="https://github.com/IHK-GfI/lux-components/assets/49644099/f8b08c49-d1cd-41d6-bc77-c7ca66c9a12a">

**- luxMaximumExtended auf den Wert 2 setzen:**
Zu erwartendes Ergebnis: 2 Menüeinträge und der Triggerbutton sind sichtbar. Triggerbutton öffnet ein Panel mit den weiteren 2Menüeinträgen.
<img width="523" alt="Bildschirmfoto 2023-12-13 um 11 00 16" src="https://github.com/IHK-GfI/lux-components/assets/49644099/dc725c0b-8c19-4ecb-b5e9-72b17931116f">

**-luxMaximumExtended auf den Wert 2 setzen und luxDisplayExtended auf false:**
Zu Erwartendes Ergebnis: 2 Menüeinträge und der Triggerbutton sind sichtbar. Der Triggerbutton befindet sich links.
<img width="273" alt="Bildschirmfoto 2023-12-13 um 11 03 28" src="https://github.com/IHK-GfI/lux-components/assets/49644099/ed08bad6-e00f-4ab4-af70-ee0e048fe1ff">

**-luxDisplayExtended auf false setzen:**
Zu erwartendes Ergebnis: Es ist nur noch der Triggerbutton sichtbar, alle Menüeinträge befinden sich im Menupanel.
<img width="306" alt="Bildschirmfoto 2023-12-13 um 11 05 59" src="https://github.com/IHK-GfI/lux-components/assets/49644099/549d22c6-8b8f-41d7-bd66-c5b69419b4be">

**B Responsives verhalten: Die Breite des Browserfensters schrittweise verringern.**
Die Menüeinträge in der Zeile müssen vollständig sichtbar bleiben. Erreicht der linke Menüeintrag den linken Rand, werden die Elemente von rechts anfangend nacheinander in das Panel verschoben werden.

vollständig Anzeige:
<img width="799" alt="Bildschirmfoto 2023-12-13 um 11 12 18" src="https://github.com/IHK-GfI/lux-components/assets/49644099/b88d180d-8df4-411a-9cfc-31325c03faff">

gekürzte Anzeige:
<img width="764" alt="Bildschirmfoto 2023-12-13 um 11 12 55" src="https://github.com/IHK-GfI/lux-components/assets/49644099/313cc542-871c-4e0a-882f-1d0f1967b73f">

**Comment by patrowe** [comment]
@DSeifer Bitte testen!

**Comment by DSeifer** [comment]
Der Test ist in Confluence dokumentiert.
