### ISSUE TITLE
lux-table: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#395]
Aus der Komponente lux-table müssen die Befehle von angular/Flexlayout entfernt werden.
Für den Ausstausch stehen die neuen layout-Klassen aus dem lux-components-theme bereit.

Akzeptanzkriterium:
Die Komponente lux-table enthält keine Befehle von angular/FlexLayout mehr bereit.

**Comment by patrowe** [comment]
### Test

**Testvorbereitung:**
- Die angefügten Zweige für die Lux-Components und das Lux-Components-Theme auschecken.
- Das Theme lokal bauen und lokal mit den Lux-Components verlinken.
- Das Demoprogramm starten und die Seite für die Lux-Table öffnen.

**Testdurchführung** 
_1. Filter anzeigen:_ Die Property luxShowFilter auf "true" setzen.
Zu erwartendes Ergebnis: Ein Eingabefeld über der Table wird angezeigt.
![Bildschirmfoto 2023-12-14 um 13 35 18](https://github.com/IHK-GfI/lux-components/assets/49644099/19a95232-eab5-4733-bd2d-44fae846d373)
_2. Pagination ein und ausblenden:_ Die Property luxShowPagination auf false setzen.
Zu erwartendes Ergebnis: Die Pagination wird ausgeblendet und die Tabelle erweitert sich nach unten.
_3. Tabelleneintrag editieren:_ In einer Tabellen-Zeile den Stift in der Spalte "Aktion" anklicken. 
Zu erwartendes Ergebnis: Die Tabelleneinträge werden als Input-Elemente angezeigt. Die Höhe der Tabellenzeile ändert sich nicht.
![Bildschirmfoto 2023-12-14 um 13 38 29](https://github.com/IHK-GfI/lux-components/assets/49644099/10bc0b9f-444f-49b3-92f9-f66ded545f54)
_4. Progressbar über der Tabelle anzeigen:_ Dafür auf die Seite "Table-Server" wechseln.
Auf den Button "Neuladen" am unteren Rand der Konfigurationen klicken.
Zu erwartendes Ergebnis: Die Progressbar wird über Tabelle angezeigt, die Tabelle darf dabei nicht verrutschen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3803) und MacOS 14.2.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK
