### ISSUE TITLE
lux-filter: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#396]
In den Komponenten des Moduls lux-filter müssen die Einträge von angular/flex-layout ausgetauscht werden.

Aktzeptanzkriterium:
Die Direktiven von flex-layout wurden durch entsprechenden CSS-Code ersetzt.

**Comment by patrowe** [comment]
### Test

**Testvorbereitung:**
- Die angehängten Zweige für die Lux-Components und das Lux-Components-Theme auschecken.
- Das Theme lokal bauen und lokal mit den Lux-Components verlinken.
- Das Demo-Programm starten und die Seite für Lux-Filter öffnen.

**Testdurchführung:**
**1. Für den Filter in einem Accordion (obere Testkomponente)**
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/66a39758-fb42-4747-8688-68854500ea1a)

- Auf das geschlossene Panel klicken, um den Filter zu öffnen.
Zu erwartendes Ergebnis: Das Panel öffnet sich und der Menu-Button für erweiterte Optionen erscheint im Panel-Header.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/cdfc9138-6db7-415f-8aff-62f4a573d0fd)

- Auf den Menu-Button im Panel-Header klicken.
Zu erwartendes Ergebnis: Das Menu klappt auf.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/38b0255d-ba8b-4a3c-b196-ba8fa88ce035)

- Den Filter wieder schließen und nun auf das "X" in dem Chip "Input: Lorem Ipsum" klicken.
Zu erwartendes Ergebnis: Der Chip und der Rahmen werden ausgeblendet und der Infotext "Es wird nach den Standardeinstellungen gefiltert." wird angezeigt.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/30d06da6-c675-4348-bf0f-12ae99fd790a)

**2. Für den Filter in einer Card**
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/098cf166-edc4-4065-ae3d-e71806a04643)

- Auf den Button "Mehr Option" klicken.
Zu erwartendes Ergebnis: Die Karte erweitert sich nach unten und weitere Elemente werden angezeigt. Durch erneutes Klicken auf den Button wird dieser Inhalt wieder ausgeblendet
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/f6147c4b-0108-4c51-99fa-87ac8806e30d)

- Auf den "Menu"-Button im Header klicken.
Zu erwartendes Ergebnis: Das Menu-Panel wird angezeigt.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/f6db25e1-2c66-4fc5-a8f6-26da805ffba7)

- Auf das "X" in dem Chip "Input: Lorem Ipsum" unterhalb der Card klicken.
Zu erwartendes Ergebnis: Der Chip und der Rahmen werden ausgeblendet und der Infotext "Es wird nach den Standardeinstellungen gefiltert." wird angezeigt.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/ba51cdda-f8c2-40e5-a4b3-0bcca96ed669)

**Comment by patrowe** [comment]
@DSeifer Bitte Testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3803) und MacOS 14.2.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK
