### ISSUE TITLE
lux-common: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#398]
Aus den Komponenten lux-message-box und lux-spinner müssen die Befehle von angular/flex-layout ersetzt werden.

Akzeptanzkriterium:
Die oben genannten Komponenten enthalten keien Befehle mehr von angular/flex-layout.
Das Layout der Komponenten, bleibt weitestgehend erhalten.

**Comment by patrowe** [comment]
Die Komponenten lux-spinner wurde durch lux-progress vom typ=luxSpinner ersetzt und wird nicht mehr benötigt.
Sie wird mit dem kommenden Release 16.0.0 aus den lux-components entfernt, die Überarbeitung bzgl. Flex-Layout wird daher für den Spinner nicht mehr durchgeführt.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt. Bitte testen.

**Comment by patrowe** [comment]
### Test

1. Testvorbereitung

- Die angehängten Zeige für die Lux-Components und das Lux-Components-Theme auschecken
- jeweils die Datei package-lock.json und den Ornder node-modules löschen
- jeweil npm install durchführen.
- das Theme lokal bauen und lokal mit den Components verlinken
- die Demoanwendung starten

2. Testdurchführung
- Die Seite für die lux-message-box öffnen.
- Default-Ansicht Theme-Authentic:
<img width="567" alt="Bildschirmfoto 2024-01-18 um 14 30 09" src="https://github.com/IHK-GfI/lux-components/assets/49644099/281e56f7-33c6-45b6-901f-748554c72dc2">

- Auf ein "X" in einer Message klicken. Zu erwartendes Ergebnis: Die Message wird gelöscht
- Danach mit dem Tab-Key durch die Messages tabben. Zu erwartendes Ergebnis: Es wird zuerst der Message-Text fokussiert und danach der X-Button. Die Farbe der Outline ist bei den farbigen Boxen weiß, bei der weißen Box ist die Outline hellblau. (für Theme Green ist es immer eine gepunktete schwarze Linie)
- den Wert bei luxMaximumdisplayed auf 5 setzen. Zu erwartendes Ergebnis: Es werden nur noch 5 Messages gleichzeitig angezeigt und ein Paginator erscheint.
<img width="1002" alt="Bildschirmfoto 2024-01-18 um 14 34 27" src="https://github.com/IHK-GfI/lux-components/assets/49644099/0ecaaa33-831d-4e52-a01f-ebd9afe5d633">

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3930) und MacOS 14.2.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK
