### ISSUE TITLE
lux-popup: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#399]
Aus den Komponenten lux-dialog (inkl. Subkomponenten) und lux-snackbar müssen die Befehle von angular/flex-layout ersetzt werden.

Akzeptanzkriterium:
Die oben genannten Komponenten enthalten keien Befehle mehr von angular/flex-layout.
Das Layout der Komponenten, bleibt weitestgehend erhalten.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
Bitte Testen.

**Comment by patrowe** [comment]
### Test für LUX-Snackbar:

**Testvorbedingungen:**
1. Die angehängten Zweige für die Lux-Components und das Lux-Components-Theme auschecken.
2. Das Theme lokal bauen und lokal mit den Components verlinken.
3. Die Demo starten und die Seite für die Lux-Snackbar öffnen.

**Testdurchführung:**
1. Auf den Button "Snackbar einblenden" klicken. -> Die Standardansicht einer Snackbar wird für die Desktopansicht rechtsbündig, für Mobile linksbündig, unterhalb des App-Headers angezeigt.
Desktop:
![Bildschirmfoto 2024-01-25 um 12 49 35](https://github.com/IHK-GfI/lux-components/assets/49644099/ef791747-eaae-4992-998d-e5c83d0e107f)
Mobil:
![Bildschirmfoto 2024-01-25 um 12 51 14](https://github.com/IHK-GfI/lux-components/assets/49644099/821d57f6-5df7-4505-b2ec-cbe22c742c6c)

3. Für die Properties "textColor", "iconColor" und "actionColor" jeweils eine andere Farbe auswählen und die Snackbar einblenden lassen. -> Die entsprechenden Farben werden für die einzelnen Elemente angezeigt. z.B.
![Bildschirmfoto 2024-01-25 um 12 54 47](https://github.com/IHK-GfI/lux-components/assets/49644099/3a3eb94c-8269-4dfb-acfc-0bba8460bc90)

4. In das Feld Text folgenden Text einfügen. "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor." -> Der Text bricht um und in der Mobilen Variante wird der rechte Rand nicht abgenschitten.
Desktop:
![Bildschirmfoto 2024-01-25 um 13 00 39](https://github.com/IHK-GfI/lux-components/assets/49644099/3d8d3ca8-faa7-4305-920c-7e036f75a0e3)
Mobil:
![Bildschirmfoto 2024-01-25 um 12 58 09](https://github.com/IHK-GfI/lux-components/assets/49644099/87560bb0-7851-4fe9-91a2-1a48cd36a842)

5. Die Property iconSize schrittweise erhöhen. -> Die Größe des Icons verändert sich entsprechend und das Icon wird immer vollständig angezeigt. Zum Vergleich
"1x":
![Bildschirmfoto 2024-01-25 um 13 03 35](https://github.com/IHK-GfI/lux-components/assets/49644099/67021d89-8fc7-4128-a092-e0962c3a39eb)
"2x": 
![Bildschirmfoto 2024-01-25 um 13 04 52](https://github.com/IHK-GfI/lux-components/assets/49644099/eafc8db2-4514-4972-8393-681e72060c14)
"3x": 
![Bildschirmfoto 2024-01-25 um 13 05 07](https://github.com/IHK-GfI/lux-components/assets/49644099/d02a7261-8ba3-44a9-9764-944a6e93a446)
"4x":
![Bildschirmfoto 2024-01-25 um 13 05 19](https://github.com/IHK-GfI/lux-components/assets/49644099/a5393626-9cf8-4e72-947c-ea36cdfb608d)
"5x": 
![Bildschirmfoto 2024-01-25 um 13 05 31](https://github.com/IHK-GfI/lux-components/assets/49644099/84b8d62d-f193-404c-812b-f9d0cbd9ef55)

**Comment by DSeifer** [comment]
### Lokaler Test
Unter Windows 10 Enterprise 22H2 (19045.3930) und MacOS 14.2.1 mit den jeweils aktuellen Browserversionen nachgetestet:

**LUX-Snackbar**
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK

**LUX-Dialog**
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK
