### ISSUE TITLE
lux-autocomplete: Filterfunktion für Optionen

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#40]
Die Komponente lux-autocomplete sucht aus einem Optionsarrays die zu einer Benutzereingabe passenden Optionen aus einem Optionsarrays und listet diese dem Benutzer in der UI als mögliche eingaben. Dabei sind die Optionen passend, die den Text der Benutzereingabe enthalten. 
Das Filtern der passenden Optionen aus dem Array aller Optionen geschieht in der Methode **_filter(filterTerm: any)_**:
![image](https://user-images.githubusercontent.com/72753526/97717682-5d3b9f00-1ac5-11eb-892b-44792b95bfea.png)

Es gibt Situationen in denen es hilfreich wäre, wenn der Benutzer die vorgeschlagenen Optionen selbst bestimmen könnte. Dies ließe sich mit einer eigenen Filterfunktion realisieren, die auf dem Array aller möglichen Optionen ausgeführt wird.

Es müsste ein neuer Input Parameter luxFilterFn eingeführt werden.
Ist dieser Wert nicht gesetzt, wird standardmäßig die bisherige Filterfunktion

`compareValue.trim().toLowerCase().indexOf(filterTerm.trim().toLowerCase()) > -1`

 in **_filter(filterTerm: any)_** ausgeführt.
Ist der Parameter gesetzt, wird die übergebene Filterfunktion zur Ermittlung der auswählbaren Optionen ausgeführt.

Vielen Dank und viele Grüße
Sascha Bülow

**Comment by thodic77** [comment]
Umgesetzt in der Version 10.2.0.
