### ISSUE TITLE
lux-app-footer: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#400]
In der Komponente lux-app-footer müssen die Befehle von angular/flex-layout ersetzt werden.

Akzeptanzkriterium:
Die oben genannte Komponente enthält keien Befehle mehr von angular/flex-layout.
Das Layout der Komponente, bleibt weitestgehend erhalten.

**Comment by patrowe** [comment]
### Test

**Test-Verbereitung**
1. Die Angehängten Zweige für das Lux-Components-Theme und die Lux-Components jeweils auschecken.
2. Das Theme lokal bauen und lokal mit den Components verlinken.
3. Das Demo starten und die Test-Seite für den App-Footer öffnen.

**Test-Durchführung**
1. Der Footer sollte wie folgt dargestellt werden und keinen horizontalen Scrollbalken anzeigen.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/5f9ffc09-ad5e-4d9a-87f6-2c70580a86d4)

2. Zur responsiven Ansicht wechseln und das Fenster langsam verkleinern. Zu erwartendes Ergebnis: Die Buttons rechts im Footer wechseln nach und nach in ein Menü, dafür erscheint das Menü-Icon als Button. 
![Screenshot 2024-01-04 135251](https://github.com/IHK-GfI/lux-components/assets/49644099/923a976d-9b51-41f6-b562-08922b7acbd6)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3803) und MacOS 14.2.1 mit den jeweils aktuellen Browserversionen nachgetestet:
MacOS:
Safari, Firefox, Chrome -> OK
Windows:
Edge, Firefox, Chrome -> OK
