### ISSUE TITLE
lux-file-preview: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#401]
In der Komponente lux-file-preview müssen die Befehle von angular/flex-layout ersetzt werden.

Akzeptanzkriterium:
Die oben genannte Komponente enthält keien Befehle mehr von angular/flex-layout.
Das Layout der Komponente, bleibt weitestgehend erhalten.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
@DSeifer bitte testen.

**Comment by patrowe** [comment]
### Test

**Testvorbedingung:**
- Die angehängten Zweige für die Lux-Components und das Lux-Components-Theme auschecken
- Das Theme lokal bauen und lokal mit den Components verlinken
- Je eine PDF-Datei, TXT-Datei und JPG-Datei für die Tests bereitlegen.
- Das Demo starten und mit die Seite für die LUX-File-List öffnen
- Auf das Upload-Symbol in der rechten oberen Ecke klicken und die pdf, txt und jpg-Datei auswählen und hochladen
<img width="430" alt="Bildschirmfoto 2024-01-31 um 09 57 48" src="https://github.com/IHK-GfI/lux-components/assets/49644099/266671e4-4d0d-4961-9491-fc834d939684">

**Testdurchführung:**
_1. Ansicht einer TXT-Datei:_ 
<img width="546" alt="Bildschirmfoto 2024-01-31 um 10 05 26" src="https://github.com/IHK-GfI/lux-components/assets/49644099/0cf35431-0b2f-405f-864f-6450795b2e14">

-über das Vorschau-Icon (Auge) die Vorschau öffnen. Zu erwartendes Ergebnis:  das Format wird in der Demo nicht unterstützt und statt einer Vorschau wird folgende Nachricht angezeigt.
<img width="361" alt="Bildschirmfoto 2024-01-31 um 10 07 59" src="https://github.com/IHK-GfI/lux-components/assets/49644099/732d91f9-51bd-4069-9b47-e0becbe6cd22">

_2. Ansicht einer PDF-Datei:_
- die Vorschau für die Pdf-Datei öffnen. Zu erwartendes Ergebnis: Die Datei wird angezeigt, über das Select-Feld in der Werkzeugleiste kann die Vorschau verkleinert und vergrößert werden.
<img width="1218" alt="Bildschirmfoto 2024-01-31 um 10 18 22" src="https://github.com/IHK-GfI/lux-components/assets/49644099/e6d6b76d-e22b-415c-ac46-cd2385555bdb">

- Das Browserfenster verkleinern Zu erwartendes Ergebnis:  Der Dateiname wird ab einer bestimmten Größe automatisch abgekürzt. Bei noch kleinerem Format wird er ausgeblendet.
<img width="669" alt="Bildschirmfoto 2024-01-31 um 10 19 07" src="https://github.com/IHK-GfI/lux-components/assets/49644099/d77168bb-6fe9-4953-9226-10f7ac912ed7">

_3. Ansicht einer JPG-Datei_ 
-die Vorschau für die jpg-Datei öffnen. Zu erwartendes Ergebnis: Das Bild wird angezeigt, über die Buttons in der Werkzeugleiste kann die Vorschau verkleinert und vergrößert werden.
<img width="669" alt="Bildschirmfoto 2024-01-31 um 10 21 21" src="https://github.com/IHK-GfI/lux-components/assets/49644099/be381f47-0abf-4f37-9c3b-ed306acd8525">

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3930) und MacOS 14.3 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
