### ISSUE TITLE
lux-error-page: Austausch von Flex-Layout

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#402]
Aus der Komponente lux-error-page müssen die Befehle von angular/flex-layout ersetzt werden.

Akzeptanzkriterium:
Die oben genannte Komponente enthält keine Befehle mehr von angular/flex-layout.
Das Layout der Komponente, bleibt weitestgehend erhalten.

**Comment by patrowe** [comment]
Die Anforderungen wurden umgesetzt.
@DSeifer Bitte Testen.

**Comment by patrowe** [comment]
### Test:

**Testvorbedingungen**

1. Die Branches für die die Components und das Theme auschecken.
2. Das Theme lokal bauen und lokal mit den Components verlinken
3. Das Demoprogramm starten und die Seite für "lux-Error-page" öffnen.

**Testdurchführung:**

Die Error-Komponente durch klick auf den Button öffnen (am unteren Rand der Seite)
Ansicht prüfen, die Elemente sollen horizontal zentriert angezeigt werden.
![Bildschirmfoto 2024-02-13 um 16 35 34](https://github.com/IHK-GfI/lux-components/assets/49644099/e9ca8f3b-09c9-4f99-9e8b-0345252ffa0f)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4046) und MacOS 14.3 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Firefox -> OK

Windows:
Edge -> OK
Firefox -> OK
