### ISSUE TITLE
lux-file-preview: Timer bei nicht anzeigbaren Dateien ist nicht accessible

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#411]
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/9ff46c6d-b91c-4e69-9b3c-a34d68a5b7d6)
Wird eine Datei in einem nicht unterstützten Format hochgeladen, wird eine entsprechende Nachricht angezeigt. Zusätzlich läuft ein Timer von 5 Sekunden, nach dessen Ablauf die Datei automatisch heruntergeladen wird.
Dieses entspricht nicht den WCAG-Kriterien und muss geändert werden. 

Empfohlen: Den Button zum direkten Download der Datei ohne Timer anzeigen. Den Text der Nachricht anpassen:
Das Dateiformat wird nicht unterstütz. Für eine Ansicht bitte herunterladen und mit einem geeigneten Programm öffnen.

**Comment by patrowe** [comment]
### Test

**Vorbedingung:**

- Den angehängten Zweig für die Lux-Components auschecken.
- Die Demo lokal starten und die Seite für die Lux-File-List öffnen

**Durchführung**
- eine nicht unterstützte Datei (z.B. .doc, .docx) hochladen
- die Preview über das Augensymbol öffnen.

**Zu erwartendes Ergebnis:**
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/afc3ce55-2c31-49b5-98eb-c2c95e224933)
Der Dialog wird angezeigt, der Download erfolgt nicht mehr automatisch nach einer kurzen Zeitspanne.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4170) und MacOS 14.4.1 mit den jeweils aktuellen Browserversionen getestet:

Windows: Edge -> OK
MacOS: Safari -> OK
