### ISSUE TITLE
lux-file-list: Die Error-Mesage ist nicht Accessible

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#414]
Die Fehlermeldung in der File-List muss gemäß der anderen Formcontrols angepasst werden. (Hellroter Hintergrund und Dunkelrote Schriftfarbe)

<img width="565" alt="Bildschirmfoto 2024-01-31 um 09 38 05" src="https://github.com/IHK-GfI/lux-components/assets/49644099/0f8f0497-95cb-42c9-88bc-b92f8d289993">

**Comment by patrowe** [comment]
Die Anforderungen wurden zusammen mit Issue #419 umgesetzt.

@DSeifer Bitte testen.

**Comment by patrowe** [comment]
### Test

**Vorbedingung:**
- Den angehängten Zweig für die Lux-Components auschecken.
- Die Demo lokal starten und die Seite für die Lux-File-List öffnen

**Durchführung**
- die Datei "example.png" aus der Beispielkomponente löschen
- die Property "luxRequired" auf true setzen
![Screenshot 2024-03-20 144614](https://github.com/IHK-GfI/lux-components/assets/49644099/75c2c5c2-5709-489c-8d12-afa7bb1f428d)

Zu erwartendes Ergebnis:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/9cf24bd1-b1dc-450d-bcc4-86b0ba11beaf)

- Eine Datei mit mehr als 5MB Dateigröße hochladen

Zu erwartendes Ergebnis:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/af0b81f1-4cb5-403a-8a7b-e6b9bfdd0758)
(Zusätzlich erscheint das X in der Fehlermeldung)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4170) und MacOS 14.4 mit den jeweils aktuellen Browserversionen getestet:

Windows: Edge -> OK
MacOS: Safari -> OK
