### ISSUE TITLE
Stroked rounded Buttons

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#415]
Guten Morgen zusammen,

momentan ist es nicht möglich runde Lux-Buttons ohne Hintergrundfarbe zu erstellen. die Eigenschaft luxStroked scheint auch nicht zu funktionieren mit runden Buttons. Ich würde gerne einen runden Button mit Icon erstellen, der eine Outline aber keinen Hintergrund hat. Beispiel dafür gibt es in den Lux Components schon beim Lux-Master-Detail-Ac, dort gibt es einen Button um die Seitenleiste zu minimieren, der exakt so aussieht wie ich es brauche (siehe Screenshot). Außerdem wäre es schön wenn ich die Größe von Buttons mit Icons skalieren könnte, da wir z.B. bei lux-menu das Problem haben, dass die Anwender den Button nicht finden, weil er zu klein ist. Icons selbst, kann man schon schön skalieren, allerdings halt nicht eingebettet in Buttons.

Viele Grüße
Florian

![image](https://github.com/IHK-GfI/lux-components/assets/48916130/38282f72-2893-4287-897c-b4395d388196)

**Comment by patrowe** [comment]
### Test

**Testvorbedingung**
1. Die Zweige für die Lux-Components und das Lux-Components-Theme auschecken.
2. Das lux-components-theme lokal bauen und lokal mit den lux-components verlinken.
3. Das Demo-Programm starten und die Seite für die Buttons öffnen.
4. Die folgenden Tests müssen sowohl für das Theme-Authentic, als auch für das Theme-Green durchgeführt werden.

**Testdurchführung**
**1. Die Default-Ansicht für die neuen Buttons ist**
Theme Authentic:
![example6](https://github.com/IHK-GfI/lux-components/assets/49644099/1a77ed50-dbea-4a59-8a81-80fe51212a11)

Theme Green:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/09215b43-ae87-430f-8a32-8ceee9d201d0)

**2. "disabled":** unter Konfiguration die Buttons auf Disabled setzen. Zu erwartendes Ergeignis:
Theme Authentic:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/8b8f5884-8423-49cc-bd25-eba6e1bb09c6)

Theme Green:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/ea17bc26-cce6-43a9-beaa-26fecf7ad0ae)

**3. "hover":** mit der Maus über die einzelnen Buttons hovern. Zu erwartendes Ergeignis:
Theme Authentic: Das Icon des Buttons wird jeweils 2 Stufen heller.

Theme Green: Der Hintergrund des Buttons erscheint in der hellblauen Hover-Farbe.

**4. "focus-visible":** mit dem Tab-Key durch die Beispiel-Buttons tabben. Zu erwartendes Ereignis:
Theme Authentic:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/2a10e84d-5bd1-4d8a-a6e3-924f9c106a70)

Theme Green:
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/c0b5e082-d326-45c1-9d03-c424dd1c52e6)

**5. "mouse-click":** die Buttons einmal anklicken. Zu erwartendes Ereignis:
Theme-Authentic: Das Icon des Buttons wird jeweils 2 Stufen dunkler.
Theme-Green:  Die Buttons erhalten einen Schatten und werden damit optisch erhöht.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.3930) und MacOS 14.3 mit den jeweils aktuellen Browserversionen getestet:

*MacOS:*
Safari -> OK
Disabled im Green-Theme ist allerdings komplett grau:
![image](https://github.com/IHK-GfI/lux-components/assets/75263741/c83bcdf6-aad7-4f8b-a4b8-135543f720ce)

*Windows:*
Edge -> OK
Disabled im Green-Theme ist allerdings komplett grau:
![image](https://github.com/IHK-GfI/lux-components/assets/75263741/c83bcdf6-aad7-4f8b-a4b8-135543f720ce)
