### ISSUE TITLE
lux-progress: Aria-Label für Progress Bar

### ISSUE THREAD

**Issue by JWoesteSN** [IHK-GfI/lux-components#416]
WCAG Success Criterion 4.1.2 Name, Role, Value

Progressbars müssen einen (für assistive Technologien) erkennbaren Namen haben. 
Bei lux-progress gibt es keine Möglichkeit, für diese ein aria-label zu setzen.

**Comment by thodic77** [comment]
Dies ist möglich, bitte die Directive _luxAriaLabel_ verwenden.

Hier ist die Dokumentation: https://github.com/IHK-GfI/lux-components/wiki/luxarialabel

```html
<lux-progress luxAriaLabel="aaaa" ...></lux-progress>
```

Über das Attribut _luxAriaLabelSelector_ kann gesteuert werden, an welches Tag das Aria-Label gehangen werden soll. 

```html
<lux-progress luxAriaLabel="aaaa" luxAriaLabelSelector="mat-progress-bar" ...></lux-progress>
```

Sollte dies nicht die Lösung sein, bitte bei mir melden.
