### ISSUE TITLE
Das Theme soll um weitere Styling-Klassen ergänzt werden

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#418]
Analog zu den neuen Layout-Klassen für flex-basis, sollen entsprechende Klassen für Width, Max-Width und Min-Width ergänzt werden.
Die neue Klasse lux-container soll responsiv werden, dh. für die unterschiedlichen breakpoints. soll die Max-Width angepasst werden. Zusätzlich soll es eine Klasse lux-container-max geben, die die max-width auf 100% setzt und nur ein minimales margin/padding für den Rand setzt.

**Comment by patrowe** [comment]
Die Anforderungen wurden im lux-components-theme umgesetzt.

**Comment by thodic77** [comment]
Code-Review erfolgreich durchgeführt.
