### ISSUE TITLE
Fehlerhafte Aria-Referenz bei den lux-Form-controls

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#419]
Dieses ist ein Sammelticket für die Form-Controls, für "kleinere" Fehler im Layout.
- lux-input-ac mit type=time: das Icon für die Uhr ist zu klein.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/5caf229a-be8c-4d47-afc8-2f50076e5436)

- die Schriftgröße der Labels muss überprüft werden (dazu gab es Rückfragen, Schrift wurde als zu klein empfunden)

- Die Aria-Referenzen für das label überprüfen und evtl. fixen
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/1e146f4b-cf3f-4521-bf11-d1f1b9df9022)

**Comment by patrowe** [comment]
Die Prüfung hat ergeben, dass die Labels in den Formcontrols eine berechnete Größe von 12px haben. Im Zuge der Umstellung auf relative Schriftgrößen wird die Einheit entsprechend ausgetauscht. Dann kann die Größe der Labels über Browsereinstellungen angepasst werden.
Vgl. https://github.com/IHK-GfI/lux-components/issues/362

**Comment by patrowe** [comment]
Die Anforderungen wurden umsetzt.

@DSeifer bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4170) und MacOS 14.4 mit den jeweils aktuellen Browserversionen getestet:

Windows: Edge -> OK
MacOS: Safari
Der Text unter dem Toggle "luxRequired" wird immer vorgelesen. -> OK
Der Fehlertext wird bei den meisten Komponenten aber erst vorgelesen, wenn das fehlerhafte Feld erneut den Fokus erhält. Beim Verlassen des fehlerhaften Feldes wird nur der Text des als nächsten angesprungenen Feldes vorgelesen. Ist das so gewollt?

**Comment by patrowe** [comment]
Ja, das ist ein gewolltes Verhalten. Die Errormessage hat das Attribute "polite" und unterbricht deshalb nicht die aktuellen Ansagen. Daher, wird der Fehler in dieser Situation erst vorgelesen, wenn das entsprechende Form-Control den Focus zurückbekommt.
