### ISSUE TITLE
fxLayout aus der Demo entfernen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#421]
Im Rahmen dieses Vorgangs soll die Abhängigkeit zu @angular/flex-layout aus der Demo entfernt werden.

### Akzeptanzkriterien

- Alle Abhängigkeiten zu @angular/flex-layout wurden aus der Demo entfernt .

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4046) und MacOS 14.3.1 mit den jeweils aktuellen Browserversionen getestet:

MacOS: Safari
Windows: Edge

Der oben beschriebene Fehler bei den Chips im Filter war ein Missverständnis. -> OK
Der kaputte Button im Storage wurde gefixed. -> OX
Der Label-Abstand bei Checkbox-Container AC muss mit @patrowe abgestimmt werden, wird hier aber nicht näher betrachtet. -> OK
