### ISSUE TITLE
Lookup-Label geht kaputt wenn Null-Werte abgefragt werden

### ISSUE THREAD

**Issue by schoflo** [IHK-GfI/lux-components#424]
Wenn das LookupLabel initial versucht, eine Tabelle mit Knr=null/undefined abzurufen geht sie kaputt. Wenn ich zu einem späteren Zeitpunkt die Kammernummer setze bleibt sie funktionslos. Ich hätte gedacht, dass entweder bei Aufrufen mit Knr=null gar nichts passiert. Oder alternativ, dass bei knr=null ein Error geworfen wird, die Komponente aber nach Setzen der Knr wieder funktioniert.

Reproducer:

HTML
`  <lux-lookup-label luxLookupId="beispiel" [luxLookupKnr]="temp" luxTableNo="1002" luxTableKey="4" luxBezeichnung="lang">
  </lux-lookup-label>`

TS
`  ngOnInit(): void {
    setTimeout(() => {
      this.temp = 101;
    }, 3000);
  }`

**Comment by DSeifer** [comment]
Bitte um direkte Kontaktaufnahme.

**Comment by thodic77** [comment]
Der Fehler wurde gefixt. 

### Test

- Die Demoseite "Lookup-Label" öffnen. 
- Die Kammernummer wird initial nicht mehr gesetzt, sondern erst nach 5 Sekunden (siehe Progress). 
  
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/592f2013-f713-4c0d-b30a-675a97d43939)

- Prüfen, ob nach 5 Sekunden die Kammernummer und das Label erscheint.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4046) und MacOS 14.3.1 mit den jeweils aktuellen Browserversionen und beiden Themes getestet:

MacOS: Safari
Windows: Edge

- Die Kammernummer wird initial nicht mehr gesetzt, sondern erst nach 5 Sekunden -> OK
