### ISSUE TITLE
Optik Badge-Notification verbessern

### ISSUE THREAD

**Issue by tlandgraf** [IHK-GfI/lux-components#43]
Heute ist die Optik der Badge-Notification wie folgt:
<img width="374" alt="heute2" src="https://user-images.githubusercontent.com/74006133/98256756-3d055780-1f7f-11eb-9b28-78b37c3d81e3.png">
<img width="395" alt="heute" src="https://user-images.githubusercontent.com/74006133/98256760-3e368480-1f7f-11eb-9937-fe8b13746ca8.png">

Verbesserungsmöglichkeiten:
- visuelle Abgrenzung von Badge zu Hintergrundobjekt (das, wo der Badge dranbleibt) schaffen
- Default-Color von "weiß" auf eine andere Solid-Farbe wechseln, die dann auch die visuelle Abgrenzung hat

Beispiel "Xing", wo diese Verbesserungen umgesetzt wurden:
<img width="226" alt="xing" src="https://user-images.githubusercontent.com/74006133/98257044-83f34d00-1f7f-11eb-9a6e-95794165bac1.png">

**Comment by thodic77** [comment]
Die Anforderung wird mit der Version 11.0.0 ausgeliefert. 

Beispiel 1: Buttons, Icons und Text
![image](https://user-images.githubusercontent.com/32597554/101895963-8a8d6980-3ba8-11eb-9bfb-aad7303b4a58.png)

Beispiel 2: Tabs
![image](https://user-images.githubusercontent.com/32597554/101895973-8e20f080-3ba8-11eb-8f54-fe0ddf360a18.png)

Beispiel 3: Kacheln
![image](https://user-images.githubusercontent.com/32597554/101896059-adb81900-3ba8-11eb-9975-7fafb8e56f79.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet in folgenden Browsern unter Windows 10:
- Edge: OK
- Chrome: OK
- Firefox: OK
- Opera: OK

Getestet in folgenden Browsern unter Mac OS 11.0.1:
- Safari: OK
- Chrome: OK
- Firefox: OK
