### ISSUE TITLE
lux-lookup-combobox interpretiert noch gültige Einträge als ungültig

### ISSUE THREAD

**Issue by taubec** [IHK-GfI/lux-components#431]
Ist bei einem Schlüsseltabelleneintrag ein GültigBis eingetragen, welches noch nicht erreicht ist, interpretiert die Komponente lux-lookup-combobox-ac diesen trotzdem als ungültig.

Umgebung: ENTW
Schlüsseltabelle: 1096 (Verwendungszweck Telekom)
Schlüssel: 001077 - gültig bis zum 5.3.2024, als ungültig interpretiert am 28.2.2024.

Folgender Code in der Datei lux-lookup-component.ts dürfte so auch nicht funktionieren:
` if (entry.gueltigkeitBis) {
          isUngueltig = Date.now() > +entry.gueltigkeitBis;
 `

Wobei das Datum 99.99.9999 anscheinend vorher schon als null oder undefined zurück geliefert wird.
![falscheUngueltigInterpretation](https://github.com/IHK-GfI/lux-components/assets/81471669/bf5f165a-fd8c-49f3-923c-c19fcb0a041d)

**Comment by taubec** [comment]
Die Markierung in der Combobox folgte anhand dieser Konfiguration:
`behandlungUngueltige: LuxBehandlungsOptionenUngueltige = LuxBehandlungsOptionenUngueltige.ausgrauen;`

Noch mal eine kurze Erklärung zum erwähnten Code-Schnippsel: 
Date.now() liefert Millisekunden, entry.gueltigkeitBis dürfte vom Format aber yyyymmtt sein. Als Zahl interpretiert auf jeden Fall immer kleiner.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

### Test

- In der Datei "_src\app\demo\components-overview\lookup-examples\mock-result.ts_" verschiedene Daten (Format yyyymmdd) für _gueltigkeitVon_ und _gueltigkeitBis_ eintragen.
- Die Demo bauen und starten.
- Die Seite "Lookup-Combobox-Authentic" öffnen.
- Prüfen, ob die ungültigen Einträge korrekt in rot dargestellt werden. 

In der aktuellen Demo sind z.B. Bellux (wegen Gültigkeit in der Vergangenheit) und Niederlande (wegen Gültigkeit in der Zukunft) rot dargestellt.

![image](https://github.com/IHK-GfI/lux-components/assets/32597554/61f41713-94ab-4347-8be1-d3e2b118a029)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4046) und MacOS 14.3.1 mit den jeweils aktuellen Browserversionen getestet:

MacOS: Safari -> OK
Windows: Edge -> OK
