### ISSUE TITLE
lux-tenant-logo: Redundanter Code und einstellbare Höhe

### ISSUE THREAD

**Issue by BeckerJu** [IHK-GfI/lux-components#435]
Redundanter Code im lux-app-header-ac, welcher in die Komponente lux-tenant-logo ausgelagert wurde, sorgt jetzt dafür, dass die Höhe der Komponente in manchen Fällen nicht gesetzt wird.

Akzeptanzkriterien:
- Der entsprechende redundante Code wird entfernt und alle Funktionalitäten der Komponente werden erfolgreich nachgewiesen

**Comment by thodic77** [comment]
Test und Code-Review erfolgreich durchgeführt.
