### ISSUE TITLE
lux‐app‐footer Buttons sollen Tooltips anzeigen können

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#44]
Ein normaler lux-button kann über die Directive "luxTooltip" einen Tooltip angehängt bekommen. Bei den Buttons, die über den lux-app-footer angebunden werden, geht das aktuell nicht. 

Es wäre super, wenn man über einen Parameter in den LuxAppFooterButtonInfo noch einen Tooltip übergeben könnte, der dann analog zum normalen Button im Footer angezeigt wird.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

![image](https://user-images.githubusercontent.com/32597554/99378934-52a44680-28c8-11eb-89dc-15c5cee3fdf1.png)
