### ISSUE TITLE
MDC-Migration: @angular/material/button

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#443]
Art: Style changes, API changes
Anleitung: https://v17.material.angular.io/guide/mdc-migration#button

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseiten "Button", "Link" und "Link-Plain" auf dem Zweig öffnen.
- Die Demoseiten "Button", "Link" und "Link-Plain" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Ein paar Pixel- und Focusunterschiede gibt es. Die Änderungen kommen mit Angular und wurden für gut befunden.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

**MacOS: Safari**
-> Button: Umrandung erster kreisförmiger Button ist lokal schwarz und in der Demo grau. 
-> Link: OK
-> Link-Plain: OK 

**Windows: Edge**
-> Button: Umrandung erster kreisförmiger Button ist lokal schwarz und in der Demo grau. 
-> Link: OK
-> Link-Plain: OK

**Comment by thodic77** [comment]
Die Umrandung wurde angepasst. Die Umrandung ist etwas kräftiger als in v16, aber nicht mehr fast schwarz.

@DSeifer: Bitte nachtesten.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

**MacOS: Safari**
-> Button: OK

**Windows: Edge**
-> Button: OK 
Interessanter Weise fällt der Unterschied nun unter Windows deutlicher ins Gewicht als unter MacOS.
