### ISSUE TITLE
MDC-Migration: @angular/material/chips

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#446]
Art: Complete rewrite
Anleitung: https://v17.material.angular.io/guide/mdc-migration#chips

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Chips" auf dem Zweig öffnen.
- Die Demoseite "Chips" auf dem Zweig "Issue_448-mdc-migration-angularmaterialform-field" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Ein paar Pixel- und Focusunterschiede gibt es. 

@DSeifer:  Bitte testen.

**Comment by DSeifer** [comment]
### Test unter Windows 11 (19045.4780) und MacOS 14.6.1

**MacOS / Safari:**
- Die Chips sind nun länger, ansonsten ok

**Windows / Edge:**
- Die Chips sind nun länger, ansonsten ok
