### ISSUE TITLE
MDC-Migration: @angular/material/dialog

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#447]
Art: Style changes, changes to change detection behavior
Anleitung: https://v17.material.angular.io/guide/mdc-migration#dialog

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test

- Die Demoseite "Dialog" auf dem Zweig öffnen.
- Die Demoseite "Dialog" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

MacOS: Safari
-> Dialog: OK

Windows: Edge
-> Dialog: OK
