### ISSUE TITLE
MDC-Migration: @angular/material/input

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#449]
Art: Style changes only
Anleitung: https://v17.material.angular.io/guide/mdc-migration#input

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Input" auf dem Zweig öffnen.
- Die Demoseite "Input" auf dem Zweig "Issue_448-mdc-migration-angularmaterialform-field" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Ein paar Pixel- und Focusunterschiede gibt es. 

@DSeifer:  Bitte testen.

**Comment by DSeifer** [comment]
### Test unter Windows 11 (19045.4780) und MacOS 14.6.1

**MacOS / Safari:**
- ok

**Windows / Edge:**
- Das Grau ist etwas dunkler, ansonsten ok
