### ISSUE TITLE
MDC-Migration: @angular/material/list

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#450]
Art: Style changes, API changes
Anleitung: https://v17.material.angular.io/guide/mdc-migration#list

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Tabs" auf dem Zweig "v17-alpha" öffnen.
- Die Demoseite "Tabs" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Ein paar Pixel- und Focusunterschiede gibt es. Die Änderungen kommen mit Angular und wurden für gut befunden.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
### Test unter MacOS 14.6.1 im aktuellen Safari und unter Windows 10 (22H2 / 190445.4780) im aktuellen Edge

1. Die Demoseite "List" auf dem Zweig geöffnet.
2. Die Demoseite "List" in der zentralen Demo geöffnet.
3. Es sind keine funktionalen Unterschiede feststellbar, bis auf ein paar Pixel- und Focusunterschiede.
