### ISSUE TITLE
MDC-Migration: @angular/material/menu

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#451]
Art: Style changes, API changes
Anleitung: https://v17.material.angular.io/guide/mdc-migration#menu

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test

- Die Demoseite "Menu" auf dem Zweig öffnen.
- Die Demoseite "Menu" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. 
  Anmerkung: Menüitems können jetzt mehrzeilig sein und werden nicht länger abgeschnitten.
  Vorher:
  ![image](https://github.com/user-attachments/assets/80b89d7a-8e05-4768-80d9-ae721a30e1a4)

  Nachher:
  ![image](https://github.com/user-attachments/assets/2829467c-1962-4854-a53e-71962d23a3b3)


@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
**Test unter Windows 10 (19045.4780) und MacOS 14.6.1**
**Win/Edge:** Soweit ok, lange Labels werden nicht mehr abgeschnitten, sondern umgebrochen. Aber wie im Screenshot zu sehen ist, wird die Höhe nicht automatisch angepasst, sodass der Menüeintrag nun oben und unten ggf. abgeschnitten ist.
![image](https://github.com/user-attachments/assets/4c9677a7-2ac4-4964-9857-4838e1afd1a6)

**MacOS/Safari:** Auch soweit ok, aber gleiches Problem wie unter Windows nur nicht so stark ausgeprägt.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 
@DSeifer: Bitte nachtesten.

**Comment by DSeifer** [comment]
**Test unter Windows 10 (19045.4780) und MacOS 14.6.1**
**Win/Edge:** OK

**MacOS/Safari:** OK
