### ISSUE TITLE
MDC-Migration: @angular/material/paginator

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#452]
Art: Style changes only
Anleitung: https://v17.material.angular.io/guide/mdc-migration#paginator

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Table" auf dem Zweig öffnen.
- Die Demoseite "Table" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Die Abstände sind größer zwischen den Elementen.
-  Es gibt auch bei den Demoseiten "HTTP-Error" und "Message-Box" (ab 11 Nachrichten) eine Paging-Anzeige.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
**Test unter Windows 10 (19045.4780) und MacOS 14.6.1**
**Win/Edge:** 
- Die Demoseite "Table" auf dem Zweig geöffnet.
- Die Demoseite "Table" auf dem Zweig "master" geöffnet.
- Geprüft, dass es keine funktionalen Unterschiede gibt. -> OK
- Größere Abstände zwischen den Elementen wurden nicht bewusst wahrgenommen. -> OK
- Bei der Demoseite "HTTP-Error" gibt es bereits im Master eine Paging-Anzeige. -> ???
- Bei der Demoseite "Message-Box" gibt es jetzt eine Paging-Anzeige, wenn luxMaximumDisplayed überschritten wird. -> OK

**MacOS/Safari:** ^
- Die Demoseite "Table" auf dem Zweig geöffnet.
- Die Demoseite "Table" auf dem Zweig "master" geöffnet.
- Geprüft, dass es keine funktionalen Unterschiede gibt. -> OK
- Größere Abstände zwischen den Elementen wurden nicht bewusst wahrgenommen. -> OK
- Bei der Demoseite "HTTP-Error" gibt es bereits im Master eine Paging-Anzeige. -> ???
- Bei der Demoseite "Message-Box" gibt es jetzt eine Paging-Anzeige, wenn luxMaximumDisplayed überschritten wird. -> OK
