### ISSUE TITLE
MDC-Migration: @angular/material/progress-bar

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#453]
Art: Style changes only
Anleitung: https://v17.material.angular.io/guide/mdc-migration#progress-bar

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Progress" auf dem Zweig öffnen.
- Die Demoseite "Progress" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

**MacOS: Safari**
-> Progress: OK
Die Laufgeschwindigkeit der Progressbar bei luxMode "indeterminate" ist lokal deutlich schneller.

**Windows: Edge**
-> Progress: OK
Die Laufgeschwindigkeit der Progressbar bei luxMode "indeterminate" ist lokal deutlich schneller.
