### ISSUE TITLE
MDC-Migration: @angular/material/progress-spinner

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#454]
Art: Style changes only
Anleitung: https://v17.material.angular.io/guide/mdc-migration#progress-spinner

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Spinner" auf dem Zweig öffnen.
- Die Demoseite "Spinner" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

MacOS: Safari
-> Spinner: OK
Die Laufgeschwindigkeit des Spinner bei luxMode "indeterminate" ist lokal deutlich schneller.

Windows: Edge
-> Spinner: OK
Die Laufgeschwindigkeit der Spinner bei luxMode "indeterminate" ist lokal deutlich schneller.
