### ISSUE TITLE
MDC-Migration: @angular/material/snack-bar

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#459]
Art: Style changes, API changes
Anleitung: https://v17.material.angular.io/guide/mdc-migration#snack-bar

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

# Test
Die Demoseite "Snackbar" auf dem Zweig öffnen.
Die Demoseite "Snackbar" auf dem Zweig "master" öffnen.
Prüfen, dass es keine funktionalen Unterschiede gibt. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

MacOS: Safari
-> Snackbar: Die Darstellung der Snackbar ist lokal breiter als zentral.

Windows: Edge
-> Snackbar: Die Darstellung der Snackbar ist lokal breiter als zentral.

![Snackbar zentral](https://github.com/user-attachments/assets/e932b560-9280-4c0a-86a7-ff2c9b371ae7)
![Snackbar lokal](https://github.com/user-attachments/assets/1db32276-81c1-4071-bbee-1d25cee85f40)

**Comment by thodic77** [comment]
Die minimale Größe wurde angepasst. 

@DSeifer: Bitte nachtesten.

**Comment by DSeifer** [comment]
Test unter Windows 10 (19045.4780) und MacOS 14.6.1 mit den jeweils aktuellen Browserversionen durchgeführt.

MacOS: Safari
-> Snackbar: OK

Windows: Edge
-> Snackbar: OK
