### ISSUE TITLE
lux-filter-form sollte auch die Lookup-Module unterstützen

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#46]
Das Lux-Filter-Form unterstützt aktuell nur einen Teil der LUX-Input Felder. Akut fehlt uns die Unterstützung der Lookup-Module, insbesondere 

- lux-lookup-autocomplete
- lux-lookup-combobox

Aktuell kann beim Verwenden dieser Module in einem lux-filter-form der value in dem lux-filter-form nicht ermittelt werden, so dass die Verarbeitung in einen Fehler läuft.

**Comment by thodic77** [comment]
![image](https://user-images.githubusercontent.com/32597554/101478326-cf1ec800-3950-11eb-9d3f-e701dbb68dca.png)


Bitte den Test übernehmen.

**Comment by DSeifer** [comment]
**Getestet unter Windows 10**
Firefox: OK
Chrome: OK
Edge: OK
Opera: OK

**Getestet unter MacOS 11.0.1**
Safari: OK
Firefox: OK
Chrome: OK
