### ISSUE TITLE
MDC-Migration: @angular/material/table

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#460]
Art: Style changes only
Anleitung: https://v17.material.angular.io/guide/mdc-migration#table

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

### Test
- Die Demoseite "Table" und "Table-Server" auf dem Zweig öffnen.
- Die Demoseite "Table" und "Table-Server" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Ein paar Pixel- und Focusunterschiede kann es geben. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
**Test unter MacOS 14.6.1 im aktuellen Safari und unter Windows 10 (22H2 / 190445.4780) im aktuellen Edge**

1. Die Demoseite "Table" auf dem Zweig geöffnet.
2. Die Demoseite "Table" in der zentralen Demo geöffnet.
3. Es sind keine funktionalen Unterschiede feststellbar, bis auf ein paar Pixel- und Focusunterschiede.
