### ISSUE TITLE
MDC-Migration: @angular/material/tabs

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#461]
Art: Style changes, API changes
Anleitung: https://v17.material.angular.io/guide/mdc-migration#tabs

**Comment by thodic77** [comment]
Die MDC-Migration wurde erfolgreich durchgeführt.

Vereinheitlichung: Die Property "luxTabAnimationActive" wurde entfernt, damit sich alle Tabs gleich verhalten. In einem Major-Update darf man schnittstellenbrechende Änderungen vornehmen.

### Test
- Die Demoseite "Tabs" auf dem Zweig "v17-alpha" öffnen.
- Die Demoseite "Tabs" auf dem Zweig "master" öffnen.
- Prüfen, dass es keine funktionalen Unterschiede gibt. Ein paar Pixel- und Focusunterschiede gibt es. Die Änderungen kommen mit Angular und wurden für gut befunden.

@DSeifer:  Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 getestet:

MacOS Safari: OK
Windows Edge: OK
