### ISSUE TITLE
Lux-App-Header Navigations Menü rückt nach

### ISSUE THREAD

**Issue by TheLethalGoose** [IHK-GfI/lux-components#463]
Wenn im Lux-App-Header Navigations luxHideAppLogo auf true gesetzt wird, rutscht das Navigations Menü in die Mitte und ist nicht mehr, wie üblich, rechts.

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

### Test

- In der Datei _app.component.html_ die folgenden Attribute im _lux-app-header-ac_ setzen: 
   `<lux-app-header-ac  [luxHideBrandLogo]="false" [luxHideAppLogo]="true" ...`
- Alle Kombinationen der beiden Attribute inklusive der mobilen Ansicht testen.
- Prüfen, ob das Menü an der korrekten Position angezeigt wird.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4291) und MacOS 14.4.1 mit den jeweils aktuellen u.a. Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
