### ISSUE TITLE
luxTitleTooltip und luxSubTitleTooltip

### ISSUE THREAD

**Issue by itodigital** [IHK-GfI/lux-components#465]
In LuxMasterListAcComponent sind sowohl luxTitleProp als auch luxSubTitleProp als 'string' und nicht als 'TemplateRef<any>' definiert und kann dafür dementsprechend kein ToolTip erstellt werden, wie die anderen Attributen. wie z.b. 'contentTempRef'. 
gewünscht sind die Properties 'luxTitleTooltip' und 'luxSubTitleTooltip', um ein ToolTip für den Titel und den SubTitel zu ermöglichen.

**Comment by DSeifer** [comment]
Für evtl. fachliche Rückfragen wäre es schön einen Kontaktkanal ausserhalb von Github zu haben. Hierfür ist aber zumindest ein Klarname erforderlich. Ich bitte um eine kurze persönliche Nachricht (z.B. Teams) wer "itodigital" ist.

**Comment by thodic77** [comment]
Die Properties wurde eingeführt, so dass man einen Tooltip für den Title und Subtitle setzen kann. 

### Test

Master-Detail-Ac

- Die Demoseite "Master-Detail-Ac" öffnen.
- Mit der Maus für den Titel und Subtiteln der Liste schweben.
- Prüfen, ob ein Tooltipp mit dem Präfix "Tooltip: ..." angezeigt wird.

Card

- Die Demoseite "Card" öffnen.
- Die Felder "luxTitleTooltip" und "luxSubTitleTooltip" mit beliebigen Werten füllen. 
- Prüfen, ob die Tooltipps korrekt angezeigt werden.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4291) und MacOS 14.4.1 mit den jeweils aktuellen u.a. Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
