### ISSUE TITLE
Checkbox-Authentic Komponente, [luxReadonly]

### ISSUE THREAD

**Issue by JBeckerSN** [IHK-GfI/lux-components#466]
Mit dem Attribut [luxReadonly]=true lässt sich trotzdem der Haken der Checkbox Komponente <lux-checkbox-ac> "toggeln"

Erwartet wird da eigentlich eine Anzeige des Wertes (true oder false) ohne Änderungsmöglichkeit

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

### Test

- Die Demoseite "Checkbox-Authentic" öffnen.
- Das Toggle "luxReadonly" aktivieren.
- Prüfen, dass die Checkbox nicht mehr (de-)aktiviert werden kann. 

Den Test für folgende Formularelemente wiederholt: 

- Radio
- Toggle
- Slider

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4291) und MacOS 14.4.1 mit den jeweils aktuellen u.a. Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
