### ISSUE TITLE
Barrierefreiheit Stepper (OZG): Transparenz ändern

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#469]
Siehe [Issue #71: Barrierefreiheit Stepper (OZG): Transparenz ändern](https://github.com/IHK-GfI/lux-components-theme/issues/71).

**Comment by thodic77** [comment]
Bitte einen Test zum Nachstellen dokumentieren.
Klärung Level der geforderten Barrierefreiheit.

**Comment by patrowe** [comment]
Der geforderte Level ist AA.
Einen Test zum Nachstellen für die Klärung der ARIA-Labels gibt es nicht. 
Nach Vereinbarung soll nun nur die Transparenz geändert werden.

**Comment by thodic77** [comment]
Der Fix wurde über den Theme-Issue https://github.com/IHK-GfI/lux-components-theme/issues/71 gefixt.
