### ISSUE TITLE
LUX-Dialog: Buttons sind auf kleinen Bildschirmen im Querformat unerreichbar

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#47]
### Ist-Zustand
Die Buttons sind auf kleinen Bildschirmen im Querformat unsichtbar/unerreichbar.

### Soll-Zustand
Die Buttons müssen auch auf kleinen Bildschirmen im Querformat sichtbar/erreichbar sein. 

### Test
- [LUX-Dialog-Demoseite](https://lux-components-develop.gfi.ihk.de/components-overview/example/dialog) öffnen. 
- Chrome-DevTools öffnen.
- Device auf "iPhone 5/SE" umstellen. 
- Auf Querformat umstellen.
- Den Button "ÖFFNEN [EIGENE COMPONENT]" anklicken. 
- Prüfen, ob die Buttons sichtbar/erreichbar sind. 

![image](https://user-images.githubusercontent.com/32597554/101136735-0e29e200-360e-11eb-9e0d-99f4c01b2627.png)

**Comment by thodic77** [comment]
Der Soll-Zustand wurde hergestellt.

**Comment by DSeifer** [comment]
Die Button sind im Firefox unter Windows 10 weiterhin nicht erreichbar.
![Screenshot 2020-12-04 105226](https://user-images.githubusercontent.com/75263741/101149221-e68f4580-361e-11eb-894f-39118c505ebc.jpg)

**Comment by DSeifer** [comment]
Sorry, Fehler im lokalen Build. Die Schaltfläche ist jetzt da.
