### ISSUE TITLE
Styleanpassungen für Buttons im Green-Theme

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#470]
Eine Analyse des IHK24-Designs hat folgende Abweichungen bei den Stylings der Buttons ergeben:
- bei den Labels wird die Schriftart Roboto verwendet, gefordert ist Korb alternativ Blogger Sans
 - die Farbkontraste erfüllen nicht bei allen Buttons/States die erforderliche Contrast-Ratio laut WCAG 2.1 AA.

**Akzeptanzkriterien**
1. Alle Button-Labels verwenden die Schriftart Blogger Sans, mit font-weight: 400, die Schriftart Korb wird im Fontstack vorangestellt.
2. Beim Hover-Effekt wird das Button-Label zusätzlich unterstrichen.
3. Der Abstand des Focus-Indicators wird auf 2px erhöht.
4. Die Strichstärke bei den stroked-Buttons wird auf 2px erhöht
5. Die Farbwerte werden entsprechend der Designvorlage angepasst.

Der Link zu der Designvorlage mit allen Farbwerten wurde an das Team ATF übermittelt, hier die pdf-Version für die Übersicht
[Anpassungen- Buttons.pdf](https://github.com/IHK-GfI/lux-components/files/15190866/Anpassungen-.Buttons.pdf)

**Comment by patrowe** [comment]
Nach neuen Designentscheidungen und Analyse für die Migration auf die Angular MDC-Components, sollen in diesem Schritt nur die Schriften der Button-Labels Angepasst werden.
Alle weiteren Anpassungen werden mit oder nach der Migration durchgeführt.

**Akzeptanzkriterien**

Alle Button-Labels verwenden die Schriftart Blogger Sans, mit font-weight: 400, die Schriftart Korb wird im Fontstack vorangestellt.

**Comment by thodic77** [comment]
Die Anforderungen wurden umgesetzt.

### Test

- Das Green-Theme über das Benutzermenü aktivieren.
- Die Demoseite "Button" öffnen.
- Prüfen, ob die Schrift und das Gewicht korrekt sind (Developer-Tools F12 Chrome).
   
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/5eb63fc4-2d1b-4029-a1a4-cdc31007ebe0)

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4412) und MacOS 14.5 mit den jeweils aktuellen Browserversionen und im Green-Theme getestet:

*MacOS:*
Safari -> OK
Chrome -> OK

*Windows:*
Edge -> OK
Chrome -> OK
