### ISSUE TITLE
Barrierefreiheit (OZG): aria-label wird bei file-upload nicht gesetzt

### ISSUE THREAD

**Issue by skleinhaus** [IHK-GfI/lux-components#471]
Im Rahmen der OZG Barrierefreiheit Tests wurde folgender Fehler gefunden:

Falscher Dateityp Error-Hint:

![Screenshot 2024-05-13 113357](https://github.com/IHK-GfI/lux-components/assets/65165446/f2f7508f-6a9e-4a02-b9d9-55a49ae15c64)

Der X-Button der Errormeldung besitzt kein aria-label

![Screenshot 2024-05-13 113600](https://github.com/IHK-GfI/lux-components/assets/65165446/f76e2d9b-3aeb-4242-a188-55ab282000e7)

Ich habe keine Möglichkeit gefunden das aria-label hier manuell zu setzen.

Ist es möglich das aria-label des Buttons mit den Inhalt der Fehlermeldung zu befüllen?

**Comment by thodic77** [comment]
Das Aria-Label des Buttons wird jetzt gesetzt.

**Comment by thodic77** [comment]
### Test

- Die Demoseite "File-Upload" öffnen.
- Eine zu große Datei hochladen.
- Den Button über die DevTools öffnen.
- Prüfen, ob das Aria-Label gesetzt ist.
