### ISSUE TITLE
luxBrandLogoSrc und luxAppLogoSrc in der LuxAppHeaderAcComponent lassen nur relative Pfade zu

### ISSUE THREAD

**Issue by cdennemarksundn** [IHK-GfI/lux-components#472]
Die luxBrandLogoSrc und luxAppLogoSrc in der LuxAppHeaderAcComponent  enthalten eine Logik, die dazu führt, dass // auch bei https:// bzw. http:// auf / reduziert werden und somit keine externe Resource für die Logos angegeben werden kann.

**Comment by thodic77** [comment]
Die Fehler wurde behoben. 

Tests stellen die korrekte Funktionsweise sicher.
