### ISSUE TITLE
Neues Standard-Icon: Ausgefülltes Pedant zu lux-interface-favorite-star im CDN

### ISSUE THREAD

**Issue by taubec** [IHK-GfI/lux-components#476]
Für das Lux Standard-Icon "lux-interface-favorite-star" wird ein ausgefülltes Pedant benötigt. Aktuell vorrangig im CDN.

Siehe hier:
![favorite-star-full](https://github.com/IHK-GfI/lux-components/assets/81471669/48964b61-b596-4c12-8319-61df4ab6eecb)

**Comment by thodic77** [comment]
Die LUX-Icons bestehen alle aus Outlineicons. D.h. es ist nicht geplant, auch ausgefüllte Icons anzubieten. Mit dem Issue #477 können auch CDN- und Custom-Icons zusammen eingesetzt werden. Das individuelle Icon kann dann wieder über die App selbst ausgeliefert werden.
