### ISSUE TITLE
LUX-Icon - Bei konfiguriertem CDN funktionieren die Custom-Icons nicht

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#477]
Wenn man in der Konfiguration unter "iconBasePath" eine CDN-Url einträgt, versucht das LUX-Icon die Custom-Icons ebenfalls vom CDN zu laden. Die Custom-Icons liegen aber im Asset-Ordner der App. 

Anleitung CDN: https://github.com/IHK-GfI/lux-components/wiki/config-v16#icons-%C3%BCber-ein-cdn-laden
Anleitung Custom-Icons: https://github.com/IHK-GfI/lux-components/wiki/lux%E2%80%90icon-v16#7-custom-icon-verwenden

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

### Test

- Die Demoseite "Icon" öffnen.
- In das Feld "luxIconName" den Wert "app-ihk-gfi" eintragen.
- Prüfen, ob das Custom-Icon korrekt angezeigt wird.
- In das Feld "luxIconName" den Wert "lux-save" eintragen.
- Prüfen, ob das CDN-Icon korrekt angezeigt wird.
- Die Request in der Browser-Console (Chome F12) checken.
  ![image](https://github.com/IHK-GfI/lux-components/assets/32597554/f11838b2-c1b0-4a6e-8ffc-6e03a24645b8)
  ![image](https://github.com/IHK-GfI/lux-components/assets/32597554/4bf5c911-34e4-4fc1-a71f-c2d0324f33b1)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.4412) und MacOS 14.5 mit den jeweils aktuellen u.a. Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
