### ISSUE TITLE
Close-Button im LUX-Dialog hat keine ARIA-Role

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#480]
Der Close-button in einem LUX-Dialog hat kein ARIA-Role. Das muss gefixt werden.
![image](https://github.com/IHK-GfI/lux-components/assets/49644099/d7989810-96b0-495a-8711-513d79c96dba)

**Aktzeptanzkriterium:**
Der Button ist mit der ARIA-Role "button" versehen worden.

**Comment by thodic77** [comment]
Es muss der Toggle "disableClose" deaktiviert werden, damit der Button sichtbar wird.

Vorher: 
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/b2dc40d8-32e2-4481-893e-8b3a592ef7e0)

Nachher: 
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/c92414f2-778f-48d4-a5cd-ddd640395881)

**Comment by DSeifer** [comment]
<img width="682" alt="Bildschirmfoto 2024-06-07 um 09 38 43" src="https://github.com/IHK-GfI/lux-components/assets/75263741/72ca1590-5154-4ba4-8789-940c81a71c65">

**Comment by DSeifer** [comment]
HTML-Code gereviewed. **role="button"**
