### ISSUE TITLE
Fontstack im Green-Theme anpassen

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#481]
Der Fontstack im Greentheme, soll wie folgt angepasst werden:

$app-headline-font: Korb, "Blogger Sans", "Source Sans Pro", Arial, sans-serif;
$app-font-family: "Source Sans Pro", Arial, sans-serif;

**Comment by thodic77** [comment]
@patrowe: Bitte testen.

**Comment by patrowe** [comment]
Die Anpassungen im Fontstack waren erfolgreich. 

Getestet unter Windows 10 und MacOs Sonoma 14.5

Bitte noch im Theme in der Datei green/_custom.scss den Wert für die font-family für h1,...,h6 auf "luxcommon.$app-headline-font" ändern. (Im Code Zeile 37).

**Comment by DSeifer** [comment]
Codeänderung gereviewed.
