### ISSUE TITLE
Eigene "Lux-Panel"-Komponente im Lux-Accordion ermöglichen

### ISSUE THREAD

**Issue by JBeckerSN** [IHK-GfI/lux-components#486]
Derzeit ist es nicht möglich, eine eigene Komponente in einem Lux-Accordion anzuordnen, welche dann wie ein Lux-Panel agiert.

<lux-accordion
      ...
    >
      <app-my-panel></app-my-panel>

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. 

### Test

- Die Demoseite "Accordion" öffnen. 
- Das Panel "Panel 4 - Custom Panel" ist eine eigene Komponente.
- Prüfen, ob das Custom Panel angezeigt wird.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK
Chrome -> OK

Windows:
Edge -> OK
Chrome -> OK
