### ISSUE TITLE
Extra Zeile bei einer Textbox ohne Titel

### ISSUE THREAD

**Issue by heli-Berry** [IHK-GfI/lux-components#488]
Wenn bei der Textbox kein Titel angegeben wird, wird dennoch eine leere h2 Zeile angezeigt. Diese Zeile sollte auch mit ausgeblendet werden.

![luxTextbox](https://github.com/IHK-GfI/lux-components/assets/168534675/ac00ae82-b1b4-4447-9b3d-74d82696a630)

Hinweis: es sollte auch geprüft werden ob eine extra Zeile angezeigt wird, wenn es in der Textbox nur einen Titel und keinen Text gibt.

**Comment by thodic77** [comment]
Die unnötigen Abstände wurden entfernt.

### Test

Die Demoseite "Textbox" öffnen.

### Ohne Titel und Icon
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/7239d8a9-b2f1-49bc-ab79-ed820f536ab0)

### Ohne Inhalt
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/a14411b8-5d38-432e-b3bc-fb24e9d01c8a)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
