### ISSUE TITLE
Überschriften-Tags (h1,h2,...) sollen individuell vergeben werden können

### ISSUE THREAD

**Issue by janweckwerth** [IHK-GfI/lux-components#49]
In manchen Layouts kommt es zu Situationen, in denen jetzt automatisch die Header-Tags falsch vergeben werden. 

Beispielsweise wird der Titel einer lux-file-list Component automatisch mit einem h2-Tag dargestellt. Die Überschrift einer Lux-Card erhält ebenfalls automatisch das h2-Tag. Wird die lux-file-list Component in eine Card eingebettet, befindet sich so ein h2-Tag der lux-file-list unterhalb eines weiteren h2-Tags. So wird die Hierarchie der Überschriften gebrochen.

Deshalb sollen die h-Tags für die Lux-Card und lux-file-list Component über einen Parameter vergeben werden können. Nur so können individuelle Layouts ohne Bruch in der Überschriftenhierarchie erstellt werden.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt. Über das Property "luxHeading" kann der Überschriften-Tag gesteuert werden.

Test

- Bespielseite der Lux-Card öffnen. 
- Debugconsole öffnen (F12 im Chrome).
- Die Überschrift in der Card ansehen. 
- Die Überschrift muss mit dem Wert aus der Property "luxHeading" übereinstimmen. Z.B. luxHeading = 2, <h2>...</h2>

![image](https://user-images.githubusercontent.com/32597554/103655169-2a9ba000-4f67-11eb-8719-2c91e72125de.png)

**Comment by thodic77** [comment]
@DSeifer Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 mit Opera, Chrome und Edge: OK
Getestet unter MacOS 11.1 mit Safari: OK
