### ISSUE TITLE
Lux-Filter-Form: das Filter-Menu kann nicht ausgeblendet werden.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#490]
Aktuell wird in der Komponente das Filter-Menu bzw. der Trigger-Button immer eingeblendet.
Wir brauchen eine Möglichkeit, diesen Button optional auszublenden, wenn das Menu nicht benötigt wird.

**Aktzeptanzkriterium:**
Die Komponente lux-filter-form besitzt einen Property, über die das Filter-Menu optional ausblendet werden kann.

**Comment by thodic77** [comment]
Die Sichtbarkeit des Filter-Menüs kann jetzt über die Property luxHideMenu gesteuert werden.

### Test

- Die Demoseite "Filter" öffnen.
- Das Filterpanel mit einem Klick auf den Header aufklappen, denn nur dann ist das Filter-Menü sichtbar.
- Das Toggle "luxHideMenu" aktivieren.
- Prüfen, ob das Filter-Menü ausgeblendet wurde.
  
![image](https://github.com/IHK-GfI/lux-components/assets/32597554/2ef30cc9-aab2-44f6-8c8b-9f3c52db2ae7)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 mit den jeweils aktuellen Browserversionen getestet:

MacOS:
Safari -> OK

Windows:
Edge -> OK
