### ISSUE TITLE
Style-Anpassung: lux-tile

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#496]
Das Green-Theme für die Komponente lux-tile soll entsprechend den Designvorlagen von ihk24 angepasst werden.

**Comment by patrowe** [comment]
Die Vorlage für die Styleanpassungen für die Komponente lux-tile in der bekannten Figma-Datei erstellt.

**Akzeptianzkreiterium für die Umsetzung:**
Die Styleanpassungen für das Green-Theme wurden gemäß der Designvorlage umgesetzt.

**Comment by DSeifer** [comment]
### Test unter Windows (Edge) und MacOS (Safari)
Grundsätzlich wäre es schön, wenn es bei "Tile" auch eine optionale Testseite mit mehreren Textkacheln geben würde, analog zu "Tile AC".

luxLabel: OK
luxIcon anzeigen: OK
luxShowNotification: OK
luxCounter: ERR -> Es wird keine Notification mit einem Counter angezeigt. Wird luxShowNotification auf true gesetzt, wird die Zahl im Feld luxCounter gelöscht.
luxCounterCap: Kann nicht getestet werden, da keine Notification angezeigt wird.

**Comment by DSeifer** [comment]
### Test im responsive Design
Im responsive Design ist die Kachel nicht quadratisch, sondern rechteckig (hochkant), im Gegensatz zum Desktop, wo sie rechteckig (quer) ist. Im Figma-Beispiel ist die Kachel mobile quadratisch.

**Comment by heli-Berry** [comment]
Es wurde eine neue Property (luxShowShadow) eingeführt die bestimmt ob ein Schatten um die Kachel angezeigt werden soll oder nicht.

**Comment by heli-Berry** [comment]
Testbeschreibung: 
- Das Style der Kachel entspricht dem in Figma. 
- Die neue Property zeigt einen Schatten an oder nicht. 
- Vorhandene Funktionen der Kachel bestehen weiterhin
( Dass wenn luxShowNotification auf true gesetzt wird, die Zahl im luxCounter auf null gesetzt wird, ist ein Verhalten das vorher bereits vorhanden war )

**Comment by heli-Berry** [comment]
In dem Branch fehlte der letzte commit aus dem Develop branch, das wurde noch nachgeholt.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise 22H2 (19045.4894) und MacOS 15.0.1

Windows/Edge: OK
MacOS/Safari: OK
