### ISSUE TITLE
LUX-ERROR-PAGE ohne "Zur Startseite zurück"-Button erzeugen

### ISSUE THREAD

**Issue by caro-kos** [IHK-GfI/lux-components#5]
Die LUX-ERROR-PAGE sieht immer einen Button vor (z.B. "Zurück zur Startseite"), konfigurierbar über ILuxErrorPageConfig.homeRedirectText und ILuxErrorPageConfig.homeRedirectUrl.
Wenn der Text mit '' konfiguriert wird, ist der Button "leer", schwebt man mit der Maus über die Stelle, kann geklickt werden.
Bei leerem Text und/oder leerer Url sollte der Button nicht gerendert (hinzugefügt) werden.
Oder mit einer Option in den ILuxErrorPageConfig schaltbar.

**Comment by thodic77** [comment]
Der Button wird nur noch angezeigt, wenn eine URL und ein Label hinterlegt sind.
