### ISSUE TITLE
Anpassbares Verhalten bei Validierung im lux‐file‐input gewünscht

### ISSUE THREAD

**Issue by ckutzner33** [IHK-GfI/lux-components#50]
Tritt ein Validierungsfehler beim lux-file-input Control auf, wird die ausgewählte Datei aus dem Textfeld entfernt. Es ist nicht mehr ersichtlich welche Datei ausgewählt wurde.
Hier wird bisher implizit die Datei wieder aus dem Input entfernt, wenn diese nach dem Validierungsschema nicht passt. Gibt es eine Möglichkeit das Verhalten konfigurierbar zu machen? Gewünscht ist, die Datei explizit vom Benutzer entfernen zu lassen oder dieser die Datei mit einer neuen Dateiauswahl überschreiben kann.

**Comment by thodic77** [comment]
Über das Property "luxClearOnError" kann gesteuert werden, ob die bereits vorhandene Datei aus dem Textfeld entfernt wird. 

Test

- Demoseite "File-Input" öffen.
- Das Toggle "luxClearOnError" deaktivieren. 
- Eine zu große Datei (Wert aus dem Textfeld "luxMaxSizeMB" beachten) hochladen.
- Prüfen, ob die bereits eingetragene Datei "example.png" noch im Textfeld steht und nicht entfernt wurde.

![image](https://user-images.githubusercontent.com/32597554/103765003-c509eb00-501c-11eb-9f54-446ab03607e3.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 mit Chrome, Opera und Edge: OK
Getestet unter MacOS 11.1 mit Safari: OK
