### ISSUE TITLE
Zeilenumbruch bei Pflichtfeldstern

### ISSUE THREAD

**Issue by SoulTheTimelord** [IHK-GfI/lux-components#501]
Bei Labeln von Elementen welche ein Pflichtfeldstern aufweisen wird, falls ein Zeilenumbruch nötig ist, der Pflichtfeldstern einzeln in die nächste Zeile gebrochen

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

**Test**

- Die Demoseite "Input" öffnen.
- Das Toggle "luxRequired" aktivieren.
- Auf den Tab "Erweitert" wechseln.
- Das Toggle "Lange Labeltexte mit Zeilenumbruch zulassen" aktivieren.
- Auf den Tab "Allgemein" zurück wechseln.
- Die Eingabe im Feld "luxLabel" verlängern.
- Prüfen, dass das * nicht alleine umbricht.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
### Getestet unter Windows 10 Ênterprise (22H2/19045.5131) und macOS 15.1.1 (Sequoia).

### Win / Edge:

- Die Demoseite "Input" geöffnet.
- Das Toggle "luxRequired" aktiviert.
- Auf den Tab "Erweitert" gewechselt.
- Das Toggle "Lange Labeltexte mit Zeilenumbruch zulassen" aktiviert.
- Auf den Tab "Allgemein" zurück gewechselt.
- Die Eingabe im Feld "luxLabel" verlängert.
- Das Zeichen * bricht nicht alleine um.

### macOS / Safari:
- Die Demoseite "Input" geöffnet.
- Das Toggle "luxRequired" aktiviert.
- Auf den Tab "Erweitert" gewechselt.
- Das Toggle "Lange Labeltexte mit Zeilenumbruch zulassen" aktiviert.
- Auf den Tab "Allgemein" zurück gewechselt.
- Die Eingabe im Feld "luxLabel" verlängert.
- Das Zeichen * bricht nicht alleine um.
