### ISSUE TITLE
Autocomplete Komponente feuert kein Blur/FocusOut Event bei Nutzung von Microsoft Edge Autofill

### ISSUE THREAD

**Issue by tmrd993** [IHK-GfI/lux-components#504]
Browser: Microsoft Edge Version 126

Bei Nutzung von Microsoft Edge werden eingebene Formulardaten gespeichert und können beim erneuten Aufruf der Seite automatisch in die Felder übertragen werden (siehe Funktion "Zuletzt Verwendet" oder "last used").

Diese Funktion führt bei der Autocomplete Komponente zu Problemen da durch das Autofill von Edge keine Events (Blur/FocusOut) gefeuert werden. Dadurch wird das Control nicht aktualisiert und die pick value Funktion wird ignoriert.

**Comment by thodic77** [comment]
Fehler
![Issue_504_error](https://github.com/IHK-GfI/lux-components/assets/32597554/1b3c9c3e-7113-4c07-9c83-57506154572b)

Der Fehler wurde behoben.

Wenn der Browser ein Auto-Fill anbietet, obwohl autocomplete="off" gesetzt wurde, erkennt das Autocomplete-Feld die Situation jetzt und führt dieselben Schritte aus, als ob ein FocusOut-Event gefeuert worden wäre.

### Vorbedingung

- Im Edge-Browser muss eine Adresse (_Einstellungen -> Profile -> Persönliche Informationen -> Adresse hinzufügen_) hinterlegt werden.
- In der Datei _lux-autocomplete-ac.component.html_ muss der folgende Wert ausgetauscht werden, damit man die Fehlersituation nachstellen kann: 
  _autocomplete="off" -> autocomplete="address-line1"_

### Test ungültiger Wert

- Die Demoseite "Autocomplete" öffnen. 
- Autofill für die Adresse auslösen:
  ![Issue_504_ok_invalid_value](https://github.com/IHK-GfI/lux-components/assets/32597554/658489ac-ecc2-4eb8-8e6d-ac2409562ff5)
- Prüfen, dass ein Fehler angezeigt wird und das Formular invalid ist.

### Test gültiger Wert

- Autofill für die Adresse auslösen:
  ![Issue_504_ok_valid_value](https://github.com/IHK-GfI/lux-components/assets/32597554/a16db45d-2753-4744-9118-ffed86991e94)
- Prüfen, dass kein Fehler angezeigt wird und das Formular valide ist.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 mit dem Edge-Broser getestet:

MacOS: OK
Windows: OK
