### ISSUE TITLE
Download von PDF`s aus der File-List funktioniert auf dem iPhone/iPad in Safari nicht

### ISSUE THREAD

**Issue by DSeifer** [IHK-GfI/lux-components#505]
Beim Download einer PDF-Datei aus einer JAST-App über Safari auf einem iPad oder einem iPhone gibt es Probleme. Wenn der Button "download" gedrückt wird tut sich nichts. Beim png fragt die App ob die Datei geladen oder geöffnet werden soll. Bei Chrome geht es problemlos. Nur die Kombination iPad/Safari und iPhone/Safari sorgt für Probleme. 

Scheinbar weiß der Safari in dem Augenblick nicht, was er mit der PDF anfangen soll und macht einfach gar nichts.

**Comment by DSeifer** [comment]
Test auf dem Mac unter MacOS 17.5 im Simulator für ein iPhone 15 Pro und ein iPad ???:

- Nach dem Bauen der App und dem Starten im Simulator werden sowohl eine "example.png" als auch neu eine Lorem Ipsum.pdf" angezeigt.
- Beim Auslösen des Download der Datei "Lorem Ipsum.pdf" erscheint nicht wie bei der png ein Dialog, in welchem zwischen "Anzeigen" und "Laden" gewählt werden kann, sondern die PDF wird sofort in der ursprünglichen Registerkarte des Browsers geöffnet.
- Ein Download in den Downloadpfad des Browsers erfolgt nicht! Dies müsste aktuell im Nachgang manuell erfolgen.
- Das ist ein Fortschritt gegenüber dem Fehlerzustand, stellt mich aber noch nicht zufrieden. M.E. sollte ebenfalls ein Dialog erscheinen, der folgende Möglichkeiten bietet: Öffnen wahlweise Browser (dann aber neue Registerkarte) oder (falls installiert) Adobe Acrobat oder ggf. anderer PDF-Viewer. Und Laden, also der reine Download in den in den Einstellungen hinterlegten Downloadpfad des Browsers.
- @thodic77: Bitte prüfen, ob das Verhalten weiter optimiert werden kann.

**Comment by thodic77** [comment]
@DSeifer: Bitte noch einmal Testen. Jetzt sollte ein Dialog erscheinen. Die PDF-Datei wird im Downloadpfad gespeichert. Wenn man die PDF-Datei ansehen möchte, kann man die View-Action anstatt der Download-Action verwenden.

**Comment by DSeifer** [comment]
Getestet im Simulator (iPhone 15 Pro) auf dem MacBook unter iOS 17.0

- Der Dialog erscheint nun. 
- Der Dialog hat eine Schaltfläche "Laden"
- Bei Betätigen dieser Schaltfläche wird die PDF ins Standarddownloadverzeichnis unter "Dateien" heruntergeladen. 
- Zum direkten Öffnen der PDF mit dem Browser dient die Funktion "Ansehen".
