### ISSUE TITLE
lux-autocomplete: Autovervollständigung greift bereits während der Eingabe und nicht erst bei FocusOut

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#508]
### Test

- Die Demoseite "Autocomplete" öffnen.
- Den Buchstaben V in das Autocompletefeld eintragen.
  
![Issue_508_error](https://github.com/user-attachments/assets/b9d4b638-7902-45da-ae42-91df778242fa)

- Prüfen, dass der Wert nicht bereits während der Eingabe vervollständigt wird, sondern erst bei Focusout.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 getestet:

MacOS: 
Safari: OK
Chrome: OK
Firefox: OK

Windows: 
Edge: OK
Chrome: OK
Firefox: OK
