### ISSUE TITLE
lux-app-header-ac - Benutzermenü rutscht ungewollt in eine zweite Zeile, wenn ein lux-tenant-logo verwendet wird

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#511]
**Problem:** Wenn ein lux-tenant-logo verwendet wird, rutscht das Benutzermenü ungewollt in eine zweite Zeile.

Desktop:
![image](https://github.com/user-attachments/assets/b4905d18-44cf-43ea-91f2-a28cbe74e6c6)

Mobile:
![image](https://github.com/user-attachments/assets/40b09cc7-bf71-414a-977b-5cda86a5b227)

**Comment by thodic77** [comment]
Vielen Dank für den Fix, [10PunkteFuerGfindor](https://github.com/10PunkteFuerGfindor)!

### Test

- Die Demoseite "Tenant-Logo" öffnen.
- Das Toggle "Nutze diese Komponente für den Header" aktivieren.
- Prüfen, ob das Layout (Desktop und Mobile) vom Header korrekt aussieht.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 21H2 (19045.4529) und MacOS 14.5 im Desktop und responsive Design getestet:

MacOS:
Safari: OK
Chrome: OK
Firefox: OK

Windows:
Edge: OK
Chrome: OK
Firefox: OK
