### ISSUE TITLE
lux-button Doppelklick unterbinden

### ISSUE THREAD

**Issue by casparhauser2001** [IHK-GfI/lux-components#52]
Die lux-button 's  akzeptieren einen Doppelklick und lösen diesen auch zwei, drei, n mal aus. Diese Events müssen um dies zu verhindern aktuell mit einer disable/enable Funktion des Buttons ausgeschaltet und nach einer gewissen Zeit wieder eingeschaltet werden. 

ggf. gibt es hier eine elegantere Lösung :-)

**Comment by thodic77** [comment]
Die LUX-Buttons verhindern Mehrfachklicks in einer gewißen Zeitspanne. 
Die Zeit kann zentral in der Buttonkonfiguartion "throttleTimeMs" angegeben werden. 
Diese Einstellung kann aber für jeden LUX-Button übersteuert werden. Der LUX-Button verfügt über die neue Property "luxThrottleTime".

Test

- Die Demoseite der LUX-Buttons öffnen. 
- Das Toggle "Output-Events loggen"  aktivieren. 
- Die Console (F12 im Chrome) öffnen. 
- 2-mal schnell klicken. 
- Prüfen, ob nur ein Eintrag in der Console geloggt wurde. 
- 2-mal langsam klicken.
- Prüfen, ob beide Einträge in der Console geloggt wurden. 

![image](https://user-images.githubusercontent.com/32597554/104008003-1941d600-51a9-11eb-92a1-225d092b54a7.png)

So kann der Konfigurationswert geändert werden: 
![image](https://user-images.githubusercontent.com/32597554/104008326-9705e180-51a9-11eb-800e-dcd0c66eb594.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Wie oben beschrieben getestet unter:
Windows 10 getestet mit Chrome, Opera, Edge, Firefox: OK
MacOS 11.1 getestet mit Safari, Chrome, Firefox: OK
