### ISSUE TITLE
Style-Anpassung: lux-button focus-indicator

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#522]
Der Focus-Indicator und der Hover-Effekt für die Buttons soll dem ihk24-Style angepasst werden.

**Comment by heli-Berry** [comment]
Stylings müssen noch definiert werden

**Comment by patrowe** [comment]
Wegen ungeklärter Designentscheidungen wird dieses Ticket bis auf weiteres geschlossen.
