### ISSUE TITLE
lux-checkbox-container: Anpassung

### ISSUE THREAD

**Issue by casparhauser2001** [IHK-GfI/lux-components#524]
in der lux-checkbox-container Komponente soll vergleichbar mit der lux-radio Komponente ein lux-form-control-wrapper integriert werden der dafür sorgt, dass die die Abstände zwischen der Checkbox-Gruppe (wie in der radiobutton-group) zu den umliegenden Komponenten gewährt sind.

![image](https://github.com/user-attachments/assets/add599d0-0b97-4160-9c49-939f229620f1)
![image](https://github.com/user-attachments/assets/6bed500f-7104-4b46-be1e-a1ab525ce24a)

**Comment by patrowe** [comment]
Die Abstände im Checkbox-Container sind bewusst verringert, da er speziell für die Anordnung einzelner Checkboxen z.B. in einer Filter-Komponente konzipiert ist. Da dort keine Fehlermeldungen erwartet werden, wurde der dafür reservierte Platz ebenfalls entfernt. Ein Standard-Label der LUX-Fomrcontrols wurde ergänzt und kann optional angezeigt werden, um mit anderen Filter-Elementen zu korrespondieren.
Wird ein Abstand unterhalb des Checkbox-Containers gewünscht, kann dieses dem als Margin-Bottom mitgegeben werden. Der Standardabstand in einem Formular ist dabei 16px.

Aus Usability-Sicht ist eine Checkbox immer eine Einzelelement, anders als bei Radiobuttons die eine Gruppe bilden. Daher ist es ungünstig unter eine "Gruppe" von Checkboxen nur eine gemeinsame Fehlermeldung anzubringen.
Daher stellt der unterschiedliche Abstand keinen Fehler da und muss nicht korriegiert werden.

Es sollte erwogen eine andere Lösung zu finden,  z.B. die Wahl eines lux-multiselect.
