### ISSUE TITLE
lux-file-list: Required Fehlermeldung beim Upload entfernen.

### ISSUE THREAD

**Issue by mohamed-abdul-hussein2** [IHK-GfI/lux-components#531]
Während des Hochladens einer Datei (wenn der Status der Datei auf "uploading" steht), bei der lux-file-list, wird kurzzeitig die Fehlermeldung angezeigt, obwohl der Upload-Vorgang noch nicht abgeschlossen ist. Die Fehlermeldung soll jedoch nur dann erscheinen, wenn das Feld "touched" und dann leer ist.

![image](https://github.com/user-attachments/assets/48d99c06-b45c-456d-8ff2-95eeac33cae4)

**Comment by heli-Berry** [comment]
Testbeschreibung:
- Wenn eine zu große Datei hochgeladen wird, erscheint eine Fehlermeldung. Wenn diese weggeklickt wird kommt die Meldung das der Upload verpflichtend ist.
- Wenn eine Datei hochgeladen wird verschwindet die Fehlermeldung.
- Wenn eine Datei hochgeladen wird, wird keine Fehlermeldung angezeigt.

**Comment by patrowe** [comment]
Test wurde durchgeführt unter
MacOS Sequoia 15.0 in den Browsern Safari, Chrome, Firefox --> OK
Windows 10 in den Browsern Chrome, Firefox, Edge --> OK

Die Anforderungen wurden vollständig und erfolgreich umgesetzt.
