### ISSUE TITLE
lux-stepper-large: durch zurücknavigieren können valide Steps verändert werden und troztdem wieder verlassen werden.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#532]
Nachstellen des Fehlers:

- in der Demo den Stepper-Large öffnen
- prüfen dass die Option "Validierung der Steps" gesetzt ist
- jetzt durch mehrere Steps navigieren (über weiter)
- zu dem Step 2 zurück kehren und den Wert im Pflichtfeld "Bezeichnung" löschen.
- über die Liste der Steps können alle vorherigen Steps erreicht werden, ohne dass der Fehler behoben wurde. 

Das ist ein Fehler und muss korrigiert werden.

**Comment by DSeifer** [comment]
Getestet unter Windows 11 (22H2/19045.5011) und macOS Sequoia (15.1) in beiden Themes.

Windows
Edge: OK

macOS
Safari: OK
