### ISSUE TITLE
lux-table: Der Inhalt der Zellen ist immer Zentriert ausgericht, bitte auch eine Option für "align-Top" anbieten

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#533]
in der lux-table sind die Zellenelemente immer Zentriert ausgerichtet, bei unterschiedlichen Inhalten wird es daher schnell unübersichtlich.

![Bild (2)](https://github.com/user-attachments/assets/5548d1a6-78f9-4ef4-804b-949cb799ac9c)
elemente am Oberen Rand der Zeile ausgerichtet werden.

Bitte eine Property einfügen, damit die Zellen

**Comment by patrowe** [comment]
Die alternierende Zeilenfarbe soll ebenfalls angepasst werden. Der neue Farbton ist #f0f3f6.

**Comment by heli-Berry** [comment]
Testbeschreibung:
- Die vorhandenen Funktionen der Tabelle sind noch vorhanden
- Alle Elemente in der Tabelle sollen beim aktivieren der neuen Property noch oben verschoben werden (Checkboxen, Text, Aktionbuttons und Eingabefelder.) (Hinweis: Wenn es nur eine eine Zeile gibt rutscht der Aktionsbutton nicht hoch, wenn es mehrere Zeilen gibt verschiebt sich auch der Button)
- Die Hintergrundfarbe der alternierende Zeilen ist geändert

**Comment by patrowe** [comment]
Test wurde durchgeführt unter
MacOS Sequoia 15.0 in den Browsern Safari, Chrome, Firefox --> OK
Windows 10 in den Browsern Chrome, Firefox, Edge --> OK

Die Anforderungen wurden vollständig und erfolgreich umgesetzt.
