### ISSUE TITLE
lux-app-footer: der footer soll optional nicht mehr fixed sein

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#534]
Aktuell ist der app-footer immer am fest am unteren Bildschirmrand positioniert. Das ist gerade auf Mobilgeräten manchmal störend.
Es soll eine Property eingeführt werden, um diese Einstellung abwählen zu können.

**Comment by patrowe** [comment]
Akzeptanzkriterien
1. Die Komponente hat zwei neue Properties, je eine für Desktop und Mobile, erhalten.
2. Durch das setzen der Propertie wird der App-Footer am Ende der Seite angezeigt, es sei denn, der Seiteninhalt ist von der Höhe her geringer als die Screensize, dann bleibt der Footer sticky, am unteren Bildschirmrand
3. Im default ist der App-Footer sticky (wie bisher)
4. Mobile gilt für die MediaObserver-Abfrage "Handheld" (vgl. [https://material.angular.io/cdk/layout/overview#predefined-breakpoints](https://material.angular.io/cdk/layout/overview#predefined-breakpoints), Desktop für alle anderen Größen.

**Comment by thodic77** [comment]
Die Anforderung wurde wie ursprünglich geplant umgesetzt. Die beiden Properties heißen "fixedDesktop" und "fixedMobile".

**Test**

- Die Konfiguration der Demoseite öffnen.
- Die Toggles "fixedDesktop" und "fixedMobile" deaktivieren.
- Prüfen, ob der Footer korrekt angezeigt wird.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
### Getestet unter Windows 10 Ênterprise (22H2/19045.5131) und macOS 15.1.1 (Sequoia).

### Win / Edge:
- Die Optionen "fixedDesktop" und "fixedMobile" sowohl wechselweise als auch gleichzeitig gesetzt.
- In der mobilen Darstellung auf einem iPhone bewirkt die Option "fixedMobile", dass der Footer kontinuierlich am Bildschirmende angezeigt wird.
- In der Desktop-Darstellung bewirkt die Option "fixedDesktop" die Fixierung des Footers am Bildschirmende scheinbar nur, wenn die vollständige Bildschirmauflösung ausgenutzt wird. Ist das darstellende Browserfenster kleiner, z.B. weil die Entwicklertools seitlich eingeblendet sind, wird der Footer nicht am unteren Bildschirmrand fixiert. Hierbei scheint aber dann das zusätzliche Setzen der Option "fixedMobile" zu helfen.

### macOS / Safari:
- Die Optionen "fixedDesktop" und "fixedMobile" sowohl wechselweise als auch gleichzeitig gesetzt.
- In der mobilen Darstellung auf einem iPhone bewirkt die Option "fixedMobile", dass der Footer kontinuierlich am Bildschirmende angezeigt wird.
- In der Desktop-Darstellung bewirkt die Option "fixedDesktop" die Fixierung des Footers am Bildschirmende scheinbar nur, wenn die vollständige Bildschirmauflösung ausgenutzt wird. Ist das darstellende Browserfenster kleiner, z.B. weil die Entwicklertools seitlich eingeblendet sind, wird der Footer nicht am unteren Bildschirmrand fixiert. Hierbei scheint aber dann das zusätzliche Setzen der Option "fixedMobile" zu helfen.

**Ist dieses Verhalten gewollt?**

**Comment by DSeifer** [comment]
### Getestet unter Windows 10 Ênterprise (22H2/19045.5131) und macOS 15.1.1 (Sequoia).

Das oben beschriebene Verhalten entspricht m.E. der Google Material Spezifikation zum BreakpointObserver. Daher wird dieser Issue geschlossen.
