### ISSUE TITLE
Keine "Edit"-Icons bei linearem Stepper 

### ISSUE THREAD

**Issue by jonas-menne** [IHK-GfI/lux-components#543]
Bei einem linearen lux-stepper sollte es optional möglich sein das Icon von den bereits bearbeiteten Steps bei dem Ursprungsicon zu lassen, zB über eine Flag "showEditIcons". Dies hätte den Vorteil, dass bei mehreren Steps von dem Nutzer immer noch erkannt werden kann welcher Step zu welchem fachlichen Punkt gehört. 
![image](https://github.com/user-attachments/assets/82da5fc4-b3ba-4dd6-acb0-a6a9b5015b7f)

**Comment by patrowe** [comment]
Der lux-stepper verwendet intern den material-stepper. Dort werden alle Steps die vollständig (valid) sind automatisch durch ein Icon markiert. Es ist von Material nicht vorgesehen für jeden Step ein individuelles Edit-Icon anzugeben. 
Eine individuelle Lösung würde die Stepper-Logik und den Prozeß der Validierung der Schritte übergehen und ist nicht zu empfehlen.
