### ISSUE TITLE
Cancel Button bei Stepper

### ISSUE THREAD

**Issue by jonas-menne** [IHK-GfI/lux-components#544]
Simultan zu den zurück Buttons sollte es auf der ersten Seite des Steppers einen "Abbrechen"-Button geben. Der Entwickler sollte konfigurieren können was dieser macht. Dadurch hätte man einen einheitlichen Weg von Seiten mit einem Stepper zurück zu navigieren.

**Comment by patrowe** [comment]
Der lux-stepper verwendet intern einen material-stepper. Dieser bietet technisch keine Möglichkeit einen weiteren Button zu den Stepper-Buttons (next, previous) hinzuzufügen. Alternativ kann eine Breadcrumb-Komponente oder ein Entrag im Navigationsmenü verwendet werden.
