### ISSUE TITLE
Standalone Migration

### ISSUE THREAD

**Issue by kathari00** [IHK-GfI/lux-components#549]
Hallo, 

ich habe in meinem Team die Migration auf Standalone durchgeführt. Dazu wäre es gut, wenn die Lux-Components als Standalone markiert werden, damit nur genutzte Komponenten importiert werden.

- Dazu ist es nicht notwendig die Module zu entfernen
- Angular stellt Schematics zur Migration bereit

Gibt es Bedenken bzw. Probleme bei der Migration, bei denen ich unterstützen kann?

LG

**Comment by thodic77** [comment]
Größer Änderungen werden in einem Hauptrelease umgestellt. D.h. die Änderung auf Standalone wird voraussichtlich mit der v19 kommen.
