### ISSUE TITLE
ARIA-label für lux-progressbar und lux-spinner hinzufügen.

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components#551]
Laus WCAG AA müssen Progress-Komponenten ein Aria-Label besitzen. Dieser ist bei den lux-progressbar und dem lux-spinner nicht vorhanden und muss ergänzt werden.

Nachtestbar in der lux-demo:
-Seite für Progressbar/Spinner öffnen
-unter Konfiguration die Property "luxMode" auf indeterminate setzten
- AXE Accessibility-Plugin im Brower starten
Ergebnis:
https://www.streamlinehq.com/illustrations/illustrations-duotone?search=cloud

**Akzeptanzkriterium:**
-Die oben genannten Komponenten besitzen ein Aria-label
-Beim Testen der Komponenten mit dem Browsertool Axe Accessibility tritt keine Fehlermeldung mehr auf.

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

**Test**

- Die Demoseite "Progress" öffnen.
- Die Combobox "luxMode" auf "indeterminate" stellen.
- Die Browser-Console (F12 Chrome) öffnen.
- Ein Ladebalken (Strg + Shift + C) auswählen.
- Prüfen, ob ein Aria-Label vorhanden ist.
  ![image](https://github.com/user-attachments/assets/22463e16-e6a5-4746-84be-43f008fae894)
- Die axe Dev-Tools öffnen.
  ![image](https://github.com/user-attachments/assets/fd0a8cd1-553d-4609-85b3-b06891db1cff)
- Einen Scan der Seite ausführen.
- Prüfen, das keine Issues gefunden wurden.
  ![image](https://github.com/user-attachments/assets/0a254cad-c2da-4d0a-85e4-63ec84aeee1d)
- Die Demoseite "Spinner" öffnen und den Test von oben analog durchführen.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 11 (22H2/19045.5011) und macOS Sequoia (15.1).

**Windows**
Progress Edge: OK
Spinner Edge: OK

**macOS**
Progress Safari: OK
Spinner Safari: OK
