### ISSUE TITLE
Lux Card content height fixen

### ISSUE THREAD

**Issue by nicolast04** [IHK-GfI/lux-components#552]
Wenn man der Lux Card bisher kein Content Element mitgegeben hat, dann war der Abstand des Titels nach oben und unten äquivalent. Seit dem Update auf die 18.0.0 hat allerdings der mat-card-content eine Mindest-Height, auch wenn gar kein Content genutzt wird. Das führt dazu, dass die Lux Card unter dem Titel eine große weiße Fläche hat.

![Bild](https://github.com/user-attachments/assets/41c45342-352c-41da-ab78-46fe193c0f07)
![Bild (1)](https://github.com/user-attachments/assets/8f7009f1-ce16-41b9-b09b-bff0261230e9)

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

**Test**

- Die Demoseite "Card" öffnen.
- Das Feld luxTitle auf "IHK Aachen" setzen.
- Das Feld "luxSubTitle" leeren.
- Das Toggle "lux-card-content ausblenden" aktivieren.
- Auf den Tab "Erweitert" wechseln.
- Das Toggle "luxIcon anzeigen" deaktivieren.
- Das Toggle "luxCardActions anzeigen" deaktivieren.
- Das Toggle "luxCardInfo anzeigen" deaktivieren.
- Prüfen, das kein überflüssiger Abstand (siehe Screenshot oben) angezeigt wird.
  ![image](https://github.com/user-attachments/assets/a9a8cdd1-3832-49b2-b2a0-c62f57b14bba) 

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 11 (22H2/19045.5011) und macOS Sequoia (15.1) in beiden Themes.

**Windows**
Edge: OK
Firefox: OK

**macOS**
Safari: OK
Chrome: OK
