### ISSUE TITLE
Hitboxen von Radio-Buttons sind in vertikaler Anordnung ungenau

### ISSUE THREAD

**Issue by marcoebbinghausGFI** [IHK-GfI/lux-components#565]
Wenn ich auf https://lux-demo.applicationplatform.gfi.ihk.de/components-overview/example/radio-button-ac die vertikale Anordnung für die RadioButtons aktiviere, und dann im gerenderten Beispiel in die untere Hälfte von Option #2 klicke, wird Option #3 ausgewählt. Das ist nicht nur in genannter Applikation so, sondern beispielsweise auch in unserer EOA2-Jast-Applikation, seit wir auf die neueste Version von LuxComponents gewechselt sind. Wir sind damit noch nicht live aber werden es bald tun, und ich bin überzeugt davon, dass das für support fälle "Die Selektion funktioniert nicht richtig" sorgen wird.

**Comment by thodic77** [comment]
Der Fehler wurde im Theme behoben. 

**Test**

- Wie oben in der Beschreibung ausgeführt.

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (22H2 / 19045.5131) und macOS Sequoia (15.1.1):

Win / Edge: OK
macOS / Safari: OK
