### ISSUE TITLE
LUX-Stepper - Neue Output-Events "luxCheckValidation" und "luxStepClicked" einführen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#57]
Im Rahmen dieses Issues sollen die folgenden zwei Output-Events beim LUX-Stepper eingeführt werden: 

- _luxCheckValidation_ (wird aufgerufen, wenn eine Validierung nötig ist, z.B. interessant wenn das Property "luxCompleted" verwemdet wird). 
- _luxStepClicked_ (wird aufgerufen, wenn ein Step angeklickt wird.

**Comment by thodic77** [comment]
- Die Demoseite "Stepper" öffnen. 
- Das Toggle "Output-Events loggen" aktivieren. 
- Die Debugkonsole (F12 im Chrome) öffnen. 
- Den Stepheader (z.B. "Step 1") anklicken.
- In der Debugkonsole prüfen, ob die neuen Output-Events geloggt werden. 

![image](https://user-images.githubusercontent.com/32597554/105005628-e06df080-5a35-11eb-896c-b47796ae1edb.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise Version 1809 und MacOS 11.1 mit folgenden Browsern in der jeweils aktuellen Version:
Windows - Edge, Firefox, Chrome, Opera: **OK**
MacOS - Safari, Firefox, Chrome: **OK**
![image](https://user-images.githubusercontent.com/75263741/105032158-b4af3280-5a56-11eb-9d84-6346b1480ce4.png)
