### ISSUE TITLE
Master-Detail-Header wächst nicht korrekt mit

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#59]
![image](https://user-images.githubusercontent.com/32597554/105363330-3391a000-5bfc-11eb-8cf7-b62f6f508bd8.png)

**Comment by thodic77** [comment]
Der Fehler wurde behoben.

Test

- Demoseite "Master-Detail" öffnen.
- Den Filter aufklappen. 
- Prüfen, ob die Oberfläche ok ist. 

![image](https://user-images.githubusercontent.com/32597554/105364140-190bf680-5bfd-11eb-9cb6-9abdca51c156.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (1809) und MacOS 11.1 mit folgenden Browsern:
Windows -  Edge, Chrome, Firefox: **OK**
MacOS - Safari, Chrome, Firefox: **OK**
