### ISSUE TITLE
Component zur Anzeige von MD und HTML-Fragmenten

### ISSUE THREAD

**Issue by OMarohn** [IHK-GfI/lux-components#6]
Für die Integration von Headless CMS ist es hilfreich eine Komponente zu haben welche MD und HTML-Fragmente sicher anzeigen kann.

Ein guter Startpunkt ist m.E: https://www.npmjs.com/package/ngx-markdown

**Comment by thodic77** [comment]
Die folgenden Komponenten wurden erstellt: 
- lux-html zur Darstellung von Html-Fragmenten und
- lux-markdown zur Darstellung von Html-Fragmenten.

Tests und Beispielseiten wurden ebenfalls angelegt.
