### ISSUE TITLE
lux-autocomplete - Optionpanelbreite soll angepasst werden können

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#77]
Im Rahmen dieses Vorgangs soll die neue Property "luxPanelWidth" eingeführt werden. Über die Property kann die Panelbreite der Vorschläge vergrößert oder verkleinert werden.

**Comment by thodic77** [comment]
Die neue Property "luxPanelWidth" wurde eingeführt. 

Test:
- Demoseite "Autocomplete" öffnen. 
- Auf den Tab "Erweitert" wechseln. 
- In dem Feld "luxPanelWidth" den Wert "500px" eintragen. 
- In das Autocomplete-Feld klicken.
- Prüfen, ob das Optionspanel entsprechend groß ist. 

![image](https://user-images.githubusercontent.com/32597554/114673479-87e18300-9d06-11eb-9f03-fc26572dbdb7.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Erfolgreich getestet unter Windows 10 und MacOS 11.2.3 mit folgenden Browsern (in der jeweils aktuellen Version):
Windows: Edge, Chrome, Firefox -> OK
MacOS: Safari, Chrome, Firefox -> OK
