### ISSUE TITLE
LUX-Table - Reload bei einer Table mit serverseitigem Paging ermöglichen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#79]
Im Rahmen dieses Vorgangs soll die Tabelle so erweitert werden, dass man einen Reload von außen triggern kann.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt.

Test

- Demoseite "Tabelle (mit serverseitigen Daten)" öffnen. 
- Den Button "Neuladen" anklicken. 
- Prüfen, ob sich der Name in der Tabelle geändert hat (z.B. Hydrogen -> Hydrogen_1).

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test unter Windows 10 und MacOS 11.2.3 in div. Browsern (jeweils aktuelle Version):

- Demoseite "Tabelle (mit serverseitigen Daten)" öffnen.
- Den Button "Neuladen" anklicken.
- Prüfen, ob sich der Name in der Tabelle geändert hat (z.B. Hydrogen -> Hydrogen_1).

Ergebnis:
Windows: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Firefox, Chrome -> OK
