### ISSUE TITLE
Filter-Textfelder (in LUX-Table z.B.) sollten Autocomplete Attribute zur Verfügung stellen

### ISSUE THREAD

**Issue by hahny93** [IHK-GfI/lux-components#8]
Könnte man (in einer LUX-Table beispielsweise) das Autocomplete Verhalten beeinflussen, ließe sich Nutzern direkt passende Vorschläge einblenden bzw. unpassende ausblenden.

In meinem Beispiel wird eine Adresszeile in einer Terminplan-Tabelle vorgeschlagen. 
Gäbe es stattdessen die Möglichkeit per "name"-Attribut im darunterliegenden Input-Feld ein eigenes Feld zu definieren, wären die Browser-eigenen Vorschläge direkt zu nutzen.
Oder direkt über das "autocomplete"-Attribut die Vorschläge deaktivierbar machen.

![image](https://user-images.githubusercontent.com/40039731/79325733-faf8c380-7f11-11ea-93c1-0655b1dd97d6.png)

**Comment by thodic77** [comment]
- **lux-table**: Die LuxTable stellt jetzt den Filter als LuxInputComponent zur Verfügung.
- **lux-table**: Der Defaultwert für das Autocomplete-Attribut des Tabellenfilters ist jetzt "off".
- **lux-input**: Das Attribut "luxName" hinzugefügt.
- **lux-textarea**: Das Attribut "luxName" hinzugefügt.
- In den Demos das Attribut "luxName" für alle Eingabefelder gesetzt.

**Comment by a-erinola** [comment]
Erfolgreich getestet.
