### ISSUE TITLE
LUX-Filterdialog löscht den falschen Filter

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#81]
Wenn man im Filterdialog auf den Löschbutton drückt wird nicht der korrekte Filter gelöscht.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

Test

- Demoseite "Filter" öffnen.
- Im Filter beliebige Werte ändern. 
- Das Filtermenü (Icon mit drei Punkten) öffnen.
- Speichern anklicken. 
- Einen beliebigen Namen eingeben. 
- Auf diese Weise mehrere Filter anlegen. 
- Dann im Filtermenü "Laden" anklicken.
- Jetzt einen Filter in der Mitte löschen. 
- Prüfen, ob der richtige Filter gelöscht wurde und nicht der erste.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise (1809) und MacOS 11.3.1 mit folgenden Browsern (jeweils aktuellste Version) getestet:
Windows: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
