### ISSUE TITLE
LUX-Filter soll keine doppelten Namen mehr akzeptieren

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#83]
Beim Speichern soll geprüft werden, ob des den Filternamen bereits gibt.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

Test

- Demoseite "Filter" öffnen.
- Im Filter beliebige Werte ändern. 
- Das Filtermenü (Icon mit drei Punkten) öffnen.
- Ein bereits vergebenen Namen vergeben.
- Speichern anklicken. 
- Prüfen, dass nicht gespeichert wurde. 
- Prüfen, dass eine Fehlermeldung angezeigt wird.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise (1809) und MacOS 11.3.1 mit folgenden Browsern (jeweils aktuellste Version) getestet:
Windows: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
