### ISSUE TITLE
lux‐file‐list Komponente Erweiterung; einen custom Button ermöglichen label:enhancement 

### ISSUE THREAD

**Issue by aamer4** [IHK-GfI/lux-components#85]
**Ist:** Die lux‐file‐list Komponente bietet keine Flexibilität, einen zusätzlichen Button zu implementieren. ( lux‐file‐list Buttons sind begrenzt).

**Gewünscht:** Die Möglichkeit einen zusätzlichen Button in der Komponente zu implementieren. Z.B. : einen Button, welcher einen Lux Dialog öffnet.

**Comment by thodic77** [comment]
Die Anforderung wurde umgesetzt und die Demo um ein Beispiel erweitert. 

![image](https://user-images.githubusercontent.com/32597554/125955319-04a82ecf-40b0-4872-b1b7-437b38c8e8a6.png)

![image](https://user-images.githubusercontent.com/32597554/125955336-ec11d72b-9368-4a58-95db-ae848a3ff46b.png)

![image](https://user-images.githubusercontent.com/32597554/125955349-80395e91-ddb5-4f7c-8429-72a8480dfc47.png)

@DSeifer: Bitte testen

**Comment by thodic77** [comment]
Der Issue wurde geprüft und anschließen gemergt (siehe Pull Request).
