### ISSUE TITLE
lux-select - "luxPickValue"-Funktion wird zu häufig aufgerufen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#86]
Die "luxPickValue"-Funktion wird zu häufig (mehrere 100-mal, bei 100 Optionen) aufgerufen. Bitte prüfen, ob die Anzahl der Aufrufe der "luxPickValue"-Funktion deutlich reduziert werden kann.

**Comment by thodic77** [comment]
Die "luxPickValue"-Funktion wird jetzt ausschließlich einmal pro Option ausgeführt. D.h. die Aufrufe wurden auf ein Minimum reduziert. 

Test: 
- Demoseite für das Select öfffnen.
- Console anzeigen lassen (z.B. Chrome F12).
- Toggle "pickValue-Funktion nutzen" aktivieren.
- Prüfen, dass in der Console nur eine Ausgabe pro Option erscheint.

![image](https://user-images.githubusercontent.com/32597554/120275988-65a1c580-c2b2-11eb-8c6f-af23e8c66178.png)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Test wie folgt unter Windows 10 Enterprise (V. 1809) und MacOS (V. 11.4) mit den aktuellen Browsern durchgeführt:

- Demoseite für das Select öffnen.
- Console anzeigen lassen.
- Toggle "pickValue-Funktion nutzen" aktivieren.
- Prüfen, dass in der Console nur eine Ausgabe pro Option erscheint.

Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
