### ISSUE TITLE
lux-table: Tooltipps werden nur angezeigt, wenn der Header sortierbar ist

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#88]
Ist-Verhalten: Tooltipps werden nur angezeigt, wenn der Header sortierbar ist.

Sortierbar:
![image](https://user-images.githubusercontent.com/32597554/120288371-6c373980-c2c0-11eb-9e21-adbee56275ba.png)

Nicht sortierbar: 
![image](https://user-images.githubusercontent.com/32597554/120288470-8a049e80-c2c0-11eb-9065-050e5352f24d.png)

Soll-Verhalten: Tooltips sollten immer angezeigt werden.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

Test:

- Demoseite "Table" öffnen. 
- Auf der Karte "Konfiguration" den Tab "Erweitert" anklicken.
- Im Abschnitt "Optionen der Spalten" das Toggle "Sortierbar" für die Spalte "Name" deaktivieren. 
- Prüfen, ob der Tooltipp sowohl für sortierbare als auch für nicht sortierbare Spalten angezeigt wird. 

![image](https://user-images.githubusercontent.com/32597554/123796577-8c6d0f00-d8e5-11eb-88cc-27ca847abb01.png)

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (1809) und macOS 11.4 mit den jeweils aktuellen Browserversionen.
Windows: Edge, Firefox, Chrome, Opera -> OK
macOS: Safari, Firefox, Chrome -> OK
