### ISSUE TITLE
lux-autocomplete: Beim Nachladen von Optionen werden nicht die aktuellsten Auswahloptionen dargestellt

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#89]
In der Komponente kommt es zu einem Fehlverhalten, wenn das Options-Array mit neuen Werten gefüllt wird. Allerdings nur wenn beim Befüllen des Optionsarrays eine Verzögerung enthalten ist, beispielweise wenn die Optionen aus einem REST Service geladen werden.
In diesem Fall enthält das Optionsarray nach dem Laden die neuen Werte. In der Auswahlliste des HTML Templates werden jedoch immer noch die alten (vorherigen) Werte zur Auswahl angeboten.

Das folgende Fehlverhalten kann mit dem gezippten Code (HTML Template & TS Komponente) reproduziert werden:
1. Beim Start enthält das Optionsarray die Werte **"AAA0", "BBB0", "CCC0", "DDD0", "EEE0", "FFF0"**
![Options_Initial](https://user-images.githubusercontent.com/72753526/121154915-a2883200-c847-11eb-812a-45e30af21392.PNG)
2. Es werden die korrekten Werte aus dem Optionsarray zur Auswahl angeboten
![Options_Initial_Open](https://user-images.githubusercontent.com/72753526/121155252-eda24500-c847-11eb-8f79-2b303b800a08.PNG)
3. Nach einer Eingabe von "A" wird das Optionsarray geändert auf **"AAA1", "BBB1", "CCC1", "DDD1", "EEE1", "FFF1"**. Es wird jedoch weiterhin die passende Option "AAA0" aus den vorigen Optionen zur Auswahl angeboten, obwohl das Optionsarray die aktualisierten Werte enthält
![Options_Mismatch](https://user-images.githubusercontent.com/72753526/121155636-483ba100-c848-11eb-910d-a8c9804df4f0.PNG)

Die Ursache liegt in der Komponente lux-autocomplete. Die Variable _**filteredOptions**_ enthält die Optionen und wird im mat-autocomplete des HTML Templates ausgegeben.
![image](https://user-images.githubusercontent.com/72753526/121157206-a3ba5e80-c849-11eb-8775-2bd4c8c22a74.png)

Die Variable ist ein Observable auf die Optionen. Im Falle eines (statischen) Wertearrays Arrays ist **_filteredOptions_** ein Observable auf Werte. Beim Nachladen von Optionen aus einem REST Service wird ein weiteres Observable erzeugt aus dem die Werte hervorgehen. In diesem Fall ist **_filteredOptions_** ein Observable auf ein weiteres Observable. Daher kommt es zu dem oben beschriebenen Fehlverhalten.

Vermutlich müssen die Observable wie in https://stackoverflow.com/questions/48644478/how-to-combine-several-events-into-rxjs-to-retrieve-and-filter-data beschrieben kombiniert werden um das Fehlverhalten zu vermeiden.

[suche.component.zip](https://github.com/IHK-GfI/lux-components/files/6614990/suche.component.zip)

**Comment by thodic77** [comment]
Vielen Dank für die ausführliche Fehlerbeschreibung!

Der Fehler wurde behoben.

Test:

- Demoseite "Autocomplete" öffnen.
- Toggle "Optionen austauschen" aktivieren.
- Prüfen, ob die Optionen ausgetauscht wurden. 

![image](https://user-images.githubusercontent.com/32597554/123786761-5aa27b00-d8da-11eb-83b4-b29686e793fe.png)
![image](https://user-images.githubusercontent.com/32597554/123786873-7efe5780-d8da-11eb-9e4d-13f555942726.png)

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (1809) und macOS 11.4 mit den jeweils aktuellen Browserversionen.
Windows: Edge, Firefox, Chrome, Opera -> OK
macOS: Safari, Firefox, Chrome -> OK
