### ISSUE TITLE
lux-autocomplete: luxValueChange event wird doppelt getriggert

### ISSUE THREAD

**Issue by scbhh-gfi** [IHK-GfI/lux-components#90]
In der Komponente lux-autocomplete wird das event luxValueChange doppelt getriggert.
Dies liegt an einem doppelt ausgeführten emit:
1. Im ngOnInit() wird durch die Subscription (Zeilen 99 & 104) ein emit ausgeführt
![image](https://user-images.githubusercontent.com/72753526/123738505-337d8680-d8a5-11eb-80a1-01213f848408.png)

2. In notifyFormValueChanged wird in Zeile 274 "this.selected$.next(newValue)" ausgeführt, wodurch die Subscription aus dem ngOninit() getriggert und das emit ein erstes mal ausgeführt wird. In Zeile 275 wird das emit ein weiteres mal aufgerufen, wodurch es zur doppelten Ausführung des luxValueChange events kommt
![image](https://user-images.githubusercontent.com/72753526/123738702-966f1d80-d8a5-11eb-8637-789a5cdc3959.png)

Die Zeile **275** "**this.luxValueChange.emit(newValue)**" muss entfernt werden um eine doppelte Ausführung zu vermeiden.

**Comment by thodic77** [comment]
Vielen Dank für die ausführliche Fehlerbeschreibung!

Der Fehler wurde behoben. 

Test: 

- Demoseite "Autocomplete" öffnen. 
- Toggle "Output-Events loggen" aktivieren. 
- Debugconsole (z.B. Chrome F12)
- Eine Option (z.B. Gruppenaufgaben) auswählen.
- In der Debugconsole prüfen, ob nur ein luxValueChange-Event zu sehen ist.

![image](https://user-images.githubusercontent.com/32597554/123784817-1f9f4800-d8d8-11eb-82c6-204358287ea0.png)
![image](https://user-images.githubusercontent.com/32597554/123784995-4b223280-d8d8-11eb-9f43-08c7b0012f6d.png)

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (1809) und macOS 11.4 mit den jeweils aktuellen Browserversionen.
Windows: Edge, Firefox, Chrome, Opera -> OK
macOS: Safari, Firefox, Chrome -> OK
