### ISSUE TITLE
lux-filter-form - Die Filtermethode wird trotz Validierungsfehler aufgerufen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#94]
Die Filtermethode sollte nur aufgerufen werden, wenn das Filterformular keine Validierungsfehler enthält.

**Comment by thodic77** [comment]
Der Fehler wurde behoben. 

Test

- Demoseite "Filter" öffnen.
- Den Filter aufklappen.
- Die Debugconsole (z.B. Chrome F12) öffnen und leeren. 
- Den Button "Filter" anklicken. 
- Prüfen, ob der Text "Please filter..." in der Debugconsole zu sehen ist. 
- Im Filter das Feld "Input *" leeren, um einen Validierungsfehler zu provozieren.
- Die Debugconsole (z.B. Chrome F12) leeren. 
- Den Button "Filter" anklicken. 
- Prüfen, dass kein Text in der Debugconsole erscheint. 

![image](https://user-images.githubusercontent.com/32597554/124079914-04ece080-da4a-11eb-9457-41cdf720f8e0.png)

@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (1809) und macOS 11.4 mit den jeweils aktuellen Browserversionen.
Windows: Edge, Firefox, Chrome, Opera -> OK
macOS: Safari, Firefox, Chrome -> OK
