### ISSUE TITLE
Dependabot Alert: Abhängigkeit "marked" aktualisieren (Regular expression Denial of Service)

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#96]
Im Rahmen dieses Issues soll die Abhängigkeit "marked" auf die Version "2.1.3" angehoben werden.

**Comment by thodic77** [comment]
Die Abhängigkeit "marked" wurde auf die Version "2.1.3" angehoben. 

Test

- Demoseite "Markdown" öffnen.
- Die Komponente vollständig durchtesten. 
- Prüfen, ob noch alles korrekt funktioniert.

@DSeifer: Bitte testen.

**Comment by thodic77** [comment]
Der Issue wurde geprüft und anschließen gemergt (siehe Pull Request).

**Comment by DSeifer** [comment]
Getestet unter macOS 11.5 mit dem aktuellen Safari-Browser: 
M.E. funktioniert die Tabellendarstellung nicht richtig. Die Spalten sind nicht vertikal untereinander ausgerichtet. Dies ist aber auch im Chrome zu sehen. Weitere Browser habe ich nicht getestet.

**Comment by thodic77** [comment]
Der Pull Request ist bereits gemerged. Bitte ggf. einen neuen Issue eröffnen.
