### ISSUE TITLE
lux-autocomplete - Im Strict-Modus ist bei falscher Eingabe das Formular kurzzeitig valide

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components#98]
Darf eine Aktion (z.B. ein Button) nur ausgeführt werden, wenn das Formular valide ist, dann kann es mit einem LUX-Autocomplete im Strict-Mode dazu kommen, dass die Aktion ausgeführt wird, obwohl das LUX-Autocomplete einen ungültigen Wert enthält. Das LUX-Autocomplete erkennt ungültige Werte erst nach einer kurzen Verzögerung. D.h. in diesem Zeitraum kann die Aktion ausgeführt werden, weil das Formular noch valide ist und erst nach der Verzögerung invalidiert wird.

Test
- Demoseite "Filter" öffnen. 
- Die Debugconsole (z.B. Chrome F12) öffnen. 
- Im Autocomplete einen ungültigen Wert eintragen. 
- Den Button "Filtern" anklicken. 
- Prüfen, dass in der Debugconsole keine Filternachricht geloggt wurde. 

![image](https://user-images.githubusercontent.com/32597554/125407488-38b8f600-e3ba-11eb-8644-655ef139b1ed.png)

**Comment by thodic77** [comment]
Der Bug wurde gefixt. 

@DSeifer: Bitte testen

**Comment by thodic77** [comment]
Der Issue wurde geprüft und anschließen gemergt (siehe Pull Request).

**Comment by DSeifer** [comment]
Getestet unter macOS 11.5 mit dem aktuellen Safari-Browser: OK
